<?php Yaf_Loader::import(PATH_APP . '/modules/Admin/views/head.phtml'); ?>
<!--编辑器-->
<link rel="stylesheet" href="/static/admin/editor/themes/default/default.css" />
<script charset="utf-8" src="/static/admin/editor/kindeditor-min.js"></script>
<script charset="utf-8" src="/static/admin/editor/lang/zh_CN.js"></script>
<!--编辑器初始化-->
<script>
    var editor;
    KindEditor.ready(function (K) {
        editor = K.create('textarea[name="content"]', {
            allowFileManager: true,
            filterMode: false,
            minChangeSize: 10
        });
    });</script>


<div class="navbar content-navbar navbar-default navbar-xs" data-toggle="breakpoint"
     data-class-xs="navbar content-navbar navbar-inverse navbar-xs"
     data-class-sm="navbar content-navbar navbar-default navbar-xs">
    <div class="navbar-header">
        <button class="navbar-toggle pull-left" data-toggle="class" data-target="#body-content" data-class-name="show_menu">
            <i class="icon-list"></i>
        </button>

        <a title="添加小组件" href="/xadmin/userwidget/add/?user=1&amp;page_id=home&amp;_redirect=/" class="navbar-toggle pull-right">
            <i class="icon-plus icon-white"></i></a>
        <a class="navbar-brand" data-toggle="collapse" data-target="#top-nav .navbar-collapse">

            <i class="icon-home" style='position:relative;top:4px;'></i> 当前位置：编辑关键词内链

        </a>
    </div>
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">   
        </ul>
        <div class="navbar-btn navbar-right hide-xs">
            <a title="编辑页面" href="<?= $data['referer'] ?>" class="btn btn-primary">
                <i class="icon-plus icon-white"></i> <span>返回列表</span></a>
        </div>
    </div>
</div>    



<form id="managememberFrom" class = "exform rended" enctype = "multipart/form-data" action = "/admin/keyword/update/" method = "post" >
    <input type = "hidden" value = "<?php echo $data['page']['id'] ?>" name = "id">
    <input type = "hidden" value = "<?php echo $data['referer'] ?>" name = "referer">
    <div class = "form-container row clearfix">
        <div id = "column-0" class = "column form-column main col col-sm-9 form-horizontal ui-sortable">

            <div class = "panel panel-default fieldset" id = "box-1">
                <div class = "panel-heading"><i class = "icon icon-chevron-up chevron"></i><h3 class = "panel-title">编辑关键词</h3></div>
                <div class = "panel-body ">

                    <div class = "form-group">
                        <label class = "control-label ">链接描述:</label>
                        <div class = "controls ">
                            <textarea   id = "desc" name="desc" required  minlength="1" maxlength="100" style="width:80%;height:50px;" ><?= htmlspecialchars($data['page']['description'])?></textarea>
                        </div>
                    </div>

                    <div id = "username" class = "form-group">
                        <label class = "control-label ">关键词:</label>
                        <div class = "controls ">
                            <input name = "keywords"   required  minlength="1" maxlength="50" value="<?= $data['page']['keywords'] ?>" class = "text-field admintextinputwidget form-control" id = "id_user_name" maxlength = "50" type = "text">
                        </div>
                    </div>

                    <div id = "username" class = "form-group">
                        <label class = "control-label ">内链地址:</label>
                        <div class = "controls ">
                            <input name = "href_url"   id = "islink"   minlength="5" maxlength="100" value="<?= $data['page']['href_url']?>" class = "text-field admintextinputwidget form-control" type = "text">
                        </div>
                    </div>




                </div>
            </div>
            <div id = "column-1" class = "column form-column sidebar col col-sm-3 ui-sortable"></div>
        </div>

        <div class = "form-actions well well-sm clearfix">
            <button type = "submit" class = "default btn btn-primary hide-xs" name = "_save" data-loading-text = "保存中.."><i class = "icon-save"></i> 保存</button>
        </div>
    </div>
</form>

<input type = 'hidden' id = '_portal_key' value = 'dashboard:home:pos' />


<!--验证-->
<script type="text/javascript" src="/static/js/jquery.validate.min.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.validate.messages.cn.js"></script>


<?php Yaf_Loader::import(PATH_APP . '/modules/Admin/views/foot.phtml'); ?>