/* soapStub.h
   Generated by gSOAP 2.8.14 from demo.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapStub_H
#define soapStub_H
#define SOAP_NAMESPACE_OF_ns2	"http://ws.semtools.ufstone.com/"
#include "stdsoap2.h"
#if GSOAP_VERSION != 20814
# error "GSOAP VERSION MISMATCH IN GENERATED CODE: PLEASE REINSTALL PACKAGE"
#endif

#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE_ns2__commonResult
#define SOAP_TYPE_ns2__commonResult (7)
/* ns2:commonResult */
struct ns2__commonResult
{
	int *code;	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns2__BaiduAccountInfo
#define SOAP_TYPE_ns2__BaiduAccountInfo (9)
/* ns2:BaiduAccountInfo */
struct ns2__BaiduAccountInfo
{
	LONG64 *accountId;	/* optional element of type xsd:long */
	char *accountName;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *domain;	/* optional element of type xsd:string */
	char *apiToken;	/* optional element of type xsd:string */
	char *websiteName;	/* optional element of type xsd:string */
	char *compName;	/* optional element of type xsd:string */
	char *pcContact;	/* optional element of type xsd:string */
	char *pcTelephone;	/* optional element of type xsd:string */
	int *status;	/* optional element of type xsd:int */
	LONG64 *companyId;	/* optional element of type xsd:long */
};
#endif

#ifndef SOAP_TYPE_ns2__Exception
#define SOAP_TYPE_ns2__Exception (12)
/* ns2:Exception */
struct ns2__Exception
{
	char *message;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns2__authLogin
#define SOAP_TYPE_ns2__authLogin (13)
/* ns2:authLogin */
struct ns2__authLogin
{
	char *loginName;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns2__authLoginResponse
#define SOAP_TYPE_ns2__authLoginResponse (14)
/* ns2:authLoginResponse */
struct ns2__authLoginResponse
{
	struct ns2__CompanyType *CompanyType;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns2:CompanyType */
};
#endif

#ifndef SOAP_TYPE_ns2__queryAllAccount
#define SOAP_TYPE_ns2__queryAllAccount (17)
/* ns2:queryAllAccount */
struct ns2__queryAllAccount
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_ns2__queryAllAccountResponse
#define SOAP_TYPE_ns2__queryAllAccountResponse (18)
/* ns2:queryAllAccountResponse */
struct ns2__queryAllAccountResponse
{
	struct ns2__AccountItemType *AccountItemType;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns2:AccountItemType */
};
#endif

#ifndef SOAP_TYPE_ns2__deleteAccount
#define SOAP_TYPE_ns2__deleteAccount (21)
/* ns2:deleteAccount */
struct ns2__deleteAccount
{
	LONG64 *companyId;	/* optional element of type xsd:long */
	LONG64 *accountId;	/* optional element of type xsd:long */
};
#endif

#ifndef SOAP_TYPE_ns2__deleteAccountResponse
#define SOAP_TYPE_ns2__deleteAccountResponse (22)
/* ns2:deleteAccountResponse */
struct ns2__deleteAccountResponse
{
	int code;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns2__queryAccount
#define SOAP_TYPE_ns2__queryAccount (23)
/* ns2:queryAccount */
struct ns2__queryAccount
{
	LONG64 *companyId;	/* optional element of type xsd:long */
};
#endif

#ifndef SOAP_TYPE_ns2__queryAccountResponse
#define SOAP_TYPE_ns2__queryAccountResponse (24)
/* ns2:queryAccountResponse */
struct ns2__queryAccountResponse
{
	struct ns2__AccountItemType *AccountItemType;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns2:AccountItemType */
};
#endif

#ifndef SOAP_TYPE_ns2__addAccount
#define SOAP_TYPE_ns2__addAccount (25)
/* ns2:addAccount */
struct ns2__addAccount
{
	struct ns2__BaiduAccountInfo *BaiduAccountInfo;	/* optional element of type ns2:BaiduAccountInfo */
};
#endif

#ifndef SOAP_TYPE_ns2__addAccountResponse
#define SOAP_TYPE_ns2__addAccountResponse (27)
/* ns2:addAccountResponse */
struct ns2__addAccountResponse
{
	struct ns2__OperateType *OperateType;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns2:OperateType */
};
#endif

#ifndef SOAP_TYPE_ns2__updateAccount
#define SOAP_TYPE_ns2__updateAccount (30)
/* ns2:updateAccount */
struct ns2__updateAccount
{
	struct ns2__BaiduAccountInfo *BaiduAccountInfo;	/* optional element of type ns2:BaiduAccountInfo */
};
#endif

#ifndef SOAP_TYPE_ns2__updateAccountResponse
#define SOAP_TYPE_ns2__updateAccountResponse (31)
/* ns2:updateAccountResponse */
struct ns2__updateAccountResponse
{
	struct ns2__OperateType *OperateType;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns2:OperateType */
};
#endif

#ifndef SOAP_TYPE_ns2__updateLoginPassword
#define SOAP_TYPE_ns2__updateLoginPassword (32)
/* ns2:updateLoginPassword */
struct ns2__updateLoginPassword
{
	char *loginName;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *newPassword;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns2__updateLoginPasswordResponse
#define SOAP_TYPE_ns2__updateLoginPasswordResponse (33)
/* ns2:updateLoginPasswordResponse */
struct ns2__updateLoginPasswordResponse
{
	struct ns2__OperateType *OperateType;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns2:OperateType */
};
#endif

#ifndef SOAP_TYPE_ns2__CompanyType
#define SOAP_TYPE_ns2__CompanyType (15)
/* ns2:CompanyType */
struct ns2__CompanyType
{
	int *code;	/* optional element of type xsd:int */
	LONG64 *companyId;	/* optional element of type xsd:long */
};
#endif

#ifndef SOAP_TYPE_ns2__AccountItemType
#define SOAP_TYPE_ns2__AccountItemType (19)
/* ns2:AccountItemType */
struct ns2__AccountItemType
{
	int *code;	/* optional element of type xsd:int */
	int __sizeaccounts;	/* sequence of elements <accounts> */
	struct ns2__BaiduAccountInfo *accounts;	/* optional element of type ns2:BaiduAccountInfo */
};
#endif

#ifndef SOAP_TYPE_ns2__OperateType
#define SOAP_TYPE_ns2__OperateType (28)
/* ns2:OperateType */
struct ns2__OperateType
{
	int *code;	/* optional element of type xsd:int */
	LONG64 *id;	/* optional element of type xsd:long */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (34)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
	char *__any;
	struct ns2__Exception *ns2__Exception;	/* optional element of type ns2:Exception */
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
};
#endif

#endif

#ifndef SOAP_TYPE___ns1__authLogin
#define SOAP_TYPE___ns1__authLogin (41)
/* Operation wrapper: */
struct __ns1__authLogin
{
	struct ns2__authLogin *ns2__authLogin;	/* optional element of type ns2:authLogin */
};
#endif

#ifndef SOAP_TYPE___ns1__queryAllAccount
#define SOAP_TYPE___ns1__queryAllAccount (45)
/* Operation wrapper: */
struct __ns1__queryAllAccount
{
	struct ns2__queryAllAccount *ns2__queryAllAccount;	/* optional element of type ns2:queryAllAccount */
};
#endif

#ifndef SOAP_TYPE___ns1__deleteAccount
#define SOAP_TYPE___ns1__deleteAccount (49)
/* Operation wrapper: */
struct __ns1__deleteAccount
{
	struct ns2__deleteAccount *ns2__deleteAccount;	/* optional element of type ns2:deleteAccount */
};
#endif

#ifndef SOAP_TYPE___ns1__addAccount
#define SOAP_TYPE___ns1__addAccount (53)
/* Operation wrapper: */
struct __ns1__addAccount
{
	struct ns2__addAccount *ns2__addAccount;	/* optional element of type ns2:addAccount */
};
#endif

#ifndef SOAP_TYPE___ns1__queryAccount
#define SOAP_TYPE___ns1__queryAccount (57)
/* Operation wrapper: */
struct __ns1__queryAccount
{
	struct ns2__queryAccount *ns2__queryAccount;	/* optional element of type ns2:queryAccount */
};
#endif

#ifndef SOAP_TYPE___ns1__updateAccount
#define SOAP_TYPE___ns1__updateAccount (61)
/* Operation wrapper: */
struct __ns1__updateAccount
{
	struct ns2__updateAccount *ns2__updateAccount;	/* optional element of type ns2:updateAccount */
};
#endif

#ifndef SOAP_TYPE___ns1__updateLoginPassword
#define SOAP_TYPE___ns1__updateLoginPassword (65)
/* Operation wrapper: */
struct __ns1__updateLoginPassword
{
	struct ns2__updateLoginPassword *ns2__updateLoginPassword;	/* optional element of type ns2:updateLoginPassword */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (66)
/* SOAP Header: */
struct SOAP_ENV__Header
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (67)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (69)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (70)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stubs                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__authLogin(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns2__authLogin *ns2__authLogin, struct ns2__authLoginResponse *ns2__authLoginResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__queryAllAccount(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns2__queryAllAccount *ns2__queryAllAccount, struct ns2__queryAllAccountResponse *ns2__queryAllAccountResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__deleteAccount(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns2__deleteAccount *ns2__deleteAccount, struct ns2__deleteAccountResponse *ns2__deleteAccountResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__addAccount(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns2__addAccount *ns2__addAccount, struct ns2__addAccountResponse *ns2__addAccountResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__queryAccount(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns2__queryAccount *ns2__queryAccount, struct ns2__queryAccountResponse *ns2__queryAccountResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__updateAccount(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns2__updateAccount *ns2__updateAccount, struct ns2__updateAccountResponse *ns2__updateAccountResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__updateLoginPassword(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns2__updateLoginPassword *ns2__updateLoginPassword, struct ns2__updateLoginPasswordResponse *ns2__updateLoginPasswordResponse);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapStub.h */
