/* soapH.h
   Generated by gSOAP 2.8.14 from demo.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifdef __cplusplus
extern "C" {
#endif
#ifndef WITH_NOIDREF
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 const char ** SOAP_FMAC4 soap_faultcode(struct soap *soap);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_begin(soap), soap_serialize_byte(soap, data), soap_begin_send(soap) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_begin(soap), soap_serialize_int(soap, data), soap_begin_send(soap) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_LONG64
#define SOAP_TYPE_LONG64 (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_LONG64(struct soap*, LONG64 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_LONG64(struct soap*, const char*, int, const LONG64 *, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_in_LONG64(struct soap*, const char*, LONG64 *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_LONG64(struct soap*, const LONG64 *, const char*, const char*);

#ifndef soap_write_LONG64
#define soap_write_LONG64(soap, data) ( soap_begin(soap), soap_serialize_LONG64(soap, data), soap_begin_send(soap) || soap_put_LONG64(soap, data, "long", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_get_LONG64(struct soap*, LONG64 *, const char*, const char*);

#ifndef soap_read_LONG64
#define soap_read_LONG64(soap, data) ( soap_begin_recv(soap) || !soap_get_LONG64(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (70)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_begin(soap), soap_serialize_SOAP_ENV__Fault(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (69)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_begin(soap), soap_serialize_SOAP_ENV__Reason(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (67)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_begin(soap), soap_serialize_SOAP_ENV__Code(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (66)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_begin(soap), soap_serialize_SOAP_ENV__Header(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef SOAP_TYPE___ns1__updateLoginPassword
#define SOAP_TYPE___ns1__updateLoginPassword (65)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__updateLoginPassword(struct soap*, struct __ns1__updateLoginPassword *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__updateLoginPassword(struct soap*, const struct __ns1__updateLoginPassword *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__updateLoginPassword(struct soap*, const char*, int, const struct __ns1__updateLoginPassword *, const char*);
SOAP_FMAC3 struct __ns1__updateLoginPassword * SOAP_FMAC4 soap_in___ns1__updateLoginPassword(struct soap*, const char*, struct __ns1__updateLoginPassword *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__updateLoginPassword(struct soap*, const struct __ns1__updateLoginPassword *, const char*, const char*);

#ifndef soap_write___ns1__updateLoginPassword
#define soap_write___ns1__updateLoginPassword(soap, data) ( soap_begin(soap), soap_serialize___ns1__updateLoginPassword(soap, data), soap_begin_send(soap) || soap_put___ns1__updateLoginPassword(soap, data, "-ns1:updateLoginPassword", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct __ns1__updateLoginPassword * SOAP_FMAC4 soap_get___ns1__updateLoginPassword(struct soap*, struct __ns1__updateLoginPassword *, const char*, const char*);

#ifndef soap_read___ns1__updateLoginPassword
#define soap_read___ns1__updateLoginPassword(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__updateLoginPassword(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE___ns1__updateAccount
#define SOAP_TYPE___ns1__updateAccount (61)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__updateAccount(struct soap*, struct __ns1__updateAccount *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__updateAccount(struct soap*, const struct __ns1__updateAccount *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__updateAccount(struct soap*, const char*, int, const struct __ns1__updateAccount *, const char*);
SOAP_FMAC3 struct __ns1__updateAccount * SOAP_FMAC4 soap_in___ns1__updateAccount(struct soap*, const char*, struct __ns1__updateAccount *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__updateAccount(struct soap*, const struct __ns1__updateAccount *, const char*, const char*);

#ifndef soap_write___ns1__updateAccount
#define soap_write___ns1__updateAccount(soap, data) ( soap_begin(soap), soap_serialize___ns1__updateAccount(soap, data), soap_begin_send(soap) || soap_put___ns1__updateAccount(soap, data, "-ns1:updateAccount", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct __ns1__updateAccount * SOAP_FMAC4 soap_get___ns1__updateAccount(struct soap*, struct __ns1__updateAccount *, const char*, const char*);

#ifndef soap_read___ns1__updateAccount
#define soap_read___ns1__updateAccount(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__updateAccount(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE___ns1__queryAccount
#define SOAP_TYPE___ns1__queryAccount (57)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__queryAccount(struct soap*, struct __ns1__queryAccount *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__queryAccount(struct soap*, const struct __ns1__queryAccount *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__queryAccount(struct soap*, const char*, int, const struct __ns1__queryAccount *, const char*);
SOAP_FMAC3 struct __ns1__queryAccount * SOAP_FMAC4 soap_in___ns1__queryAccount(struct soap*, const char*, struct __ns1__queryAccount *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__queryAccount(struct soap*, const struct __ns1__queryAccount *, const char*, const char*);

#ifndef soap_write___ns1__queryAccount
#define soap_write___ns1__queryAccount(soap, data) ( soap_begin(soap), soap_serialize___ns1__queryAccount(soap, data), soap_begin_send(soap) || soap_put___ns1__queryAccount(soap, data, "-ns1:queryAccount", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct __ns1__queryAccount * SOAP_FMAC4 soap_get___ns1__queryAccount(struct soap*, struct __ns1__queryAccount *, const char*, const char*);

#ifndef soap_read___ns1__queryAccount
#define soap_read___ns1__queryAccount(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__queryAccount(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE___ns1__addAccount
#define SOAP_TYPE___ns1__addAccount (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__addAccount(struct soap*, struct __ns1__addAccount *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__addAccount(struct soap*, const struct __ns1__addAccount *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__addAccount(struct soap*, const char*, int, const struct __ns1__addAccount *, const char*);
SOAP_FMAC3 struct __ns1__addAccount * SOAP_FMAC4 soap_in___ns1__addAccount(struct soap*, const char*, struct __ns1__addAccount *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__addAccount(struct soap*, const struct __ns1__addAccount *, const char*, const char*);

#ifndef soap_write___ns1__addAccount
#define soap_write___ns1__addAccount(soap, data) ( soap_begin(soap), soap_serialize___ns1__addAccount(soap, data), soap_begin_send(soap) || soap_put___ns1__addAccount(soap, data, "-ns1:addAccount", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct __ns1__addAccount * SOAP_FMAC4 soap_get___ns1__addAccount(struct soap*, struct __ns1__addAccount *, const char*, const char*);

#ifndef soap_read___ns1__addAccount
#define soap_read___ns1__addAccount(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__addAccount(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE___ns1__deleteAccount
#define SOAP_TYPE___ns1__deleteAccount (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__deleteAccount(struct soap*, struct __ns1__deleteAccount *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__deleteAccount(struct soap*, const struct __ns1__deleteAccount *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__deleteAccount(struct soap*, const char*, int, const struct __ns1__deleteAccount *, const char*);
SOAP_FMAC3 struct __ns1__deleteAccount * SOAP_FMAC4 soap_in___ns1__deleteAccount(struct soap*, const char*, struct __ns1__deleteAccount *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__deleteAccount(struct soap*, const struct __ns1__deleteAccount *, const char*, const char*);

#ifndef soap_write___ns1__deleteAccount
#define soap_write___ns1__deleteAccount(soap, data) ( soap_begin(soap), soap_serialize___ns1__deleteAccount(soap, data), soap_begin_send(soap) || soap_put___ns1__deleteAccount(soap, data, "-ns1:deleteAccount", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct __ns1__deleteAccount * SOAP_FMAC4 soap_get___ns1__deleteAccount(struct soap*, struct __ns1__deleteAccount *, const char*, const char*);

#ifndef soap_read___ns1__deleteAccount
#define soap_read___ns1__deleteAccount(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__deleteAccount(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE___ns1__queryAllAccount
#define SOAP_TYPE___ns1__queryAllAccount (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__queryAllAccount(struct soap*, struct __ns1__queryAllAccount *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__queryAllAccount(struct soap*, const struct __ns1__queryAllAccount *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__queryAllAccount(struct soap*, const char*, int, const struct __ns1__queryAllAccount *, const char*);
SOAP_FMAC3 struct __ns1__queryAllAccount * SOAP_FMAC4 soap_in___ns1__queryAllAccount(struct soap*, const char*, struct __ns1__queryAllAccount *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__queryAllAccount(struct soap*, const struct __ns1__queryAllAccount *, const char*, const char*);

#ifndef soap_write___ns1__queryAllAccount
#define soap_write___ns1__queryAllAccount(soap, data) ( soap_begin(soap), soap_serialize___ns1__queryAllAccount(soap, data), soap_begin_send(soap) || soap_put___ns1__queryAllAccount(soap, data, "-ns1:queryAllAccount", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct __ns1__queryAllAccount * SOAP_FMAC4 soap_get___ns1__queryAllAccount(struct soap*, struct __ns1__queryAllAccount *, const char*, const char*);

#ifndef soap_read___ns1__queryAllAccount
#define soap_read___ns1__queryAllAccount(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__queryAllAccount(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE___ns1__authLogin
#define SOAP_TYPE___ns1__authLogin (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__authLogin(struct soap*, struct __ns1__authLogin *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__authLogin(struct soap*, const struct __ns1__authLogin *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__authLogin(struct soap*, const char*, int, const struct __ns1__authLogin *, const char*);
SOAP_FMAC3 struct __ns1__authLogin * SOAP_FMAC4 soap_in___ns1__authLogin(struct soap*, const char*, struct __ns1__authLogin *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__authLogin(struct soap*, const struct __ns1__authLogin *, const char*, const char*);

#ifndef soap_write___ns1__authLogin
#define soap_write___ns1__authLogin(soap, data) ( soap_begin(soap), soap_serialize___ns1__authLogin(soap, data), soap_begin_send(soap) || soap_put___ns1__authLogin(soap, data, "-ns1:authLogin", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct __ns1__authLogin * SOAP_FMAC4 soap_get___ns1__authLogin(struct soap*, struct __ns1__authLogin *, const char*, const char*);

#ifndef soap_read___ns1__authLogin
#define soap_read___ns1__authLogin(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__authLogin(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_begin(soap), soap_serialize_SOAP_ENV__Detail(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef SOAP_TYPE_ns2__updateLoginPasswordResponse
#define SOAP_TYPE_ns2__updateLoginPasswordResponse (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__updateLoginPasswordResponse(struct soap*, struct ns2__updateLoginPasswordResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__updateLoginPasswordResponse(struct soap*, const struct ns2__updateLoginPasswordResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__updateLoginPasswordResponse(struct soap*, const char*, int, const struct ns2__updateLoginPasswordResponse *, const char*);
SOAP_FMAC3 struct ns2__updateLoginPasswordResponse * SOAP_FMAC4 soap_in_ns2__updateLoginPasswordResponse(struct soap*, const char*, struct ns2__updateLoginPasswordResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__updateLoginPasswordResponse(struct soap*, const struct ns2__updateLoginPasswordResponse *, const char*, const char*);

#ifndef soap_write_ns2__updateLoginPasswordResponse
#define soap_write_ns2__updateLoginPasswordResponse(soap, data) ( soap_begin(soap), soap_serialize_ns2__updateLoginPasswordResponse(soap, data), soap_begin_send(soap) || soap_put_ns2__updateLoginPasswordResponse(soap, data, "ns2:updateLoginPasswordResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__updateLoginPasswordResponse * SOAP_FMAC4 soap_get_ns2__updateLoginPasswordResponse(struct soap*, struct ns2__updateLoginPasswordResponse *, const char*, const char*);

#ifndef soap_read_ns2__updateLoginPasswordResponse
#define soap_read_ns2__updateLoginPasswordResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__updateLoginPasswordResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns2__updateLoginPassword
#define SOAP_TYPE_ns2__updateLoginPassword (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__updateLoginPassword(struct soap*, struct ns2__updateLoginPassword *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__updateLoginPassword(struct soap*, const struct ns2__updateLoginPassword *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__updateLoginPassword(struct soap*, const char*, int, const struct ns2__updateLoginPassword *, const char*);
SOAP_FMAC3 struct ns2__updateLoginPassword * SOAP_FMAC4 soap_in_ns2__updateLoginPassword(struct soap*, const char*, struct ns2__updateLoginPassword *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__updateLoginPassword(struct soap*, const struct ns2__updateLoginPassword *, const char*, const char*);

#ifndef soap_write_ns2__updateLoginPassword
#define soap_write_ns2__updateLoginPassword(soap, data) ( soap_begin(soap), soap_serialize_ns2__updateLoginPassword(soap, data), soap_begin_send(soap) || soap_put_ns2__updateLoginPassword(soap, data, "ns2:updateLoginPassword", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__updateLoginPassword * SOAP_FMAC4 soap_get_ns2__updateLoginPassword(struct soap*, struct ns2__updateLoginPassword *, const char*, const char*);

#ifndef soap_read_ns2__updateLoginPassword
#define soap_read_ns2__updateLoginPassword(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__updateLoginPassword(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns2__updateAccountResponse
#define SOAP_TYPE_ns2__updateAccountResponse (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__updateAccountResponse(struct soap*, struct ns2__updateAccountResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__updateAccountResponse(struct soap*, const struct ns2__updateAccountResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__updateAccountResponse(struct soap*, const char*, int, const struct ns2__updateAccountResponse *, const char*);
SOAP_FMAC3 struct ns2__updateAccountResponse * SOAP_FMAC4 soap_in_ns2__updateAccountResponse(struct soap*, const char*, struct ns2__updateAccountResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__updateAccountResponse(struct soap*, const struct ns2__updateAccountResponse *, const char*, const char*);

#ifndef soap_write_ns2__updateAccountResponse
#define soap_write_ns2__updateAccountResponse(soap, data) ( soap_begin(soap), soap_serialize_ns2__updateAccountResponse(soap, data), soap_begin_send(soap) || soap_put_ns2__updateAccountResponse(soap, data, "ns2:updateAccountResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__updateAccountResponse * SOAP_FMAC4 soap_get_ns2__updateAccountResponse(struct soap*, struct ns2__updateAccountResponse *, const char*, const char*);

#ifndef soap_read_ns2__updateAccountResponse
#define soap_read_ns2__updateAccountResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__updateAccountResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns2__updateAccount
#define SOAP_TYPE_ns2__updateAccount (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__updateAccount(struct soap*, struct ns2__updateAccount *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__updateAccount(struct soap*, const struct ns2__updateAccount *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__updateAccount(struct soap*, const char*, int, const struct ns2__updateAccount *, const char*);
SOAP_FMAC3 struct ns2__updateAccount * SOAP_FMAC4 soap_in_ns2__updateAccount(struct soap*, const char*, struct ns2__updateAccount *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__updateAccount(struct soap*, const struct ns2__updateAccount *, const char*, const char*);

#ifndef soap_write_ns2__updateAccount
#define soap_write_ns2__updateAccount(soap, data) ( soap_begin(soap), soap_serialize_ns2__updateAccount(soap, data), soap_begin_send(soap) || soap_put_ns2__updateAccount(soap, data, "ns2:updateAccount", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__updateAccount * SOAP_FMAC4 soap_get_ns2__updateAccount(struct soap*, struct ns2__updateAccount *, const char*, const char*);

#ifndef soap_read_ns2__updateAccount
#define soap_read_ns2__updateAccount(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__updateAccount(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns2__OperateType
#define SOAP_TYPE_ns2__OperateType (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__OperateType(struct soap*, struct ns2__OperateType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__OperateType(struct soap*, const struct ns2__OperateType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__OperateType(struct soap*, const char*, int, const struct ns2__OperateType *, const char*);
SOAP_FMAC3 struct ns2__OperateType * SOAP_FMAC4 soap_in_ns2__OperateType(struct soap*, const char*, struct ns2__OperateType *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__OperateType(struct soap*, const struct ns2__OperateType *, const char*, const char*);

#ifndef soap_write_ns2__OperateType
#define soap_write_ns2__OperateType(soap, data) ( soap_begin(soap), soap_serialize_ns2__OperateType(soap, data), soap_begin_send(soap) || soap_put_ns2__OperateType(soap, data, "ns2:OperateType", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__OperateType * SOAP_FMAC4 soap_get_ns2__OperateType(struct soap*, struct ns2__OperateType *, const char*, const char*);

#ifndef soap_read_ns2__OperateType
#define soap_read_ns2__OperateType(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__OperateType(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns2__addAccountResponse
#define SOAP_TYPE_ns2__addAccountResponse (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__addAccountResponse(struct soap*, struct ns2__addAccountResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__addAccountResponse(struct soap*, const struct ns2__addAccountResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__addAccountResponse(struct soap*, const char*, int, const struct ns2__addAccountResponse *, const char*);
SOAP_FMAC3 struct ns2__addAccountResponse * SOAP_FMAC4 soap_in_ns2__addAccountResponse(struct soap*, const char*, struct ns2__addAccountResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__addAccountResponse(struct soap*, const struct ns2__addAccountResponse *, const char*, const char*);

#ifndef soap_write_ns2__addAccountResponse
#define soap_write_ns2__addAccountResponse(soap, data) ( soap_begin(soap), soap_serialize_ns2__addAccountResponse(soap, data), soap_begin_send(soap) || soap_put_ns2__addAccountResponse(soap, data, "ns2:addAccountResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__addAccountResponse * SOAP_FMAC4 soap_get_ns2__addAccountResponse(struct soap*, struct ns2__addAccountResponse *, const char*, const char*);

#ifndef soap_read_ns2__addAccountResponse
#define soap_read_ns2__addAccountResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__addAccountResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns2__addAccount
#define SOAP_TYPE_ns2__addAccount (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__addAccount(struct soap*, struct ns2__addAccount *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__addAccount(struct soap*, const struct ns2__addAccount *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__addAccount(struct soap*, const char*, int, const struct ns2__addAccount *, const char*);
SOAP_FMAC3 struct ns2__addAccount * SOAP_FMAC4 soap_in_ns2__addAccount(struct soap*, const char*, struct ns2__addAccount *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__addAccount(struct soap*, const struct ns2__addAccount *, const char*, const char*);

#ifndef soap_write_ns2__addAccount
#define soap_write_ns2__addAccount(soap, data) ( soap_begin(soap), soap_serialize_ns2__addAccount(soap, data), soap_begin_send(soap) || soap_put_ns2__addAccount(soap, data, "ns2:addAccount", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__addAccount * SOAP_FMAC4 soap_get_ns2__addAccount(struct soap*, struct ns2__addAccount *, const char*, const char*);

#ifndef soap_read_ns2__addAccount
#define soap_read_ns2__addAccount(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__addAccount(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns2__queryAccountResponse
#define SOAP_TYPE_ns2__queryAccountResponse (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__queryAccountResponse(struct soap*, struct ns2__queryAccountResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__queryAccountResponse(struct soap*, const struct ns2__queryAccountResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__queryAccountResponse(struct soap*, const char*, int, const struct ns2__queryAccountResponse *, const char*);
SOAP_FMAC3 struct ns2__queryAccountResponse * SOAP_FMAC4 soap_in_ns2__queryAccountResponse(struct soap*, const char*, struct ns2__queryAccountResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__queryAccountResponse(struct soap*, const struct ns2__queryAccountResponse *, const char*, const char*);

#ifndef soap_write_ns2__queryAccountResponse
#define soap_write_ns2__queryAccountResponse(soap, data) ( soap_begin(soap), soap_serialize_ns2__queryAccountResponse(soap, data), soap_begin_send(soap) || soap_put_ns2__queryAccountResponse(soap, data, "ns2:queryAccountResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__queryAccountResponse * SOAP_FMAC4 soap_get_ns2__queryAccountResponse(struct soap*, struct ns2__queryAccountResponse *, const char*, const char*);

#ifndef soap_read_ns2__queryAccountResponse
#define soap_read_ns2__queryAccountResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__queryAccountResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns2__queryAccount
#define SOAP_TYPE_ns2__queryAccount (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__queryAccount(struct soap*, struct ns2__queryAccount *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__queryAccount(struct soap*, const struct ns2__queryAccount *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__queryAccount(struct soap*, const char*, int, const struct ns2__queryAccount *, const char*);
SOAP_FMAC3 struct ns2__queryAccount * SOAP_FMAC4 soap_in_ns2__queryAccount(struct soap*, const char*, struct ns2__queryAccount *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__queryAccount(struct soap*, const struct ns2__queryAccount *, const char*, const char*);

#ifndef soap_write_ns2__queryAccount
#define soap_write_ns2__queryAccount(soap, data) ( soap_begin(soap), soap_serialize_ns2__queryAccount(soap, data), soap_begin_send(soap) || soap_put_ns2__queryAccount(soap, data, "ns2:queryAccount", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__queryAccount * SOAP_FMAC4 soap_get_ns2__queryAccount(struct soap*, struct ns2__queryAccount *, const char*, const char*);

#ifndef soap_read_ns2__queryAccount
#define soap_read_ns2__queryAccount(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__queryAccount(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns2__deleteAccountResponse
#define SOAP_TYPE_ns2__deleteAccountResponse (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__deleteAccountResponse(struct soap*, struct ns2__deleteAccountResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__deleteAccountResponse(struct soap*, const struct ns2__deleteAccountResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__deleteAccountResponse(struct soap*, const char*, int, const struct ns2__deleteAccountResponse *, const char*);
SOAP_FMAC3 struct ns2__deleteAccountResponse * SOAP_FMAC4 soap_in_ns2__deleteAccountResponse(struct soap*, const char*, struct ns2__deleteAccountResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__deleteAccountResponse(struct soap*, const struct ns2__deleteAccountResponse *, const char*, const char*);

#ifndef soap_write_ns2__deleteAccountResponse
#define soap_write_ns2__deleteAccountResponse(soap, data) ( soap_begin(soap), soap_serialize_ns2__deleteAccountResponse(soap, data), soap_begin_send(soap) || soap_put_ns2__deleteAccountResponse(soap, data, "ns2:deleteAccountResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__deleteAccountResponse * SOAP_FMAC4 soap_get_ns2__deleteAccountResponse(struct soap*, struct ns2__deleteAccountResponse *, const char*, const char*);

#ifndef soap_read_ns2__deleteAccountResponse
#define soap_read_ns2__deleteAccountResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__deleteAccountResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns2__deleteAccount
#define SOAP_TYPE_ns2__deleteAccount (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__deleteAccount(struct soap*, struct ns2__deleteAccount *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__deleteAccount(struct soap*, const struct ns2__deleteAccount *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__deleteAccount(struct soap*, const char*, int, const struct ns2__deleteAccount *, const char*);
SOAP_FMAC3 struct ns2__deleteAccount * SOAP_FMAC4 soap_in_ns2__deleteAccount(struct soap*, const char*, struct ns2__deleteAccount *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__deleteAccount(struct soap*, const struct ns2__deleteAccount *, const char*, const char*);

#ifndef soap_write_ns2__deleteAccount
#define soap_write_ns2__deleteAccount(soap, data) ( soap_begin(soap), soap_serialize_ns2__deleteAccount(soap, data), soap_begin_send(soap) || soap_put_ns2__deleteAccount(soap, data, "ns2:deleteAccount", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__deleteAccount * SOAP_FMAC4 soap_get_ns2__deleteAccount(struct soap*, struct ns2__deleteAccount *, const char*, const char*);

#ifndef soap_read_ns2__deleteAccount
#define soap_read_ns2__deleteAccount(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__deleteAccount(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns2__AccountItemType
#define SOAP_TYPE_ns2__AccountItemType (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__AccountItemType(struct soap*, struct ns2__AccountItemType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__AccountItemType(struct soap*, const struct ns2__AccountItemType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__AccountItemType(struct soap*, const char*, int, const struct ns2__AccountItemType *, const char*);
SOAP_FMAC3 struct ns2__AccountItemType * SOAP_FMAC4 soap_in_ns2__AccountItemType(struct soap*, const char*, struct ns2__AccountItemType *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__AccountItemType(struct soap*, const struct ns2__AccountItemType *, const char*, const char*);

#ifndef soap_write_ns2__AccountItemType
#define soap_write_ns2__AccountItemType(soap, data) ( soap_begin(soap), soap_serialize_ns2__AccountItemType(soap, data), soap_begin_send(soap) || soap_put_ns2__AccountItemType(soap, data, "ns2:AccountItemType", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__AccountItemType * SOAP_FMAC4 soap_get_ns2__AccountItemType(struct soap*, struct ns2__AccountItemType *, const char*, const char*);

#ifndef soap_read_ns2__AccountItemType
#define soap_read_ns2__AccountItemType(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__AccountItemType(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns2__queryAllAccountResponse
#define SOAP_TYPE_ns2__queryAllAccountResponse (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__queryAllAccountResponse(struct soap*, struct ns2__queryAllAccountResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__queryAllAccountResponse(struct soap*, const struct ns2__queryAllAccountResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__queryAllAccountResponse(struct soap*, const char*, int, const struct ns2__queryAllAccountResponse *, const char*);
SOAP_FMAC3 struct ns2__queryAllAccountResponse * SOAP_FMAC4 soap_in_ns2__queryAllAccountResponse(struct soap*, const char*, struct ns2__queryAllAccountResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__queryAllAccountResponse(struct soap*, const struct ns2__queryAllAccountResponse *, const char*, const char*);

#ifndef soap_write_ns2__queryAllAccountResponse
#define soap_write_ns2__queryAllAccountResponse(soap, data) ( soap_begin(soap), soap_serialize_ns2__queryAllAccountResponse(soap, data), soap_begin_send(soap) || soap_put_ns2__queryAllAccountResponse(soap, data, "ns2:queryAllAccountResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__queryAllAccountResponse * SOAP_FMAC4 soap_get_ns2__queryAllAccountResponse(struct soap*, struct ns2__queryAllAccountResponse *, const char*, const char*);

#ifndef soap_read_ns2__queryAllAccountResponse
#define soap_read_ns2__queryAllAccountResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__queryAllAccountResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns2__queryAllAccount
#define SOAP_TYPE_ns2__queryAllAccount (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__queryAllAccount(struct soap*, struct ns2__queryAllAccount *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__queryAllAccount(struct soap*, const struct ns2__queryAllAccount *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__queryAllAccount(struct soap*, const char*, int, const struct ns2__queryAllAccount *, const char*);
SOAP_FMAC3 struct ns2__queryAllAccount * SOAP_FMAC4 soap_in_ns2__queryAllAccount(struct soap*, const char*, struct ns2__queryAllAccount *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__queryAllAccount(struct soap*, const struct ns2__queryAllAccount *, const char*, const char*);

#ifndef soap_write_ns2__queryAllAccount
#define soap_write_ns2__queryAllAccount(soap, data) ( soap_begin(soap), soap_serialize_ns2__queryAllAccount(soap, data), soap_begin_send(soap) || soap_put_ns2__queryAllAccount(soap, data, "ns2:queryAllAccount", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__queryAllAccount * SOAP_FMAC4 soap_get_ns2__queryAllAccount(struct soap*, struct ns2__queryAllAccount *, const char*, const char*);

#ifndef soap_read_ns2__queryAllAccount
#define soap_read_ns2__queryAllAccount(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__queryAllAccount(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns2__CompanyType
#define SOAP_TYPE_ns2__CompanyType (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__CompanyType(struct soap*, struct ns2__CompanyType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__CompanyType(struct soap*, const struct ns2__CompanyType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__CompanyType(struct soap*, const char*, int, const struct ns2__CompanyType *, const char*);
SOAP_FMAC3 struct ns2__CompanyType * SOAP_FMAC4 soap_in_ns2__CompanyType(struct soap*, const char*, struct ns2__CompanyType *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__CompanyType(struct soap*, const struct ns2__CompanyType *, const char*, const char*);

#ifndef soap_write_ns2__CompanyType
#define soap_write_ns2__CompanyType(soap, data) ( soap_begin(soap), soap_serialize_ns2__CompanyType(soap, data), soap_begin_send(soap) || soap_put_ns2__CompanyType(soap, data, "ns2:CompanyType", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__CompanyType * SOAP_FMAC4 soap_get_ns2__CompanyType(struct soap*, struct ns2__CompanyType *, const char*, const char*);

#ifndef soap_read_ns2__CompanyType
#define soap_read_ns2__CompanyType(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__CompanyType(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns2__authLoginResponse
#define SOAP_TYPE_ns2__authLoginResponse (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__authLoginResponse(struct soap*, struct ns2__authLoginResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__authLoginResponse(struct soap*, const struct ns2__authLoginResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__authLoginResponse(struct soap*, const char*, int, const struct ns2__authLoginResponse *, const char*);
SOAP_FMAC3 struct ns2__authLoginResponse * SOAP_FMAC4 soap_in_ns2__authLoginResponse(struct soap*, const char*, struct ns2__authLoginResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__authLoginResponse(struct soap*, const struct ns2__authLoginResponse *, const char*, const char*);

#ifndef soap_write_ns2__authLoginResponse
#define soap_write_ns2__authLoginResponse(soap, data) ( soap_begin(soap), soap_serialize_ns2__authLoginResponse(soap, data), soap_begin_send(soap) || soap_put_ns2__authLoginResponse(soap, data, "ns2:authLoginResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__authLoginResponse * SOAP_FMAC4 soap_get_ns2__authLoginResponse(struct soap*, struct ns2__authLoginResponse *, const char*, const char*);

#ifndef soap_read_ns2__authLoginResponse
#define soap_read_ns2__authLoginResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__authLoginResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns2__authLogin
#define SOAP_TYPE_ns2__authLogin (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__authLogin(struct soap*, struct ns2__authLogin *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__authLogin(struct soap*, const struct ns2__authLogin *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__authLogin(struct soap*, const char*, int, const struct ns2__authLogin *, const char*);
SOAP_FMAC3 struct ns2__authLogin * SOAP_FMAC4 soap_in_ns2__authLogin(struct soap*, const char*, struct ns2__authLogin *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__authLogin(struct soap*, const struct ns2__authLogin *, const char*, const char*);

#ifndef soap_write_ns2__authLogin
#define soap_write_ns2__authLogin(soap, data) ( soap_begin(soap), soap_serialize_ns2__authLogin(soap, data), soap_begin_send(soap) || soap_put_ns2__authLogin(soap, data, "ns2:authLogin", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__authLogin * SOAP_FMAC4 soap_get_ns2__authLogin(struct soap*, struct ns2__authLogin *, const char*, const char*);

#ifndef soap_read_ns2__authLogin
#define soap_read_ns2__authLogin(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__authLogin(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns2__Exception
#define SOAP_TYPE_ns2__Exception (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__Exception(struct soap*, struct ns2__Exception *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__Exception(struct soap*, const struct ns2__Exception *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__Exception(struct soap*, const char*, int, const struct ns2__Exception *, const char*);
SOAP_FMAC3 struct ns2__Exception * SOAP_FMAC4 soap_in_ns2__Exception(struct soap*, const char*, struct ns2__Exception *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__Exception(struct soap*, const struct ns2__Exception *, const char*, const char*);

#ifndef soap_write_ns2__Exception
#define soap_write_ns2__Exception(soap, data) ( soap_begin(soap), soap_serialize_ns2__Exception(soap, data), soap_begin_send(soap) || soap_put_ns2__Exception(soap, data, "ns2:Exception", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__Exception * SOAP_FMAC4 soap_get_ns2__Exception(struct soap*, struct ns2__Exception *, const char*, const char*);

#ifndef soap_read_ns2__Exception
#define soap_read_ns2__Exception(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__Exception(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns2__BaiduAccountInfo
#define SOAP_TYPE_ns2__BaiduAccountInfo (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__BaiduAccountInfo(struct soap*, struct ns2__BaiduAccountInfo *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__BaiduAccountInfo(struct soap*, const struct ns2__BaiduAccountInfo *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__BaiduAccountInfo(struct soap*, const char*, int, const struct ns2__BaiduAccountInfo *, const char*);
SOAP_FMAC3 struct ns2__BaiduAccountInfo * SOAP_FMAC4 soap_in_ns2__BaiduAccountInfo(struct soap*, const char*, struct ns2__BaiduAccountInfo *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__BaiduAccountInfo(struct soap*, const struct ns2__BaiduAccountInfo *, const char*, const char*);

#ifndef soap_write_ns2__BaiduAccountInfo
#define soap_write_ns2__BaiduAccountInfo(soap, data) ( soap_begin(soap), soap_serialize_ns2__BaiduAccountInfo(soap, data), soap_begin_send(soap) || soap_put_ns2__BaiduAccountInfo(soap, data, "ns2:BaiduAccountInfo", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__BaiduAccountInfo * SOAP_FMAC4 soap_get_ns2__BaiduAccountInfo(struct soap*, struct ns2__BaiduAccountInfo *, const char*, const char*);

#ifndef soap_read_ns2__BaiduAccountInfo
#define soap_read_ns2__BaiduAccountInfo(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__BaiduAccountInfo(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns2__commonResult
#define SOAP_TYPE_ns2__commonResult (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__commonResult(struct soap*, struct ns2__commonResult *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__commonResult(struct soap*, const struct ns2__commonResult *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__commonResult(struct soap*, const char*, int, const struct ns2__commonResult *, const char*);
SOAP_FMAC3 struct ns2__commonResult * SOAP_FMAC4 soap_in_ns2__commonResult(struct soap*, const char*, struct ns2__commonResult *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__commonResult(struct soap*, const struct ns2__commonResult *, const char*, const char*);

#ifndef soap_write_ns2__commonResult
#define soap_write_ns2__commonResult(soap, data) ( soap_begin(soap), soap_serialize_ns2__commonResult(soap, data), soap_begin_send(soap) || soap_put_ns2__commonResult(soap, data, "ns2:commonResult", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__commonResult * SOAP_FMAC4 soap_get_ns2__commonResult(struct soap*, struct ns2__commonResult *, const char*, const char*);

#ifndef soap_read_ns2__commonResult
#define soap_read_ns2__commonResult(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__commonResult(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (72)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin(soap), soap_serialize_PointerToSOAP_ENV__Reason(soap, data), soap_begin_send(soap) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (71)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin(soap), soap_serialize_PointerToSOAP_ENV__Detail(soap, data), soap_begin_send(soap) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (68)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_begin(soap), soap_serialize_PointerToSOAP_ENV__Code(soap, data), soap_begin_send(soap) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef SOAP_TYPE_PointerTons2__updateLoginPasswordResponse
#define SOAP_TYPE_PointerTons2__updateLoginPasswordResponse (63)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__updateLoginPasswordResponse(struct soap*, struct ns2__updateLoginPasswordResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__updateLoginPasswordResponse(struct soap*, const char *, int, struct ns2__updateLoginPasswordResponse *const*, const char *);
SOAP_FMAC3 struct ns2__updateLoginPasswordResponse ** SOAP_FMAC4 soap_in_PointerTons2__updateLoginPasswordResponse(struct soap*, const char*, struct ns2__updateLoginPasswordResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__updateLoginPasswordResponse(struct soap*, struct ns2__updateLoginPasswordResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTons2__updateLoginPasswordResponse
#define soap_write_PointerTons2__updateLoginPasswordResponse(soap, data) ( soap_begin(soap), soap_serialize_PointerTons2__updateLoginPasswordResponse(soap, data), soap_begin_send(soap) || soap_put_PointerTons2__updateLoginPasswordResponse(soap, data, "ns2:updateLoginPasswordResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__updateLoginPasswordResponse ** SOAP_FMAC4 soap_get_PointerTons2__updateLoginPasswordResponse(struct soap*, struct ns2__updateLoginPasswordResponse **, const char*, const char*);

#ifndef soap_read_PointerTons2__updateLoginPasswordResponse
#define soap_read_PointerTons2__updateLoginPasswordResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__updateLoginPasswordResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons2__updateLoginPassword
#define SOAP_TYPE_PointerTons2__updateLoginPassword (62)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__updateLoginPassword(struct soap*, struct ns2__updateLoginPassword *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__updateLoginPassword(struct soap*, const char *, int, struct ns2__updateLoginPassword *const*, const char *);
SOAP_FMAC3 struct ns2__updateLoginPassword ** SOAP_FMAC4 soap_in_PointerTons2__updateLoginPassword(struct soap*, const char*, struct ns2__updateLoginPassword **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__updateLoginPassword(struct soap*, struct ns2__updateLoginPassword *const*, const char*, const char*);

#ifndef soap_write_PointerTons2__updateLoginPassword
#define soap_write_PointerTons2__updateLoginPassword(soap, data) ( soap_begin(soap), soap_serialize_PointerTons2__updateLoginPassword(soap, data), soap_begin_send(soap) || soap_put_PointerTons2__updateLoginPassword(soap, data, "ns2:updateLoginPassword", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__updateLoginPassword ** SOAP_FMAC4 soap_get_PointerTons2__updateLoginPassword(struct soap*, struct ns2__updateLoginPassword **, const char*, const char*);

#ifndef soap_read_PointerTons2__updateLoginPassword
#define soap_read_PointerTons2__updateLoginPassword(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__updateLoginPassword(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons2__updateAccountResponse
#define SOAP_TYPE_PointerTons2__updateAccountResponse (59)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__updateAccountResponse(struct soap*, struct ns2__updateAccountResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__updateAccountResponse(struct soap*, const char *, int, struct ns2__updateAccountResponse *const*, const char *);
SOAP_FMAC3 struct ns2__updateAccountResponse ** SOAP_FMAC4 soap_in_PointerTons2__updateAccountResponse(struct soap*, const char*, struct ns2__updateAccountResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__updateAccountResponse(struct soap*, struct ns2__updateAccountResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTons2__updateAccountResponse
#define soap_write_PointerTons2__updateAccountResponse(soap, data) ( soap_begin(soap), soap_serialize_PointerTons2__updateAccountResponse(soap, data), soap_begin_send(soap) || soap_put_PointerTons2__updateAccountResponse(soap, data, "ns2:updateAccountResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__updateAccountResponse ** SOAP_FMAC4 soap_get_PointerTons2__updateAccountResponse(struct soap*, struct ns2__updateAccountResponse **, const char*, const char*);

#ifndef soap_read_PointerTons2__updateAccountResponse
#define soap_read_PointerTons2__updateAccountResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__updateAccountResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons2__updateAccount
#define SOAP_TYPE_PointerTons2__updateAccount (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__updateAccount(struct soap*, struct ns2__updateAccount *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__updateAccount(struct soap*, const char *, int, struct ns2__updateAccount *const*, const char *);
SOAP_FMAC3 struct ns2__updateAccount ** SOAP_FMAC4 soap_in_PointerTons2__updateAccount(struct soap*, const char*, struct ns2__updateAccount **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__updateAccount(struct soap*, struct ns2__updateAccount *const*, const char*, const char*);

#ifndef soap_write_PointerTons2__updateAccount
#define soap_write_PointerTons2__updateAccount(soap, data) ( soap_begin(soap), soap_serialize_PointerTons2__updateAccount(soap, data), soap_begin_send(soap) || soap_put_PointerTons2__updateAccount(soap, data, "ns2:updateAccount", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__updateAccount ** SOAP_FMAC4 soap_get_PointerTons2__updateAccount(struct soap*, struct ns2__updateAccount **, const char*, const char*);

#ifndef soap_read_PointerTons2__updateAccount
#define soap_read_PointerTons2__updateAccount(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__updateAccount(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons2__queryAccountResponse
#define SOAP_TYPE_PointerTons2__queryAccountResponse (55)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__queryAccountResponse(struct soap*, struct ns2__queryAccountResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__queryAccountResponse(struct soap*, const char *, int, struct ns2__queryAccountResponse *const*, const char *);
SOAP_FMAC3 struct ns2__queryAccountResponse ** SOAP_FMAC4 soap_in_PointerTons2__queryAccountResponse(struct soap*, const char*, struct ns2__queryAccountResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__queryAccountResponse(struct soap*, struct ns2__queryAccountResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTons2__queryAccountResponse
#define soap_write_PointerTons2__queryAccountResponse(soap, data) ( soap_begin(soap), soap_serialize_PointerTons2__queryAccountResponse(soap, data), soap_begin_send(soap) || soap_put_PointerTons2__queryAccountResponse(soap, data, "ns2:queryAccountResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__queryAccountResponse ** SOAP_FMAC4 soap_get_PointerTons2__queryAccountResponse(struct soap*, struct ns2__queryAccountResponse **, const char*, const char*);

#ifndef soap_read_PointerTons2__queryAccountResponse
#define soap_read_PointerTons2__queryAccountResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__queryAccountResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons2__queryAccount
#define SOAP_TYPE_PointerTons2__queryAccount (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__queryAccount(struct soap*, struct ns2__queryAccount *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__queryAccount(struct soap*, const char *, int, struct ns2__queryAccount *const*, const char *);
SOAP_FMAC3 struct ns2__queryAccount ** SOAP_FMAC4 soap_in_PointerTons2__queryAccount(struct soap*, const char*, struct ns2__queryAccount **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__queryAccount(struct soap*, struct ns2__queryAccount *const*, const char*, const char*);

#ifndef soap_write_PointerTons2__queryAccount
#define soap_write_PointerTons2__queryAccount(soap, data) ( soap_begin(soap), soap_serialize_PointerTons2__queryAccount(soap, data), soap_begin_send(soap) || soap_put_PointerTons2__queryAccount(soap, data, "ns2:queryAccount", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__queryAccount ** SOAP_FMAC4 soap_get_PointerTons2__queryAccount(struct soap*, struct ns2__queryAccount **, const char*, const char*);

#ifndef soap_read_PointerTons2__queryAccount
#define soap_read_PointerTons2__queryAccount(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__queryAccount(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons2__addAccountResponse
#define SOAP_TYPE_PointerTons2__addAccountResponse (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__addAccountResponse(struct soap*, struct ns2__addAccountResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__addAccountResponse(struct soap*, const char *, int, struct ns2__addAccountResponse *const*, const char *);
SOAP_FMAC3 struct ns2__addAccountResponse ** SOAP_FMAC4 soap_in_PointerTons2__addAccountResponse(struct soap*, const char*, struct ns2__addAccountResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__addAccountResponse(struct soap*, struct ns2__addAccountResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTons2__addAccountResponse
#define soap_write_PointerTons2__addAccountResponse(soap, data) ( soap_begin(soap), soap_serialize_PointerTons2__addAccountResponse(soap, data), soap_begin_send(soap) || soap_put_PointerTons2__addAccountResponse(soap, data, "ns2:addAccountResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__addAccountResponse ** SOAP_FMAC4 soap_get_PointerTons2__addAccountResponse(struct soap*, struct ns2__addAccountResponse **, const char*, const char*);

#ifndef soap_read_PointerTons2__addAccountResponse
#define soap_read_PointerTons2__addAccountResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__addAccountResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons2__addAccount
#define SOAP_TYPE_PointerTons2__addAccount (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__addAccount(struct soap*, struct ns2__addAccount *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__addAccount(struct soap*, const char *, int, struct ns2__addAccount *const*, const char *);
SOAP_FMAC3 struct ns2__addAccount ** SOAP_FMAC4 soap_in_PointerTons2__addAccount(struct soap*, const char*, struct ns2__addAccount **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__addAccount(struct soap*, struct ns2__addAccount *const*, const char*, const char*);

#ifndef soap_write_PointerTons2__addAccount
#define soap_write_PointerTons2__addAccount(soap, data) ( soap_begin(soap), soap_serialize_PointerTons2__addAccount(soap, data), soap_begin_send(soap) || soap_put_PointerTons2__addAccount(soap, data, "ns2:addAccount", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__addAccount ** SOAP_FMAC4 soap_get_PointerTons2__addAccount(struct soap*, struct ns2__addAccount **, const char*, const char*);

#ifndef soap_read_PointerTons2__addAccount
#define soap_read_PointerTons2__addAccount(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__addAccount(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons2__deleteAccountResponse
#define SOAP_TYPE_PointerTons2__deleteAccountResponse (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__deleteAccountResponse(struct soap*, struct ns2__deleteAccountResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__deleteAccountResponse(struct soap*, const char *, int, struct ns2__deleteAccountResponse *const*, const char *);
SOAP_FMAC3 struct ns2__deleteAccountResponse ** SOAP_FMAC4 soap_in_PointerTons2__deleteAccountResponse(struct soap*, const char*, struct ns2__deleteAccountResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__deleteAccountResponse(struct soap*, struct ns2__deleteAccountResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTons2__deleteAccountResponse
#define soap_write_PointerTons2__deleteAccountResponse(soap, data) ( soap_begin(soap), soap_serialize_PointerTons2__deleteAccountResponse(soap, data), soap_begin_send(soap) || soap_put_PointerTons2__deleteAccountResponse(soap, data, "ns2:deleteAccountResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__deleteAccountResponse ** SOAP_FMAC4 soap_get_PointerTons2__deleteAccountResponse(struct soap*, struct ns2__deleteAccountResponse **, const char*, const char*);

#ifndef soap_read_PointerTons2__deleteAccountResponse
#define soap_read_PointerTons2__deleteAccountResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__deleteAccountResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons2__deleteAccount
#define SOAP_TYPE_PointerTons2__deleteAccount (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__deleteAccount(struct soap*, struct ns2__deleteAccount *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__deleteAccount(struct soap*, const char *, int, struct ns2__deleteAccount *const*, const char *);
SOAP_FMAC3 struct ns2__deleteAccount ** SOAP_FMAC4 soap_in_PointerTons2__deleteAccount(struct soap*, const char*, struct ns2__deleteAccount **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__deleteAccount(struct soap*, struct ns2__deleteAccount *const*, const char*, const char*);

#ifndef soap_write_PointerTons2__deleteAccount
#define soap_write_PointerTons2__deleteAccount(soap, data) ( soap_begin(soap), soap_serialize_PointerTons2__deleteAccount(soap, data), soap_begin_send(soap) || soap_put_PointerTons2__deleteAccount(soap, data, "ns2:deleteAccount", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__deleteAccount ** SOAP_FMAC4 soap_get_PointerTons2__deleteAccount(struct soap*, struct ns2__deleteAccount **, const char*, const char*);

#ifndef soap_read_PointerTons2__deleteAccount
#define soap_read_PointerTons2__deleteAccount(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__deleteAccount(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons2__queryAllAccountResponse
#define SOAP_TYPE_PointerTons2__queryAllAccountResponse (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__queryAllAccountResponse(struct soap*, struct ns2__queryAllAccountResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__queryAllAccountResponse(struct soap*, const char *, int, struct ns2__queryAllAccountResponse *const*, const char *);
SOAP_FMAC3 struct ns2__queryAllAccountResponse ** SOAP_FMAC4 soap_in_PointerTons2__queryAllAccountResponse(struct soap*, const char*, struct ns2__queryAllAccountResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__queryAllAccountResponse(struct soap*, struct ns2__queryAllAccountResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTons2__queryAllAccountResponse
#define soap_write_PointerTons2__queryAllAccountResponse(soap, data) ( soap_begin(soap), soap_serialize_PointerTons2__queryAllAccountResponse(soap, data), soap_begin_send(soap) || soap_put_PointerTons2__queryAllAccountResponse(soap, data, "ns2:queryAllAccountResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__queryAllAccountResponse ** SOAP_FMAC4 soap_get_PointerTons2__queryAllAccountResponse(struct soap*, struct ns2__queryAllAccountResponse **, const char*, const char*);

#ifndef soap_read_PointerTons2__queryAllAccountResponse
#define soap_read_PointerTons2__queryAllAccountResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__queryAllAccountResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons2__queryAllAccount
#define SOAP_TYPE_PointerTons2__queryAllAccount (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__queryAllAccount(struct soap*, struct ns2__queryAllAccount *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__queryAllAccount(struct soap*, const char *, int, struct ns2__queryAllAccount *const*, const char *);
SOAP_FMAC3 struct ns2__queryAllAccount ** SOAP_FMAC4 soap_in_PointerTons2__queryAllAccount(struct soap*, const char*, struct ns2__queryAllAccount **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__queryAllAccount(struct soap*, struct ns2__queryAllAccount *const*, const char*, const char*);

#ifndef soap_write_PointerTons2__queryAllAccount
#define soap_write_PointerTons2__queryAllAccount(soap, data) ( soap_begin(soap), soap_serialize_PointerTons2__queryAllAccount(soap, data), soap_begin_send(soap) || soap_put_PointerTons2__queryAllAccount(soap, data, "ns2:queryAllAccount", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__queryAllAccount ** SOAP_FMAC4 soap_get_PointerTons2__queryAllAccount(struct soap*, struct ns2__queryAllAccount **, const char*, const char*);

#ifndef soap_read_PointerTons2__queryAllAccount
#define soap_read_PointerTons2__queryAllAccount(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__queryAllAccount(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons2__authLoginResponse
#define SOAP_TYPE_PointerTons2__authLoginResponse (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__authLoginResponse(struct soap*, struct ns2__authLoginResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__authLoginResponse(struct soap*, const char *, int, struct ns2__authLoginResponse *const*, const char *);
SOAP_FMAC3 struct ns2__authLoginResponse ** SOAP_FMAC4 soap_in_PointerTons2__authLoginResponse(struct soap*, const char*, struct ns2__authLoginResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__authLoginResponse(struct soap*, struct ns2__authLoginResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTons2__authLoginResponse
#define soap_write_PointerTons2__authLoginResponse(soap, data) ( soap_begin(soap), soap_serialize_PointerTons2__authLoginResponse(soap, data), soap_begin_send(soap) || soap_put_PointerTons2__authLoginResponse(soap, data, "ns2:authLoginResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__authLoginResponse ** SOAP_FMAC4 soap_get_PointerTons2__authLoginResponse(struct soap*, struct ns2__authLoginResponse **, const char*, const char*);

#ifndef soap_read_PointerTons2__authLoginResponse
#define soap_read_PointerTons2__authLoginResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__authLoginResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons2__authLogin
#define SOAP_TYPE_PointerTons2__authLogin (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__authLogin(struct soap*, struct ns2__authLogin *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__authLogin(struct soap*, const char *, int, struct ns2__authLogin *const*, const char *);
SOAP_FMAC3 struct ns2__authLogin ** SOAP_FMAC4 soap_in_PointerTons2__authLogin(struct soap*, const char*, struct ns2__authLogin **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__authLogin(struct soap*, struct ns2__authLogin *const*, const char*, const char*);

#ifndef soap_write_PointerTons2__authLogin
#define soap_write_PointerTons2__authLogin(soap, data) ( soap_begin(soap), soap_serialize_PointerTons2__authLogin(soap, data), soap_begin_send(soap) || soap_put_PointerTons2__authLogin(soap, data, "ns2:authLogin", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__authLogin ** SOAP_FMAC4 soap_get_PointerTons2__authLogin(struct soap*, struct ns2__authLogin **, const char*, const char*);

#ifndef soap_read_PointerTons2__authLogin
#define soap_read_PointerTons2__authLogin(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__authLogin(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons2__Exception
#define SOAP_TYPE_PointerTons2__Exception (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__Exception(struct soap*, struct ns2__Exception *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__Exception(struct soap*, const char *, int, struct ns2__Exception *const*, const char *);
SOAP_FMAC3 struct ns2__Exception ** SOAP_FMAC4 soap_in_PointerTons2__Exception(struct soap*, const char*, struct ns2__Exception **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__Exception(struct soap*, struct ns2__Exception *const*, const char*, const char*);

#ifndef soap_write_PointerTons2__Exception
#define soap_write_PointerTons2__Exception(soap, data) ( soap_begin(soap), soap_serialize_PointerTons2__Exception(soap, data), soap_begin_send(soap) || soap_put_PointerTons2__Exception(soap, data, "ns2:Exception", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__Exception ** SOAP_FMAC4 soap_get_PointerTons2__Exception(struct soap*, struct ns2__Exception **, const char*, const char*);

#ifndef soap_read_PointerTons2__Exception
#define soap_read_PointerTons2__Exception(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__Exception(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons2__OperateType
#define SOAP_TYPE_PointerTons2__OperateType (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__OperateType(struct soap*, struct ns2__OperateType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__OperateType(struct soap*, const char *, int, struct ns2__OperateType *const*, const char *);
SOAP_FMAC3 struct ns2__OperateType ** SOAP_FMAC4 soap_in_PointerTons2__OperateType(struct soap*, const char*, struct ns2__OperateType **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__OperateType(struct soap*, struct ns2__OperateType *const*, const char*, const char*);

#ifndef soap_write_PointerTons2__OperateType
#define soap_write_PointerTons2__OperateType(soap, data) ( soap_begin(soap), soap_serialize_PointerTons2__OperateType(soap, data), soap_begin_send(soap) || soap_put_PointerTons2__OperateType(soap, data, "ns2:OperateType", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__OperateType ** SOAP_FMAC4 soap_get_PointerTons2__OperateType(struct soap*, struct ns2__OperateType **, const char*, const char*);

#ifndef soap_read_PointerTons2__OperateType
#define soap_read_PointerTons2__OperateType(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__OperateType(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons2__BaiduAccountInfo
#define SOAP_TYPE_PointerTons2__BaiduAccountInfo (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__BaiduAccountInfo(struct soap*, struct ns2__BaiduAccountInfo *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__BaiduAccountInfo(struct soap*, const char *, int, struct ns2__BaiduAccountInfo *const*, const char *);
SOAP_FMAC3 struct ns2__BaiduAccountInfo ** SOAP_FMAC4 soap_in_PointerTons2__BaiduAccountInfo(struct soap*, const char*, struct ns2__BaiduAccountInfo **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__BaiduAccountInfo(struct soap*, struct ns2__BaiduAccountInfo *const*, const char*, const char*);

#ifndef soap_write_PointerTons2__BaiduAccountInfo
#define soap_write_PointerTons2__BaiduAccountInfo(soap, data) ( soap_begin(soap), soap_serialize_PointerTons2__BaiduAccountInfo(soap, data), soap_begin_send(soap) || soap_put_PointerTons2__BaiduAccountInfo(soap, data, "ns2:BaiduAccountInfo", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__BaiduAccountInfo ** SOAP_FMAC4 soap_get_PointerTons2__BaiduAccountInfo(struct soap*, struct ns2__BaiduAccountInfo **, const char*, const char*);

#ifndef soap_read_PointerTons2__BaiduAccountInfo
#define soap_read_PointerTons2__BaiduAccountInfo(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__BaiduAccountInfo(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons2__AccountItemType
#define SOAP_TYPE_PointerTons2__AccountItemType (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__AccountItemType(struct soap*, struct ns2__AccountItemType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__AccountItemType(struct soap*, const char *, int, struct ns2__AccountItemType *const*, const char *);
SOAP_FMAC3 struct ns2__AccountItemType ** SOAP_FMAC4 soap_in_PointerTons2__AccountItemType(struct soap*, const char*, struct ns2__AccountItemType **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__AccountItemType(struct soap*, struct ns2__AccountItemType *const*, const char*, const char*);

#ifndef soap_write_PointerTons2__AccountItemType
#define soap_write_PointerTons2__AccountItemType(soap, data) ( soap_begin(soap), soap_serialize_PointerTons2__AccountItemType(soap, data), soap_begin_send(soap) || soap_put_PointerTons2__AccountItemType(soap, data, "ns2:AccountItemType", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__AccountItemType ** SOAP_FMAC4 soap_get_PointerTons2__AccountItemType(struct soap*, struct ns2__AccountItemType **, const char*, const char*);

#ifndef soap_read_PointerTons2__AccountItemType
#define soap_read_PointerTons2__AccountItemType(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__AccountItemType(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons2__CompanyType
#define SOAP_TYPE_PointerTons2__CompanyType (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__CompanyType(struct soap*, struct ns2__CompanyType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__CompanyType(struct soap*, const char *, int, struct ns2__CompanyType *const*, const char *);
SOAP_FMAC3 struct ns2__CompanyType ** SOAP_FMAC4 soap_in_PointerTons2__CompanyType(struct soap*, const char*, struct ns2__CompanyType **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__CompanyType(struct soap*, struct ns2__CompanyType *const*, const char*, const char*);

#ifndef soap_write_PointerTons2__CompanyType
#define soap_write_PointerTons2__CompanyType(soap, data) ( soap_begin(soap), soap_serialize_PointerTons2__CompanyType(soap, data), soap_begin_send(soap) || soap_put_PointerTons2__CompanyType(soap, data, "ns2:CompanyType", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__CompanyType ** SOAP_FMAC4 soap_get_PointerTons2__CompanyType(struct soap*, struct ns2__CompanyType **, const char*, const char*);

#ifndef soap_read_PointerTons2__CompanyType
#define soap_read_PointerTons2__CompanyType(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__CompanyType(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerToLONG64
#define SOAP_TYPE_PointerToLONG64 (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToLONG64(struct soap*, LONG64 *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToLONG64(struct soap*, const char *, int, LONG64 *const*, const char *);
SOAP_FMAC3 LONG64 ** SOAP_FMAC4 soap_in_PointerToLONG64(struct soap*, const char*, LONG64 **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToLONG64(struct soap*, LONG64 *const*, const char*, const char*);

#ifndef soap_write_PointerToLONG64
#define soap_write_PointerToLONG64(soap, data) ( soap_begin(soap), soap_serialize_PointerToLONG64(soap, data), soap_begin_send(soap) || soap_put_PointerToLONG64(soap, data, "long", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 LONG64 ** SOAP_FMAC4 soap_get_PointerToLONG64(struct soap*, LONG64 **, const char*, const char*);

#ifndef soap_read_PointerToLONG64
#define soap_read_PointerToLONG64(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToLONG64(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerToint
#define SOAP_TYPE_PointerToint (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToint(struct soap*, int *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToint(struct soap*, const char *, int, int *const*, const char *);
SOAP_FMAC3 int ** SOAP_FMAC4 soap_in_PointerToint(struct soap*, const char*, int **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToint(struct soap*, int *const*, const char*, const char*);

#ifndef soap_write_PointerToint
#define soap_write_PointerToint(soap, data) ( soap_begin(soap), soap_serialize_PointerToint(soap, data), soap_begin_send(soap) || soap_put_PointerToint(soap, data, "int", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 int ** SOAP_FMAC4 soap_get_PointerToint(struct soap*, int **, const char*, const char*);

#ifndef soap_read_PointerToint
#define soap_read_PointerToint(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToint(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_begin(soap), soap_serialize__QName(soap, data), soap_begin_send(soap) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_begin(soap), soap_serialize_string(soap, data), soap_begin_send(soap) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifdef __cplusplus
}
#endif

#endif

/* End of soapH.h */
