<?php Yaf_Loader::import(PATH_APP . '/modules/Admin/views/head.phtml'); ?>
<div class="navbar content-navbar navbar-default navbar-xs" data-toggle="breakpoint"
     data-class-xs="navbar content-navbar navbar-inverse navbar-xs"
     data-class-sm="navbar content-navbar navbar-default navbar-xs">
    <div class="navbar-header">
        <button class="navbar-toggle pull-left" data-toggle="class" data-target="#body-content" data-class-name="show_menu">
            <i class="icon-list"></i>
        </button>
        <a title="添加小组件" href="/xadmin/role/add/?user=1&amp;page_id=home&amp;_redirect=/" class="navbar-toggle pull-right">
            <i class="icon-plus icon-white"></i></a>
        <a class="navbar-brand" data-toggle="collapse" data-target="#top-nav .navbar-collapse">
            <i class="icon-home" style='position:relative;top:4px;'></i> 当前位置：个人面板
        </a>
    </div>
</div>
<div class="dashboard row">
<div class="col-sm-4 column">
        <!--个人信息-->
        <div class="panel panel-default widget addform form-horizontal short_label fieldset" id="88">
            <div class="panel-heading"><i class='icon icon-chevron-up chevron'></i><h3 class="panel-title">个人信息 </h3></div>
            <div class="panel-body " >
                <table class="table table-hover table-striped">
                    <tr>
                        <td>你好</td> <td><?php echo $user_profile['username']; ?></td>
                    </tr>

                    <tr>
                        <td>所属角色</td> <td><?php echo $role_detail['role_name']; ?></td>
                    </tr>

                    <tr>
                        <td>上次登录时间</td> <td><?php
                            if ($user_profile['logindatetime']) {
                                echo date('Y-m-d H:i:s', $user_profile['logindatetime']);
                            } else {
                                echo '--';
                            }
                            ?></td>
                    </tr>

                    <tr>
                        <td>是否设置密保</td> <td><?php echo (int) $user_profile['question'] ? '是' : '否' ?></td>
                    </tr>
                </table>
            </div>
        </div>
    </div>

    <div class="col-sm-4 column">
        <div class="panel panel-default widget addform form-horizontal short_label fieldset" id="88">
            <div class="panel-heading"><i class='icon icon-chevron-up chevron'></i><h3 class="panel-title">系统信息</h3></div>
            <div class="panel-body " >

                <table class="table table-hover table-striped">
                    <tr>
                        <td>服务器时间</td> <td>2014-11-26 11:02:49</td>
                    </tr>

                    <tr>
                        <td>数据表数</td> <td>23</td>
                    </tr>

                    <tr>
                        <td>前台注册用户数</td> <td>32450</td>
                    </tr>

                    <tr>
                        <td>今日新增</td> <td>234</td>
                    </tr>

                    <tr>
                        <td>文档总数</td> <td>2334</td>
                    </tr>

                    <tr>
                        <td>设置管理员</td> <td>5个</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="col-sm-4 column">
        <div class="panel panel-default widget addform form-horizontal short_label fieldset" id="88">
            <div class="panel-heading"><i class='icon icon-chevron-up chevron'></i><h3 class="panel-title">文章发布统计</h3></div>
            <div class="panel-body " >
                <table class="table table-hover table-striped">
                    <tr>
                        <td>文章已发布总量</td> <td><?=$news_count?></td>
                    </tr>

                    <tr>
                        <td>今日已发布的文章量</td> <td><?=$day_news_count?></td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="dashboard row">
    <div class="col-sm-12 column">
        <div class="panel panel-default widget addform form-horizontal short_label fieldset" id="88">
            <div class="panel-heading"><i class='icon icon-chevron-up chevron'></i><h3 class="panel-title">拥有权限</h3></div>
            <div class="panel-body " >
                <div style='padding:10px;'>

                    <?php
                    if ($privilege_foribd) {
                        $count = count($privilege_list);
                        if ($count) {
                            $str = '';
                            foreach ($privilege_list as $key => $value) {
                                $str .= $privilege_map[$value['privilege_id']] . '、';
                            }
                            echo chop($str, '、');
                        } else {
                            echo '该用户没有任何权限';
                        }
                    } else {
                        echo '该用户为超级管理员角色，可以进行任何操作';
                    }
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="dashboard row">
    <div class="col-sm-12 column">
        <div class="panel panel-default widget addform form-horizontal short_label fieldset" id="88">
            <div class="panel-heading"><i class='icon icon-chevron-up chevron'></i><h3 class="panel-title">常用操作</h3></div>
            <div class="panel-body " >
                <div style="padding:10px;">
                    <a href='/admin/category/add'><i class='icon-list-alt'></i> 新建栏目</a>
                    <a style="margin-left:20px;" href='#'><i class='icon-pencil'></i> 新建文档</a>
                    <a style="margin-left:20px;" href='/admin/user/addAdmin/'><i class='icon-user'></i> 添加管理员</a>
                    <a style="margin-left:20px;" href='/admin/user/changePassword/'><i class='icon-wrench'></i> 修改登录密码</a>
                    <a style="margin-left:20px;" href='/admin/user/setPasswordProtect'><i class='icon-briefcase'></i> 设置密保</a>
                </div>
            </div>
        </div>
    </div>
</div>
<input type='hidden' id='_portal_key' value='dashboard:home:pos' />
<?php Yaf_Loader::import(PATH_APP . '/modules/Admin/views/foot.phtml'); ?>