<?php Yaf_Loader::import(PATH_APP . '/modules/Admin/views/head.phtml'); ?>
<div class="navbar content-navbar navbar-default navbar-xs" data-toggle="breakpoint"
     data-class-xs="navbar content-navbar navbar-inverse navbar-xs"
     data-class-sm="navbar content-navbar navbar-default navbar-xs">
    <div class="navbar-header">
        <a class="navbar-brand" data-toggle="collapse" data-target="#top-nav .navbar-collapse">
            <i class="icon-home" style='position:relative;top:4px;'></i> 当前位置：频道管理
        </a>
    </div>
    <div class="navbar-collapse collapse">
        <div class="navbar-btn navbar-right hide-xs">
            <a title="新建栏目" href="/admin/category/add/" class="btn btn-primary">
                <i class="icon-plus icon-white"></i> <span>新建栏目</span>
            </a>
        </div>
    </div>
</div>
<div class="dashboard row">
    <div class="col-sm-12 column">
        <!--频道列表-->
        <div class="panel panel-default widget addform form-horizontal short_label fieldset" id="88">
            <div class="panel-heading"><i class='icon icon-chevron-up chevron'></i><h3 class="panel-title">频道列表 </h3></div>
            <div class="panel-body " >
                <table class="table table-hover table-striped">
                    <tr>
                        <th width="5%">栏目ID</th>
                        <th width="10%">栏目名</th>
                        <th width="5%">英文栏目名</th>
                        <th width="35%">栏目描述</th>
                        <th width="15%">关键字</th>
                        <th width="5%">排序号</th>
                        <th width="5%">状态</th>
                        <th width="25%">操作</th>
                    </tr>
                    <?php
                    foreach ($article_category_list as $key => $value) {
                        ?>
                        <tr>

                            <td><?php echo $value['catid']; ?></td>
                            <td><?php echo $value['html'] . $value['catname']; ?></td>
                            <td><?php echo $value['en']; ?></td>
                            <td><?php echo $value['description']; ?></td>
                            <td><?php echo $value['keyword']; ?></td>
                            <td><?php echo $value['orderid']; ?></td>
                            <td><?php echo $value['showtype'] ? '隐藏' : '显示'; ?></td>
                            <td>
                                <a href='/admin/category/add?cid=<?php echo $value['catid']; ?>'>编辑</a>
                                <a href='/admin/category/delete?cid=<?php echo $value['catid'] ?>' onclick="javascript:return confirm('确定要删除该栏目吗？')">删除</a>
                                <a href='/admin/document/batchAdd?cid=<?=$value['catid'] ?>'>批量添加文章</a>
                            </td>
                        </tr>
                        <?php
                    }
                    ?>
<!--                        <tr>-->
<!--                            <td colspan=9 style='text-align:right;'>--><?php //echo isset($data['page'])?$data['page']:'';   ?><!-- </td>-->
                    <!--                        </tr>-->

                </table>
            </div>
        </div>
    </div>
</div>
<input type='hidden' id='_portal_key' value='dashboard:home:pos' />
<?php Yaf_Loader::import(PATH_APP . '/modules/Admin/views/foot.phtml'); ?>