<?php Yaf_Loader::import(PATH_APP . '/modules/Admin/views/head.phtml'); ?>

<div class="navbar content-navbar navbar-default navbar-xs" data-toggle="breakpoint"
     data-class-xs="navbar content-navbar navbar-inverse navbar-xs"
     data-class-sm="navbar content-navbar navbar-default navbar-xs">
    <div class="navbar-header">
        <button class="navbar-toggle pull-left" data-toggle="class" data-target="#body-content" data-class-name="show_menu">
            <i class="icon-list"></i>
        </button>

        <a title="添加小组件" href="/xadmin/userwidget/add/?user=1&amp;page_id=home&amp;_redirect=/" class="navbar-toggle pull-right">
            <i class="icon-plus icon-white"></i></a>
        <a class="navbar-brand" data-toggle="collapse" data-target="#top-nav .navbar-collapse">

            <i class="icon-home" style='position:relative;top:4px;'></i> 当前位置：修改前台信息

        </a>
    </div>
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">   
        </ul>
        <div class="navbar-btn navbar-right hide-xs">
            <a title="返回列表" onClick="javascript :history.back(-1);" class="btn btn-primary">
                <i class="icon-plus icon-white"></i> <span>返回列表</span></a>
        </div>
    </div>
</div>    



<form class = "exform rended" enctype = "multipart/form-data" action = "/admin/config/update/" method = "post" >
    <input type="hidden" name="var" value="<?php echo $var;?>">
    <div class = "form-container row clearfix">
        <div id = "column-0" class = "column form-column main col col-sm-9 form-horizontal ui-sortable">

            <div class = "panel panel-default fieldset" id = "box-1">
                <div class = "panel-heading"><i class = "icon icon-chevron-up chevron"></i><h3 class = "panel-title">编辑信息</h3></div>
                <div class = "panel-body ">

                    <div class = "panel-body ">

                    <div class = "form-group">
                        <label class = "control-label ">名称</label>
                        <div class = "controls ">
                            <input name = "description" value="<?php echo $data['description'];?>" class = "text-field admintextinputwidget form-control" type = "text">
                        </div>
                    </div>
                    <div class = "form-group">
                        <label class = "control-label ">值（必填）</label>
                        <div class = "controls ">
                            <textarea name="value" style="width:98%;height:150px;" ><?php echo $data['value'];?></textarea>
                        </div>
                    </div>
                </div>
            </div>
            <div id = "column-1" class = "column form-column sidebar col col-sm-3 ui-sortable"></div>
        </div>

        <div class = "form-actions well well-sm clearfix">
            <input type="submit" class="default btn btn-primary hide-xs" name="_save" data-loading-text="保存中.." value="保存"/>
        </div>
    </div>
</form>


<?php Yaf_Loader::import(PATH_APP . '/modules/Admin/views/foot.phtml'); ?>