/* soapH.h
   Generated by gSOAP 2.8.14 from baidu.h

   Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
   The generated code is released under ONE of the following licenses:
   GPL or Genivia's license for commercial use.
   This program is released under the GPL with the additional exemption that
   compiling, linking, and/or using OpenSSL is allowed.
   */

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifdef __cplusplus
extern "C" {
#endif
#ifndef WITH_NOIDREF
    SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
    SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
    SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
    SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

    SOAP_FMAC3 const char ** SOAP_FMAC4 soap_faultcode(struct soap *soap);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
    char *strptime(const char *s, const char *format, struct tm *tm);
    SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
    SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

    SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_begin(soap), soap_serialize_byte(soap, data), soap_begin_send(soap) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
    SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

    SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_begin(soap), soap_serialize_int(soap, data), soap_begin_send(soap) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_LONG64
#define SOAP_TYPE_LONG64 (15)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_default_LONG64(struct soap*, LONG64 *);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out_LONG64(struct soap*, const char*, int, const LONG64 *, const char*);
    SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_in_LONG64(struct soap*, const char*, LONG64 *, const char*);

    SOAP_FMAC3 int SOAP_FMAC4 soap_put_LONG64(struct soap*, const LONG64 *, const char*, const char*);

#ifndef soap_write_LONG64
#define soap_write_LONG64(soap, data) ( soap_begin(soap), soap_serialize_LONG64(soap, data), soap_begin_send(soap) || soap_put_LONG64(soap, data, "long", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_get_LONG64(struct soap*, LONG64 *, const char*, const char*);

#ifndef soap_read_LONG64
#define soap_read_LONG64(soap, data) ( soap_begin_recv(soap) || !soap_get_LONG64(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_float
#define SOAP_TYPE_float (35)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_default_float(struct soap*, float *);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out_float(struct soap*, const char*, int, const float *, const char*);
    SOAP_FMAC3 float * SOAP_FMAC4 soap_in_float(struct soap*, const char*, float *, const char*);

    SOAP_FMAC3 int SOAP_FMAC4 soap_put_float(struct soap*, const float *, const char*, const char*);

#ifndef soap_write_float
#define soap_write_float(soap, data) ( soap_begin(soap), soap_serialize_float(soap, data), soap_begin_send(soap) || soap_put_float(soap, data, "float", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 float * SOAP_FMAC4 soap_get_float(struct soap*, float *, const char*, const char*);

#ifndef soap_read_float
#define soap_read_float(soap, data) ( soap_begin_recv(soap) || !soap_get_float(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_double
#define SOAP_TYPE_double (36)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_default_double(struct soap*, double *);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out_double(struct soap*, const char*, int, const double *, const char*);
    SOAP_FMAC3 double * SOAP_FMAC4 soap_in_double(struct soap*, const char*, double *, const char*);

    SOAP_FMAC3 int SOAP_FMAC4 soap_put_double(struct soap*, const double *, const char*, const char*);

#ifndef soap_write_double
#define soap_write_double(soap, data) ( soap_begin(soap), soap_serialize_double(soap, data), soap_begin_send(soap) || soap_put_double(soap, data, "double", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 double * SOAP_FMAC4 soap_get_double(struct soap*, double *, const char*, const char*);

#ifndef soap_read_double
#define soap_read_double(soap, data) ( soap_begin_recv(soap) || !soap_get_double(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_time
#define SOAP_TYPE_time (10)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_default_time(struct soap*, time_t *);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out_time(struct soap*, const char*, int, const time_t *, const char*);
    SOAP_FMAC3 time_t * SOAP_FMAC4 soap_in_time(struct soap*, const char*, time_t *, const char*);

    SOAP_FMAC3 int SOAP_FMAC4 soap_put_time(struct soap*, const time_t *, const char*, const char*);

#ifndef soap_write_time
#define soap_write_time(soap, data) ( soap_begin(soap), soap_serialize_time(soap, data), soap_begin_send(soap) || soap_put_time(soap, data, "dateTime", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 time_t * SOAP_FMAC4 soap_get_time(struct soap*, time_t *, const char*, const char*);

#ifndef soap_read_time
#define soap_read_time(soap, data) ( soap_begin_recv(soap) || !soap_get_time(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (7)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__boolean(struct soap*, enum xsd__boolean *);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__boolean(struct soap*, const char*, int, const enum xsd__boolean *, const char*);

    SOAP_FMAC3S const char* SOAP_FMAC4S soap_xsd__boolean2s(struct soap*, enum xsd__boolean);
    SOAP_FMAC3 enum xsd__boolean * SOAP_FMAC4 soap_in_xsd__boolean(struct soap*, const char*, enum xsd__boolean *, const char*);

    SOAP_FMAC3S int SOAP_FMAC4S soap_s2xsd__boolean(struct soap*, const char*, enum xsd__boolean *);

    SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__boolean(struct soap*, const enum xsd__boolean *, const char*, const char*);

#ifndef soap_write_xsd__boolean
#define soap_write_xsd__boolean(soap, data) ( soap_begin(soap), soap_serialize_xsd__boolean(soap, data), soap_begin_send(soap) || soap_put_xsd__boolean(soap, data, "xsd:boolean", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 enum xsd__boolean * SOAP_FMAC4 soap_get_xsd__boolean(struct soap*, enum xsd__boolean *, const char*, const char*);

#ifndef soap_read_xsd__boolean
#define soap_read_xsd__boolean(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__boolean(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (62)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
    SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

    SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_begin(soap), soap_serialize_SOAP_ENV__Fault(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (61)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
    SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

    SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_begin(soap), soap_serialize_SOAP_ENV__Reason(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (58)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
    SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

    SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_begin(soap), soap_serialize_SOAP_ENV__Detail(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (56)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
    SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

    SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_begin(soap), soap_serialize_SOAP_ENV__Code(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef SOAP_TYPE___ns1__getReportFileUrl
#define SOAP_TYPE___ns1__getReportFileUrl (55)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__getReportFileUrl(struct soap*, struct __ns1__getReportFileUrl *);
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__getReportFileUrl(struct soap*, const struct __ns1__getReportFileUrl *);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__getReportFileUrl(struct soap*, const char*, int, const struct __ns1__getReportFileUrl *, const char*);
    SOAP_FMAC3 struct __ns1__getReportFileUrl * SOAP_FMAC4 soap_in___ns1__getReportFileUrl(struct soap*, const char*, struct __ns1__getReportFileUrl *, const char*);

    SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__getReportFileUrl(struct soap*, const struct __ns1__getReportFileUrl *, const char*, const char*);

#ifndef soap_write___ns1__getReportFileUrl
#define soap_write___ns1__getReportFileUrl(soap, data) ( soap_begin(soap), soap_serialize___ns1__getReportFileUrl(soap, data), soap_begin_send(soap) || soap_put___ns1__getReportFileUrl(soap, data, "-ns1:getReportFileUrl", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 struct __ns1__getReportFileUrl * SOAP_FMAC4 soap_get___ns1__getReportFileUrl(struct soap*, struct __ns1__getReportFileUrl *, const char*, const char*);

#ifndef soap_read___ns1__getReportFileUrl
#define soap_read___ns1__getReportFileUrl(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__getReportFileUrl(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE___ns1__getReportState
#define SOAP_TYPE___ns1__getReportState (51)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__getReportState(struct soap*, struct __ns1__getReportState *);
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__getReportState(struct soap*, const struct __ns1__getReportState *);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__getReportState(struct soap*, const char*, int, const struct __ns1__getReportState *, const char*);
    SOAP_FMAC3 struct __ns1__getReportState * SOAP_FMAC4 soap_in___ns1__getReportState(struct soap*, const char*, struct __ns1__getReportState *, const char*);

    SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__getReportState(struct soap*, const struct __ns1__getReportState *, const char*, const char*);

#ifndef soap_write___ns1__getReportState
#define soap_write___ns1__getReportState(soap, data) ( soap_begin(soap), soap_serialize___ns1__getReportState(soap, data), soap_begin_send(soap) || soap_put___ns1__getReportState(soap, data, "-ns1:getReportState", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 struct __ns1__getReportState * SOAP_FMAC4 soap_get___ns1__getReportState(struct soap*, struct __ns1__getReportState *, const char*, const char*);

#ifndef soap_read___ns1__getReportState
#define soap_read___ns1__getReportState(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__getReportState(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE___ns1__getProfessionalReportId
#define SOAP_TYPE___ns1__getProfessionalReportId (47)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__getProfessionalReportId(struct soap*, struct __ns1__getProfessionalReportId *);
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__getProfessionalReportId(struct soap*, const struct __ns1__getProfessionalReportId *);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__getProfessionalReportId(struct soap*, const char*, int, const struct __ns1__getProfessionalReportId *, const char*);
    SOAP_FMAC3 struct __ns1__getProfessionalReportId * SOAP_FMAC4 soap_in___ns1__getProfessionalReportId(struct soap*, const char*, struct __ns1__getProfessionalReportId *, const char*);

    SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__getProfessionalReportId(struct soap*, const struct __ns1__getProfessionalReportId *, const char*, const char*);

#ifndef soap_write___ns1__getProfessionalReportId
#define soap_write___ns1__getProfessionalReportId(soap, data) ( soap_begin(soap), soap_serialize___ns1__getProfessionalReportId(soap, data), soap_begin_send(soap) || soap_put___ns1__getProfessionalReportId(soap, data, "-ns1:getProfessionalReportId", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 struct __ns1__getProfessionalReportId * SOAP_FMAC4 soap_get___ns1__getProfessionalReportId(struct soap*, struct __ns1__getProfessionalReportId *, const char*, const char*);

#ifndef soap_read___ns1__getProfessionalReportId
#define soap_read___ns1__getProfessionalReportId(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__getProfessionalReportId(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (41)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
    SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

    SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_begin(soap), soap_serialize_SOAP_ENV__Header(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef SOAP_TYPE_ns2__Failure
#define SOAP_TYPE_ns2__Failure (39)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__Failure(struct soap*, struct ns2__Failure *);
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__Failure(struct soap*, const struct ns2__Failure *);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__Failure(struct soap*, const char*, int, const struct ns2__Failure *, const char*);
    SOAP_FMAC3 struct ns2__Failure * SOAP_FMAC4 soap_in_ns2__Failure(struct soap*, const char*, struct ns2__Failure *, const char*);

    SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__Failure(struct soap*, const struct ns2__Failure *, const char*, const char*);

#ifndef soap_write_ns2__Failure
#define soap_write_ns2__Failure(soap, data) ( soap_begin(soap), soap_serialize_ns2__Failure(soap, data), soap_begin_send(soap) || soap_put_ns2__Failure(soap, data, "ns2:Failure", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 struct ns2__Failure * SOAP_FMAC4 soap_get_ns2__Failure(struct soap*, struct ns2__Failure *, const char*, const char*);

#ifndef soap_read_ns2__Failure
#define soap_read_ns2__Failure(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__Failure(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns2__ResHeader
#define SOAP_TYPE_ns2__ResHeader (38)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__ResHeader(struct soap*, struct ns2__ResHeader *);
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__ResHeader(struct soap*, const struct ns2__ResHeader *);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__ResHeader(struct soap*, const char*, int, const struct ns2__ResHeader *, const char*);
    SOAP_FMAC3 struct ns2__ResHeader * SOAP_FMAC4 soap_in_ns2__ResHeader(struct soap*, const char*, struct ns2__ResHeader *, const char*);

    SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__ResHeader(struct soap*, const struct ns2__ResHeader *, const char*, const char*);

#ifndef soap_write_ns2__ResHeader
#define soap_write_ns2__ResHeader(soap, data) ( soap_begin(soap), soap_serialize_ns2__ResHeader(soap, data), soap_begin_send(soap) || soap_put_ns2__ResHeader(soap, data, "ns2:ResHeader", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 struct ns2__ResHeader * SOAP_FMAC4 soap_get_ns2__ResHeader(struct soap*, struct ns2__ResHeader *, const char*, const char*);

#ifndef soap_read_ns2__ResHeader
#define soap_read_ns2__ResHeader(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__ResHeader(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns2__AuthHeader
#define SOAP_TYPE_ns2__AuthHeader (37)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__AuthHeader(struct soap*, struct ns2__AuthHeader *);
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__AuthHeader(struct soap*, const struct ns2__AuthHeader *);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__AuthHeader(struct soap*, const char*, int, const struct ns2__AuthHeader *, const char*);
    SOAP_FMAC3 struct ns2__AuthHeader * SOAP_FMAC4 soap_in_ns2__AuthHeader(struct soap*, const char*, struct ns2__AuthHeader *, const char*);

    SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__AuthHeader(struct soap*, const struct ns2__AuthHeader *, const char*, const char*);

#ifndef soap_write_ns2__AuthHeader
#define soap_write_ns2__AuthHeader(soap, data) ( soap_begin(soap), soap_serialize_ns2__AuthHeader(soap, data), soap_begin_send(soap) || soap_put_ns2__AuthHeader(soap, data, "ns2:AuthHeader", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 struct ns2__AuthHeader * SOAP_FMAC4 soap_get_ns2__AuthHeader(struct soap*, struct ns2__AuthHeader *, const char*, const char*);

#ifndef soap_read_ns2__AuthHeader
#define soap_read_ns2__AuthHeader(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__AuthHeader(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns2__DoubleMapItemType
#define SOAP_TYPE_ns2__DoubleMapItemType (33)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__DoubleMapItemType(struct soap*, struct ns2__DoubleMapItemType *);
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__DoubleMapItemType(struct soap*, const struct ns2__DoubleMapItemType *);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__DoubleMapItemType(struct soap*, const char*, int, const struct ns2__DoubleMapItemType *, const char*);
    SOAP_FMAC3 struct ns2__DoubleMapItemType * SOAP_FMAC4 soap_in_ns2__DoubleMapItemType(struct soap*, const char*, struct ns2__DoubleMapItemType *, const char*);

    SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__DoubleMapItemType(struct soap*, const struct ns2__DoubleMapItemType *, const char*, const char*);

#ifndef soap_write_ns2__DoubleMapItemType
#define soap_write_ns2__DoubleMapItemType(soap, data) ( soap_begin(soap), soap_serialize_ns2__DoubleMapItemType(soap, data), soap_begin_send(soap) || soap_put_ns2__DoubleMapItemType(soap, data, "ns2:DoubleMapItemType", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 struct ns2__DoubleMapItemType * SOAP_FMAC4 soap_get_ns2__DoubleMapItemType(struct soap*, struct ns2__DoubleMapItemType *, const char*, const char*);

#ifndef soap_read_ns2__DoubleMapItemType
#define soap_read_ns2__DoubleMapItemType(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__DoubleMapItemType(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns2__FloatMapItemType
#define SOAP_TYPE_ns2__FloatMapItemType (31)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__FloatMapItemType(struct soap*, struct ns2__FloatMapItemType *);
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__FloatMapItemType(struct soap*, const struct ns2__FloatMapItemType *);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__FloatMapItemType(struct soap*, const char*, int, const struct ns2__FloatMapItemType *, const char*);
    SOAP_FMAC3 struct ns2__FloatMapItemType * SOAP_FMAC4 soap_in_ns2__FloatMapItemType(struct soap*, const char*, struct ns2__FloatMapItemType *, const char*);

    SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__FloatMapItemType(struct soap*, const struct ns2__FloatMapItemType *, const char*, const char*);

#ifndef soap_write_ns2__FloatMapItemType
#define soap_write_ns2__FloatMapItemType(soap, data) ( soap_begin(soap), soap_serialize_ns2__FloatMapItemType(soap, data), soap_begin_send(soap) || soap_put_ns2__FloatMapItemType(soap, data, "ns2:FloatMapItemType", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 struct ns2__FloatMapItemType * SOAP_FMAC4 soap_get_ns2__FloatMapItemType(struct soap*, struct ns2__FloatMapItemType *, const char*, const char*);

#ifndef soap_read_ns2__FloatMapItemType
#define soap_read_ns2__FloatMapItemType(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__FloatMapItemType(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns2__LongMapItemType
#define SOAP_TYPE_ns2__LongMapItemType (29)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__LongMapItemType(struct soap*, struct ns2__LongMapItemType *);
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__LongMapItemType(struct soap*, const struct ns2__LongMapItemType *);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__LongMapItemType(struct soap*, const char*, int, const struct ns2__LongMapItemType *, const char*);
    SOAP_FMAC3 struct ns2__LongMapItemType * SOAP_FMAC4 soap_in_ns2__LongMapItemType(struct soap*, const char*, struct ns2__LongMapItemType *, const char*);

    SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__LongMapItemType(struct soap*, const struct ns2__LongMapItemType *, const char*, const char*);

#ifndef soap_write_ns2__LongMapItemType
#define soap_write_ns2__LongMapItemType(soap, data) ( soap_begin(soap), soap_serialize_ns2__LongMapItemType(soap, data), soap_begin_send(soap) || soap_put_ns2__LongMapItemType(soap, data, "ns2:LongMapItemType", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 struct ns2__LongMapItemType * SOAP_FMAC4 soap_get_ns2__LongMapItemType(struct soap*, struct ns2__LongMapItemType *, const char*, const char*);

#ifndef soap_read_ns2__LongMapItemType
#define soap_read_ns2__LongMapItemType(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__LongMapItemType(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns2__IntMapItemType
#define SOAP_TYPE_ns2__IntMapItemType (27)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__IntMapItemType(struct soap*, struct ns2__IntMapItemType *);
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__IntMapItemType(struct soap*, const struct ns2__IntMapItemType *);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__IntMapItemType(struct soap*, const char*, int, const struct ns2__IntMapItemType *, const char*);
    SOAP_FMAC3 struct ns2__IntMapItemType * SOAP_FMAC4 soap_in_ns2__IntMapItemType(struct soap*, const char*, struct ns2__IntMapItemType *, const char*);

    SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__IntMapItemType(struct soap*, const struct ns2__IntMapItemType *, const char*, const char*);

#ifndef soap_write_ns2__IntMapItemType
#define soap_write_ns2__IntMapItemType(soap, data) ( soap_begin(soap), soap_serialize_ns2__IntMapItemType(soap, data), soap_begin_send(soap) || soap_put_ns2__IntMapItemType(soap, data, "ns2:IntMapItemType", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 struct ns2__IntMapItemType * SOAP_FMAC4 soap_get_ns2__IntMapItemType(struct soap*, struct ns2__IntMapItemType *, const char*, const char*);

#ifndef soap_read_ns2__IntMapItemType
#define soap_read_ns2__IntMapItemType(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__IntMapItemType(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns2__StringMapItemType
#define SOAP_TYPE_ns2__StringMapItemType (25)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__StringMapItemType(struct soap*, struct ns2__StringMapItemType *);
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__StringMapItemType(struct soap*, const struct ns2__StringMapItemType *);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__StringMapItemType(struct soap*, const char*, int, const struct ns2__StringMapItemType *, const char*);
    SOAP_FMAC3 struct ns2__StringMapItemType * SOAP_FMAC4 soap_in_ns2__StringMapItemType(struct soap*, const char*, struct ns2__StringMapItemType *, const char*);

    SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__StringMapItemType(struct soap*, const struct ns2__StringMapItemType *, const char*, const char*);

#ifndef soap_write_ns2__StringMapItemType
#define soap_write_ns2__StringMapItemType(soap, data) ( soap_begin(soap), soap_serialize_ns2__StringMapItemType(soap, data), soap_begin_send(soap) || soap_put_ns2__StringMapItemType(soap, data, "ns2:StringMapItemType", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 struct ns2__StringMapItemType * SOAP_FMAC4 soap_get_ns2__StringMapItemType(struct soap*, struct ns2__StringMapItemType *, const char*, const char*);

#ifndef soap_read_ns2__StringMapItemType
#define soap_read_ns2__StringMapItemType(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__StringMapItemType(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns2__OptType
#define SOAP_TYPE_ns2__OptType (24)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__OptType(struct soap*, struct ns2__OptType *);
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__OptType(struct soap*, const struct ns2__OptType *);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__OptType(struct soap*, const char*, int, const struct ns2__OptType *, const char*);
    SOAP_FMAC3 struct ns2__OptType * SOAP_FMAC4 soap_in_ns2__OptType(struct soap*, const char*, struct ns2__OptType *, const char*);

    SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__OptType(struct soap*, const struct ns2__OptType *, const char*, const char*);

#ifndef soap_write_ns2__OptType
#define soap_write_ns2__OptType(soap, data) ( soap_begin(soap), soap_serialize_ns2__OptType(soap, data), soap_begin_send(soap) || soap_put_ns2__OptType(soap, data, "ns2:OptType", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 struct ns2__OptType * SOAP_FMAC4 soap_get_ns2__OptType(struct soap*, struct ns2__OptType *, const char*, const char*);

#ifndef soap_read_ns2__OptType
#define soap_read_ns2__OptType(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__OptType(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE__ns1__getReportFileUrlResponse
#define SOAP_TYPE__ns1__getReportFileUrlResponse (23)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__getReportFileUrlResponse(struct soap*, struct _ns1__getReportFileUrlResponse *);
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__getReportFileUrlResponse(struct soap*, const struct _ns1__getReportFileUrlResponse *);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__getReportFileUrlResponse(struct soap*, const char*, int, const struct _ns1__getReportFileUrlResponse *, const char*);
    SOAP_FMAC3 struct _ns1__getReportFileUrlResponse * SOAP_FMAC4 soap_in__ns1__getReportFileUrlResponse(struct soap*, const char*, struct _ns1__getReportFileUrlResponse *, const char*);

    SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__getReportFileUrlResponse(struct soap*, const struct _ns1__getReportFileUrlResponse *, const char*, const char*);

#ifndef soap_write__ns1__getReportFileUrlResponse
#define soap_write__ns1__getReportFileUrlResponse(soap, data) ( soap_begin(soap), soap_serialize__ns1__getReportFileUrlResponse(soap, data), soap_begin_send(soap) || soap_put__ns1__getReportFileUrlResponse(soap, data, "ns1:getReportFileUrlResponse", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 struct _ns1__getReportFileUrlResponse * SOAP_FMAC4 soap_get__ns1__getReportFileUrlResponse(struct soap*, struct _ns1__getReportFileUrlResponse *, const char*, const char*);

#ifndef soap_read__ns1__getReportFileUrlResponse
#define soap_read__ns1__getReportFileUrlResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__getReportFileUrlResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE__ns1__getReportFileUrlRequest
#define SOAP_TYPE__ns1__getReportFileUrlRequest (22)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__getReportFileUrlRequest(struct soap*, struct _ns1__getReportFileUrlRequest *);
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__getReportFileUrlRequest(struct soap*, const struct _ns1__getReportFileUrlRequest *);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__getReportFileUrlRequest(struct soap*, const char*, int, const struct _ns1__getReportFileUrlRequest *, const char*);
    SOAP_FMAC3 struct _ns1__getReportFileUrlRequest * SOAP_FMAC4 soap_in__ns1__getReportFileUrlRequest(struct soap*, const char*, struct _ns1__getReportFileUrlRequest *, const char*);

    SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__getReportFileUrlRequest(struct soap*, const struct _ns1__getReportFileUrlRequest *, const char*, const char*);

#ifndef soap_write__ns1__getReportFileUrlRequest
#define soap_write__ns1__getReportFileUrlRequest(soap, data) ( soap_begin(soap), soap_serialize__ns1__getReportFileUrlRequest(soap, data), soap_begin_send(soap) || soap_put__ns1__getReportFileUrlRequest(soap, data, "ns1:getReportFileUrlRequest", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 struct _ns1__getReportFileUrlRequest * SOAP_FMAC4 soap_get__ns1__getReportFileUrlRequest(struct soap*, struct _ns1__getReportFileUrlRequest *, const char*, const char*);

#ifndef soap_read__ns1__getReportFileUrlRequest
#define soap_read__ns1__getReportFileUrlRequest(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__getReportFileUrlRequest(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE__ns1__getReportStateResponse
#define SOAP_TYPE__ns1__getReportStateResponse (21)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__getReportStateResponse(struct soap*, struct _ns1__getReportStateResponse *);
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__getReportStateResponse(struct soap*, const struct _ns1__getReportStateResponse *);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__getReportStateResponse(struct soap*, const char*, int, const struct _ns1__getReportStateResponse *, const char*);
    SOAP_FMAC3 struct _ns1__getReportStateResponse * SOAP_FMAC4 soap_in__ns1__getReportStateResponse(struct soap*, const char*, struct _ns1__getReportStateResponse *, const char*);

    SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__getReportStateResponse(struct soap*, const struct _ns1__getReportStateResponse *, const char*, const char*);

#ifndef soap_write__ns1__getReportStateResponse
#define soap_write__ns1__getReportStateResponse(soap, data) ( soap_begin(soap), soap_serialize__ns1__getReportStateResponse(soap, data), soap_begin_send(soap) || soap_put__ns1__getReportStateResponse(soap, data, "ns1:getReportStateResponse", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 struct _ns1__getReportStateResponse * SOAP_FMAC4 soap_get__ns1__getReportStateResponse(struct soap*, struct _ns1__getReportStateResponse *, const char*, const char*);

#ifndef soap_read__ns1__getReportStateResponse
#define soap_read__ns1__getReportStateResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__getReportStateResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE__ns1__getReportStateRequest
#define SOAP_TYPE__ns1__getReportStateRequest (20)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__getReportStateRequest(struct soap*, struct _ns1__getReportStateRequest *);
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__getReportStateRequest(struct soap*, const struct _ns1__getReportStateRequest *);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__getReportStateRequest(struct soap*, const char*, int, const struct _ns1__getReportStateRequest *, const char*);
    SOAP_FMAC3 struct _ns1__getReportStateRequest * SOAP_FMAC4 soap_in__ns1__getReportStateRequest(struct soap*, const char*, struct _ns1__getReportStateRequest *, const char*);

    SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__getReportStateRequest(struct soap*, const struct _ns1__getReportStateRequest *, const char*, const char*);

#ifndef soap_write__ns1__getReportStateRequest
#define soap_write__ns1__getReportStateRequest(soap, data) ( soap_begin(soap), soap_serialize__ns1__getReportStateRequest(soap, data), soap_begin_send(soap) || soap_put__ns1__getReportStateRequest(soap, data, "ns1:getReportStateRequest", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 struct _ns1__getReportStateRequest * SOAP_FMAC4 soap_get__ns1__getReportStateRequest(struct soap*, struct _ns1__getReportStateRequest *, const char*, const char*);

#ifndef soap_read__ns1__getReportStateRequest
#define soap_read__ns1__getReportStateRequest(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__getReportStateRequest(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE__ns1__getProfessionalReportIdResponse
#define SOAP_TYPE__ns1__getProfessionalReportIdResponse (19)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__getProfessionalReportIdResponse(struct soap*, struct _ns1__getProfessionalReportIdResponse *);
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__getProfessionalReportIdResponse(struct soap*, const struct _ns1__getProfessionalReportIdResponse *);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__getProfessionalReportIdResponse(struct soap*, const char*, int, const struct _ns1__getProfessionalReportIdResponse *, const char*);
    SOAP_FMAC3 struct _ns1__getProfessionalReportIdResponse * SOAP_FMAC4 soap_in__ns1__getProfessionalReportIdResponse(struct soap*, const char*, struct _ns1__getProfessionalReportIdResponse *, const char*);

    SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__getProfessionalReportIdResponse(struct soap*, const struct _ns1__getProfessionalReportIdResponse *, const char*, const char*);

#ifndef soap_write__ns1__getProfessionalReportIdResponse
#define soap_write__ns1__getProfessionalReportIdResponse(soap, data) ( soap_begin(soap), soap_serialize__ns1__getProfessionalReportIdResponse(soap, data), soap_begin_send(soap) || soap_put__ns1__getProfessionalReportIdResponse(soap, data, "ns1:getProfessionalReportIdResponse", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 struct _ns1__getProfessionalReportIdResponse * SOAP_FMAC4 soap_get__ns1__getProfessionalReportIdResponse(struct soap*, struct _ns1__getProfessionalReportIdResponse *, const char*, const char*);

#ifndef soap_read__ns1__getProfessionalReportIdResponse
#define soap_read__ns1__getProfessionalReportIdResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__getProfessionalReportIdResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE__ns1__getProfessionalReportIdRequest
#define SOAP_TYPE__ns1__getProfessionalReportIdRequest (17)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__getProfessionalReportIdRequest(struct soap*, struct _ns1__getProfessionalReportIdRequest *);
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__getProfessionalReportIdRequest(struct soap*, const struct _ns1__getProfessionalReportIdRequest *);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__getProfessionalReportIdRequest(struct soap*, const char*, int, const struct _ns1__getProfessionalReportIdRequest *, const char*);
    SOAP_FMAC3 struct _ns1__getProfessionalReportIdRequest * SOAP_FMAC4 soap_in__ns1__getProfessionalReportIdRequest(struct soap*, const char*, struct _ns1__getProfessionalReportIdRequest *, const char*);

    SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__getProfessionalReportIdRequest(struct soap*, const struct _ns1__getProfessionalReportIdRequest *, const char*, const char*);

#ifndef soap_write__ns1__getProfessionalReportIdRequest
#define soap_write__ns1__getProfessionalReportIdRequest(soap, data) ( soap_begin(soap), soap_serialize__ns1__getProfessionalReportIdRequest(soap, data), soap_begin_send(soap) || soap_put__ns1__getProfessionalReportIdRequest(soap, data, "ns1:getProfessionalReportIdRequest", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 struct _ns1__getProfessionalReportIdRequest * SOAP_FMAC4 soap_get__ns1__getProfessionalReportIdRequest(struct soap*, struct _ns1__getProfessionalReportIdRequest *, const char*, const char*);

#ifndef soap_read__ns1__getProfessionalReportIdRequest
#define soap_read__ns1__getProfessionalReportIdRequest(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__getProfessionalReportIdRequest(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns1__AttributeType
#define SOAP_TYPE_ns1__AttributeType (13)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__AttributeType(struct soap*, struct ns1__AttributeType *);
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__AttributeType(struct soap*, const struct ns1__AttributeType *);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__AttributeType(struct soap*, const char*, int, const struct ns1__AttributeType *, const char*);
    SOAP_FMAC3 struct ns1__AttributeType * SOAP_FMAC4 soap_in_ns1__AttributeType(struct soap*, const char*, struct ns1__AttributeType *, const char*);

    SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__AttributeType(struct soap*, const struct ns1__AttributeType *, const char*, const char*);

#ifndef soap_write_ns1__AttributeType
#define soap_write_ns1__AttributeType(soap, data) ( soap_begin(soap), soap_serialize_ns1__AttributeType(soap, data), soap_begin_send(soap) || soap_put_ns1__AttributeType(soap, data, "ns1:AttributeType", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 struct ns1__AttributeType * SOAP_FMAC4 soap_get_ns1__AttributeType(struct soap*, struct ns1__AttributeType *, const char*, const char*);

#ifndef soap_read_ns1__AttributeType
#define soap_read_ns1__AttributeType(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__AttributeType(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns1__ReportRequestType
#define SOAP_TYPE_ns1__ReportRequestType (8)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__ReportRequestType(struct soap*, struct ns1__ReportRequestType *);
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__ReportRequestType(struct soap*, const struct ns1__ReportRequestType *);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ReportRequestType(struct soap*, const char*, int, const struct ns1__ReportRequestType *, const char*);
    SOAP_FMAC3 struct ns1__ReportRequestType * SOAP_FMAC4 soap_in_ns1__ReportRequestType(struct soap*, const char*, struct ns1__ReportRequestType *, const char*);

    SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__ReportRequestType(struct soap*, const struct ns1__ReportRequestType *, const char*, const char*);

#ifndef soap_write_ns1__ReportRequestType
#define soap_write_ns1__ReportRequestType(soap, data) ( soap_begin(soap), soap_serialize_ns1__ReportRequestType(soap, data), soap_begin_send(soap) || soap_put_ns1__ReportRequestType(soap, data, "ns1:ReportRequestType", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 struct ns1__ReportRequestType * SOAP_FMAC4 soap_get_ns1__ReportRequestType(struct soap*, struct ns1__ReportRequestType *, const char*, const char*);

#ifndef soap_read_ns1__ReportRequestType
#define soap_read_ns1__ReportRequestType(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__ReportRequestType(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (64)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
    SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin(soap), soap_serialize_PointerToSOAP_ENV__Reason(soap, data), soap_begin_send(soap) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (63)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
    SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin(soap), soap_serialize_PointerToSOAP_ENV__Detail(soap, data), soap_begin_send(soap) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (57)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
    SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_begin(soap), soap_serialize_PointerToSOAP_ENV__Code(soap, data), soap_begin_send(soap) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef SOAP_TYPE_PointerTo_ns1__getReportFileUrlResponse
#define SOAP_TYPE_PointerTo_ns1__getReportFileUrlResponse (53)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__getReportFileUrlResponse(struct soap*, struct _ns1__getReportFileUrlResponse *const*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__getReportFileUrlResponse(struct soap*, const char *, int, struct _ns1__getReportFileUrlResponse *const*, const char *);
    SOAP_FMAC3 struct _ns1__getReportFileUrlResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__getReportFileUrlResponse(struct soap*, const char*, struct _ns1__getReportFileUrlResponse **, const char*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__getReportFileUrlResponse(struct soap*, struct _ns1__getReportFileUrlResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns1__getReportFileUrlResponse
#define soap_write_PointerTo_ns1__getReportFileUrlResponse(soap, data) ( soap_begin(soap), soap_serialize_PointerTo_ns1__getReportFileUrlResponse(soap, data), soap_begin_send(soap) || soap_put_PointerTo_ns1__getReportFileUrlResponse(soap, data, "ns1:getReportFileUrlResponse", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 struct _ns1__getReportFileUrlResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__getReportFileUrlResponse(struct soap*, struct _ns1__getReportFileUrlResponse **, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__getReportFileUrlResponse
#define soap_read_PointerTo_ns1__getReportFileUrlResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__getReportFileUrlResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTo_ns1__getReportFileUrlRequest
#define SOAP_TYPE_PointerTo_ns1__getReportFileUrlRequest (52)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__getReportFileUrlRequest(struct soap*, struct _ns1__getReportFileUrlRequest *const*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__getReportFileUrlRequest(struct soap*, const char *, int, struct _ns1__getReportFileUrlRequest *const*, const char *);
    SOAP_FMAC3 struct _ns1__getReportFileUrlRequest ** SOAP_FMAC4 soap_in_PointerTo_ns1__getReportFileUrlRequest(struct soap*, const char*, struct _ns1__getReportFileUrlRequest **, const char*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__getReportFileUrlRequest(struct soap*, struct _ns1__getReportFileUrlRequest *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns1__getReportFileUrlRequest
#define soap_write_PointerTo_ns1__getReportFileUrlRequest(soap, data) ( soap_begin(soap), soap_serialize_PointerTo_ns1__getReportFileUrlRequest(soap, data), soap_begin_send(soap) || soap_put_PointerTo_ns1__getReportFileUrlRequest(soap, data, "ns1:getReportFileUrlRequest", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 struct _ns1__getReportFileUrlRequest ** SOAP_FMAC4 soap_get_PointerTo_ns1__getReportFileUrlRequest(struct soap*, struct _ns1__getReportFileUrlRequest **, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__getReportFileUrlRequest
#define soap_read_PointerTo_ns1__getReportFileUrlRequest(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__getReportFileUrlRequest(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTo_ns1__getReportStateResponse
#define SOAP_TYPE_PointerTo_ns1__getReportStateResponse (49)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__getReportStateResponse(struct soap*, struct _ns1__getReportStateResponse *const*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__getReportStateResponse(struct soap*, const char *, int, struct _ns1__getReportStateResponse *const*, const char *);
    SOAP_FMAC3 struct _ns1__getReportStateResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__getReportStateResponse(struct soap*, const char*, struct _ns1__getReportStateResponse **, const char*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__getReportStateResponse(struct soap*, struct _ns1__getReportStateResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns1__getReportStateResponse
#define soap_write_PointerTo_ns1__getReportStateResponse(soap, data) ( soap_begin(soap), soap_serialize_PointerTo_ns1__getReportStateResponse(soap, data), soap_begin_send(soap) || soap_put_PointerTo_ns1__getReportStateResponse(soap, data, "ns1:getReportStateResponse", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 struct _ns1__getReportStateResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__getReportStateResponse(struct soap*, struct _ns1__getReportStateResponse **, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__getReportStateResponse
#define soap_read_PointerTo_ns1__getReportStateResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__getReportStateResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTo_ns1__getReportStateRequest
#define SOAP_TYPE_PointerTo_ns1__getReportStateRequest (48)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__getReportStateRequest(struct soap*, struct _ns1__getReportStateRequest *const*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__getReportStateRequest(struct soap*, const char *, int, struct _ns1__getReportStateRequest *const*, const char *);
    SOAP_FMAC3 struct _ns1__getReportStateRequest ** SOAP_FMAC4 soap_in_PointerTo_ns1__getReportStateRequest(struct soap*, const char*, struct _ns1__getReportStateRequest **, const char*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__getReportStateRequest(struct soap*, struct _ns1__getReportStateRequest *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns1__getReportStateRequest
#define soap_write_PointerTo_ns1__getReportStateRequest(soap, data) ( soap_begin(soap), soap_serialize_PointerTo_ns1__getReportStateRequest(soap, data), soap_begin_send(soap) || soap_put_PointerTo_ns1__getReportStateRequest(soap, data, "ns1:getReportStateRequest", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 struct _ns1__getReportStateRequest ** SOAP_FMAC4 soap_get_PointerTo_ns1__getReportStateRequest(struct soap*, struct _ns1__getReportStateRequest **, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__getReportStateRequest
#define soap_read_PointerTo_ns1__getReportStateRequest(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__getReportStateRequest(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTo_ns1__getProfessionalReportIdResponse
#define SOAP_TYPE_PointerTo_ns1__getProfessionalReportIdResponse (45)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__getProfessionalReportIdResponse(struct soap*, struct _ns1__getProfessionalReportIdResponse *const*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__getProfessionalReportIdResponse(struct soap*, const char *, int, struct _ns1__getProfessionalReportIdResponse *const*, const char *);
    SOAP_FMAC3 struct _ns1__getProfessionalReportIdResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__getProfessionalReportIdResponse(struct soap*, const char*, struct _ns1__getProfessionalReportIdResponse **, const char*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__getProfessionalReportIdResponse(struct soap*, struct _ns1__getProfessionalReportIdResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns1__getProfessionalReportIdResponse
#define soap_write_PointerTo_ns1__getProfessionalReportIdResponse(soap, data) ( soap_begin(soap), soap_serialize_PointerTo_ns1__getProfessionalReportIdResponse(soap, data), soap_begin_send(soap) || soap_put_PointerTo_ns1__getProfessionalReportIdResponse(soap, data, "ns1:getProfessionalReportIdResponse", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 struct _ns1__getProfessionalReportIdResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__getProfessionalReportIdResponse(struct soap*, struct _ns1__getProfessionalReportIdResponse **, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__getProfessionalReportIdResponse
#define soap_read_PointerTo_ns1__getProfessionalReportIdResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__getProfessionalReportIdResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTo_ns1__getProfessionalReportIdRequest
#define SOAP_TYPE_PointerTo_ns1__getProfessionalReportIdRequest (44)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__getProfessionalReportIdRequest(struct soap*, struct _ns1__getProfessionalReportIdRequest *const*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__getProfessionalReportIdRequest(struct soap*, const char *, int, struct _ns1__getProfessionalReportIdRequest *const*, const char *);
    SOAP_FMAC3 struct _ns1__getProfessionalReportIdRequest ** SOAP_FMAC4 soap_in_PointerTo_ns1__getProfessionalReportIdRequest(struct soap*, const char*, struct _ns1__getProfessionalReportIdRequest **, const char*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__getProfessionalReportIdRequest(struct soap*, struct _ns1__getProfessionalReportIdRequest *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns1__getProfessionalReportIdRequest
#define soap_write_PointerTo_ns1__getProfessionalReportIdRequest(soap, data) ( soap_begin(soap), soap_serialize_PointerTo_ns1__getProfessionalReportIdRequest(soap, data), soap_begin_send(soap) || soap_put_PointerTo_ns1__getProfessionalReportIdRequest(soap, data, "ns1:getProfessionalReportIdRequest", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 struct _ns1__getProfessionalReportIdRequest ** SOAP_FMAC4 soap_get_PointerTo_ns1__getProfessionalReportIdRequest(struct soap*, struct _ns1__getProfessionalReportIdRequest **, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__getProfessionalReportIdRequest
#define soap_read_PointerTo_ns1__getProfessionalReportIdRequest(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__getProfessionalReportIdRequest(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons2__ResHeader
#define SOAP_TYPE_PointerTons2__ResHeader (43)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__ResHeader(struct soap*, struct ns2__ResHeader *const*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__ResHeader(struct soap*, const char *, int, struct ns2__ResHeader *const*, const char *);
    SOAP_FMAC3 struct ns2__ResHeader ** SOAP_FMAC4 soap_in_PointerTons2__ResHeader(struct soap*, const char*, struct ns2__ResHeader **, const char*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__ResHeader(struct soap*, struct ns2__ResHeader *const*, const char*, const char*);

#ifndef soap_write_PointerTons2__ResHeader
#define soap_write_PointerTons2__ResHeader(soap, data) ( soap_begin(soap), soap_serialize_PointerTons2__ResHeader(soap, data), soap_begin_send(soap) || soap_put_PointerTons2__ResHeader(soap, data, "ns2:ResHeader", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 struct ns2__ResHeader ** SOAP_FMAC4 soap_get_PointerTons2__ResHeader(struct soap*, struct ns2__ResHeader **, const char*, const char*);

#ifndef soap_read_PointerTons2__ResHeader
#define soap_read_PointerTons2__ResHeader(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__ResHeader(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons2__AuthHeader
#define SOAP_TYPE_PointerTons2__AuthHeader (42)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__AuthHeader(struct soap*, struct ns2__AuthHeader *const*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__AuthHeader(struct soap*, const char *, int, struct ns2__AuthHeader *const*, const char *);
    SOAP_FMAC3 struct ns2__AuthHeader ** SOAP_FMAC4 soap_in_PointerTons2__AuthHeader(struct soap*, const char*, struct ns2__AuthHeader **, const char*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__AuthHeader(struct soap*, struct ns2__AuthHeader *const*, const char*, const char*);

#ifndef soap_write_PointerTons2__AuthHeader
#define soap_write_PointerTons2__AuthHeader(soap, data) ( soap_begin(soap), soap_serialize_PointerTons2__AuthHeader(soap, data), soap_begin_send(soap) || soap_put_PointerTons2__AuthHeader(soap, data, "ns2:AuthHeader", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 struct ns2__AuthHeader ** SOAP_FMAC4 soap_get_PointerTons2__AuthHeader(struct soap*, struct ns2__AuthHeader **, const char*, const char*);

#ifndef soap_read_PointerTons2__AuthHeader
#define soap_read_PointerTons2__AuthHeader(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__AuthHeader(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons2__Failure
#define SOAP_TYPE_PointerTons2__Failure (40)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__Failure(struct soap*, struct ns2__Failure *const*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__Failure(struct soap*, const char *, int, struct ns2__Failure *const*, const char *);
    SOAP_FMAC3 struct ns2__Failure ** SOAP_FMAC4 soap_in_PointerTons2__Failure(struct soap*, const char*, struct ns2__Failure **, const char*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__Failure(struct soap*, struct ns2__Failure *const*, const char*, const char*);

#ifndef soap_write_PointerTons2__Failure
#define soap_write_PointerTons2__Failure(soap, data) ( soap_begin(soap), soap_serialize_PointerTons2__Failure(soap, data), soap_begin_send(soap) || soap_put_PointerTons2__Failure(soap, data, "ns2:Failure", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 struct ns2__Failure ** SOAP_FMAC4 soap_get_PointerTons2__Failure(struct soap*, struct ns2__Failure **, const char*, const char*);

#ifndef soap_read_PointerTons2__Failure
#define soap_read_PointerTons2__Failure(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__Failure(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons2__DoubleMapItemType
#define SOAP_TYPE_PointerTons2__DoubleMapItemType (34)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__DoubleMapItemType(struct soap*, struct ns2__DoubleMapItemType *const*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__DoubleMapItemType(struct soap*, const char *, int, struct ns2__DoubleMapItemType *const*, const char *);
    SOAP_FMAC3 struct ns2__DoubleMapItemType ** SOAP_FMAC4 soap_in_PointerTons2__DoubleMapItemType(struct soap*, const char*, struct ns2__DoubleMapItemType **, const char*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__DoubleMapItemType(struct soap*, struct ns2__DoubleMapItemType *const*, const char*, const char*);

#ifndef soap_write_PointerTons2__DoubleMapItemType
#define soap_write_PointerTons2__DoubleMapItemType(soap, data) ( soap_begin(soap), soap_serialize_PointerTons2__DoubleMapItemType(soap, data), soap_begin_send(soap) || soap_put_PointerTons2__DoubleMapItemType(soap, data, "ns2:DoubleMapItemType", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 struct ns2__DoubleMapItemType ** SOAP_FMAC4 soap_get_PointerTons2__DoubleMapItemType(struct soap*, struct ns2__DoubleMapItemType **, const char*, const char*);

#ifndef soap_read_PointerTons2__DoubleMapItemType
#define soap_read_PointerTons2__DoubleMapItemType(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__DoubleMapItemType(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons2__FloatMapItemType
#define SOAP_TYPE_PointerTons2__FloatMapItemType (32)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__FloatMapItemType(struct soap*, struct ns2__FloatMapItemType *const*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__FloatMapItemType(struct soap*, const char *, int, struct ns2__FloatMapItemType *const*, const char *);
    SOAP_FMAC3 struct ns2__FloatMapItemType ** SOAP_FMAC4 soap_in_PointerTons2__FloatMapItemType(struct soap*, const char*, struct ns2__FloatMapItemType **, const char*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__FloatMapItemType(struct soap*, struct ns2__FloatMapItemType *const*, const char*, const char*);

#ifndef soap_write_PointerTons2__FloatMapItemType
#define soap_write_PointerTons2__FloatMapItemType(soap, data) ( soap_begin(soap), soap_serialize_PointerTons2__FloatMapItemType(soap, data), soap_begin_send(soap) || soap_put_PointerTons2__FloatMapItemType(soap, data, "ns2:FloatMapItemType", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 struct ns2__FloatMapItemType ** SOAP_FMAC4 soap_get_PointerTons2__FloatMapItemType(struct soap*, struct ns2__FloatMapItemType **, const char*, const char*);

#ifndef soap_read_PointerTons2__FloatMapItemType
#define soap_read_PointerTons2__FloatMapItemType(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__FloatMapItemType(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons2__LongMapItemType
#define SOAP_TYPE_PointerTons2__LongMapItemType (30)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__LongMapItemType(struct soap*, struct ns2__LongMapItemType *const*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__LongMapItemType(struct soap*, const char *, int, struct ns2__LongMapItemType *const*, const char *);
    SOAP_FMAC3 struct ns2__LongMapItemType ** SOAP_FMAC4 soap_in_PointerTons2__LongMapItemType(struct soap*, const char*, struct ns2__LongMapItemType **, const char*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__LongMapItemType(struct soap*, struct ns2__LongMapItemType *const*, const char*, const char*);

#ifndef soap_write_PointerTons2__LongMapItemType
#define soap_write_PointerTons2__LongMapItemType(soap, data) ( soap_begin(soap), soap_serialize_PointerTons2__LongMapItemType(soap, data), soap_begin_send(soap) || soap_put_PointerTons2__LongMapItemType(soap, data, "ns2:LongMapItemType", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 struct ns2__LongMapItemType ** SOAP_FMAC4 soap_get_PointerTons2__LongMapItemType(struct soap*, struct ns2__LongMapItemType **, const char*, const char*);

#ifndef soap_read_PointerTons2__LongMapItemType
#define soap_read_PointerTons2__LongMapItemType(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__LongMapItemType(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons2__IntMapItemType
#define SOAP_TYPE_PointerTons2__IntMapItemType (28)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__IntMapItemType(struct soap*, struct ns2__IntMapItemType *const*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__IntMapItemType(struct soap*, const char *, int, struct ns2__IntMapItemType *const*, const char *);
    SOAP_FMAC3 struct ns2__IntMapItemType ** SOAP_FMAC4 soap_in_PointerTons2__IntMapItemType(struct soap*, const char*, struct ns2__IntMapItemType **, const char*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__IntMapItemType(struct soap*, struct ns2__IntMapItemType *const*, const char*, const char*);

#ifndef soap_write_PointerTons2__IntMapItemType
#define soap_write_PointerTons2__IntMapItemType(soap, data) ( soap_begin(soap), soap_serialize_PointerTons2__IntMapItemType(soap, data), soap_begin_send(soap) || soap_put_PointerTons2__IntMapItemType(soap, data, "ns2:IntMapItemType", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 struct ns2__IntMapItemType ** SOAP_FMAC4 soap_get_PointerTons2__IntMapItemType(struct soap*, struct ns2__IntMapItemType **, const char*, const char*);

#ifndef soap_read_PointerTons2__IntMapItemType
#define soap_read_PointerTons2__IntMapItemType(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__IntMapItemType(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons2__StringMapItemType
#define SOAP_TYPE_PointerTons2__StringMapItemType (26)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__StringMapItemType(struct soap*, struct ns2__StringMapItemType *const*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__StringMapItemType(struct soap*, const char *, int, struct ns2__StringMapItemType *const*, const char *);
    SOAP_FMAC3 struct ns2__StringMapItemType ** SOAP_FMAC4 soap_in_PointerTons2__StringMapItemType(struct soap*, const char*, struct ns2__StringMapItemType **, const char*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__StringMapItemType(struct soap*, struct ns2__StringMapItemType *const*, const char*, const char*);

#ifndef soap_write_PointerTons2__StringMapItemType
#define soap_write_PointerTons2__StringMapItemType(soap, data) ( soap_begin(soap), soap_serialize_PointerTons2__StringMapItemType(soap, data), soap_begin_send(soap) || soap_put_PointerTons2__StringMapItemType(soap, data, "ns2:StringMapItemType", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 struct ns2__StringMapItemType ** SOAP_FMAC4 soap_get_PointerTons2__StringMapItemType(struct soap*, struct ns2__StringMapItemType **, const char*, const char*);

#ifndef soap_read_PointerTons2__StringMapItemType
#define soap_read_PointerTons2__StringMapItemType(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__StringMapItemType(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons1__ReportRequestType
#define SOAP_TYPE_PointerTons1__ReportRequestType (18)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ReportRequestType(struct soap*, struct ns1__ReportRequestType *const*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ReportRequestType(struct soap*, const char *, int, struct ns1__ReportRequestType *const*, const char *);
    SOAP_FMAC3 struct ns1__ReportRequestType ** SOAP_FMAC4 soap_in_PointerTons1__ReportRequestType(struct soap*, const char*, struct ns1__ReportRequestType **, const char*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ReportRequestType(struct soap*, struct ns1__ReportRequestType *const*, const char*, const char*);

#ifndef soap_write_PointerTons1__ReportRequestType
#define soap_write_PointerTons1__ReportRequestType(soap, data) ( soap_begin(soap), soap_serialize_PointerTons1__ReportRequestType(soap, data), soap_begin_send(soap) || soap_put_PointerTons1__ReportRequestType(soap, data, "ns1:ReportRequestType", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 struct ns1__ReportRequestType ** SOAP_FMAC4 soap_get_PointerTons1__ReportRequestType(struct soap*, struct ns1__ReportRequestType **, const char*, const char*);

#ifndef soap_read_PointerTons1__ReportRequestType
#define soap_read_PointerTons1__ReportRequestType(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__ReportRequestType(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerToLONG64
#define SOAP_TYPE_PointerToLONG64 (16)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToLONG64(struct soap*, LONG64 *const*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToLONG64(struct soap*, const char *, int, LONG64 *const*, const char *);
    SOAP_FMAC3 LONG64 ** SOAP_FMAC4 soap_in_PointerToLONG64(struct soap*, const char*, LONG64 **, const char*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToLONG64(struct soap*, LONG64 *const*, const char*, const char*);

#ifndef soap_write_PointerToLONG64
#define soap_write_PointerToLONG64(soap, data) ( soap_begin(soap), soap_serialize_PointerToLONG64(soap, data), soap_begin_send(soap) || soap_put_PointerToLONG64(soap, data, "long", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 LONG64 ** SOAP_FMAC4 soap_get_PointerToLONG64(struct soap*, LONG64 **, const char*, const char*);

#ifndef soap_read_PointerToLONG64
#define soap_read_PointerToLONG64(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToLONG64(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons1__AttributeType
#define SOAP_TYPE_PointerTons1__AttributeType (14)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__AttributeType(struct soap*, struct ns1__AttributeType *const*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__AttributeType(struct soap*, const char *, int, struct ns1__AttributeType *const*, const char *);
    SOAP_FMAC3 struct ns1__AttributeType ** SOAP_FMAC4 soap_in_PointerTons1__AttributeType(struct soap*, const char*, struct ns1__AttributeType **, const char*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__AttributeType(struct soap*, struct ns1__AttributeType *const*, const char*, const char*);

#ifndef soap_write_PointerTons1__AttributeType
#define soap_write_PointerTons1__AttributeType(soap, data) ( soap_begin(soap), soap_serialize_PointerTons1__AttributeType(soap, data), soap_begin_send(soap) || soap_put_PointerTons1__AttributeType(soap, data, "ns1:AttributeType", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 struct ns1__AttributeType ** SOAP_FMAC4 soap_get_PointerTons1__AttributeType(struct soap*, struct ns1__AttributeType **, const char*, const char*);

#ifndef soap_read_PointerTons1__AttributeType
#define soap_read_PointerTons1__AttributeType(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__AttributeType(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerToint
#define SOAP_TYPE_PointerToint (12)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToint(struct soap*, int *const*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToint(struct soap*, const char *, int, int *const*, const char *);
    SOAP_FMAC3 int ** SOAP_FMAC4 soap_in_PointerToint(struct soap*, const char*, int **, const char*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToint(struct soap*, int *const*, const char*, const char*);

#ifndef soap_write_PointerToint
#define soap_write_PointerToint(soap, data) ( soap_begin(soap), soap_serialize_PointerToint(soap, data), soap_begin_send(soap) || soap_put_PointerToint(soap, data, "int", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 int ** SOAP_FMAC4 soap_get_PointerToint(struct soap*, int **, const char*, const char*);

#ifndef soap_read_PointerToint
#define soap_read_PointerToint(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToint(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerToxsd__boolean
#define SOAP_TYPE_PointerToxsd__boolean (11)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToxsd__boolean(struct soap*, enum xsd__boolean *const*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToxsd__boolean(struct soap*, const char *, int, enum xsd__boolean *const*, const char *);
    SOAP_FMAC3 enum xsd__boolean ** SOAP_FMAC4 soap_in_PointerToxsd__boolean(struct soap*, const char*, enum xsd__boolean **, const char*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToxsd__boolean(struct soap*, enum xsd__boolean *const*, const char*, const char*);

#ifndef soap_write_PointerToxsd__boolean
#define soap_write_PointerToxsd__boolean(soap, data) ( soap_begin(soap), soap_serialize_PointerToxsd__boolean(soap, data), soap_begin_send(soap) || soap_put_PointerToxsd__boolean(soap, data, "xsd:boolean", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 enum xsd__boolean ** SOAP_FMAC4 soap_get_PointerToxsd__boolean(struct soap*, enum xsd__boolean **, const char*, const char*);

#ifndef soap_read_PointerToxsd__boolean
#define soap_read_PointerToxsd__boolean(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToxsd__boolean(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTostring
#define SOAP_TYPE_PointerTostring (9)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostring(struct soap*, char **const*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostring(struct soap*, const char *, int, char **const*, const char *);
    SOAP_FMAC3 char *** SOAP_FMAC4 soap_in_PointerTostring(struct soap*, const char*, char ***, const char*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostring(struct soap*, char **const*, const char*, const char*);

#ifndef soap_write_PointerTostring
#define soap_write_PointerTostring(soap, data) ( soap_begin(soap), soap_serialize_PointerTostring(soap, data), soap_begin_send(soap) || soap_put_PointerTostring(soap, data, "byte", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 char *** SOAP_FMAC4 soap_get_PointerTostring(struct soap*, char ***, const char*, const char*);

#ifndef soap_read_PointerTostring
#define soap_read_PointerTostring(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTostring(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)

    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
    SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_begin(soap), soap_serialize__QName(soap, data), soap_begin_send(soap) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
    SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
    SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
    SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);
    SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_begin(soap), soap_serialize_string(soap, data), soap_begin_send(soap) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap), soap->error )
#endif

    SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifdef __cplusplus
}
#endif

#endif

/* End of soapH.h */
