<?php Yaf_Loader::import(PATH_APP . '/modules/Admin/views/head.phtml'); ?>

      
      <div class="navbar content-navbar navbar-default navbar-xs" data-toggle="breakpoint"
        data-class-xs="navbar content-navbar navbar-inverse navbar-xs"
        data-class-sm="navbar content-navbar navbar-default navbar-xs">
        <div class="navbar-header">
          
          
<button class="navbar-toggle pull-left" data-toggle="class" data-target="#body-content" data-class-name="show_menu">
  <i class="icon-list"></i>
</button>

  <a title="添加小组件" href="/xadmin/userwidget/add/?user=1&amp;page_id=home&amp;_redirect=/" class="navbar-toggle pull-right">
    <i class="icon-plus icon-white"></i></a>



          <a class="navbar-brand" data-toggle="collapse" data-target="#top-nav .navbar-collapse">
            
  <i class="icon-home" style='position:relative;top:4px;'></i> 当前位置：后台首页

          </a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            
          </ul>
        </div>
      </div>
          <div class="dashboard row">

        <div class="col-sm-4 column">

            <div class="panel panel-default widget addform form-horizontal short_label fieldset" id="88">
                <div class="panel-heading"><h3 class="panel-title">
                        修改密码
                    </h3></div>
                <div class="panel-body " >

                    <form action='/admin/user/dealChangePassword/' method='post'>
                        <table class="table table-hover table-striped">
                            <tr>
                                <td></td>
                                <td>
                                    <input class="form-control" name="oldpassword" type="password" id="inputOldPassword" placeholder="旧密码">
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td>
                                    <input class="form-control" name="newpassword" type="password" id="inputNewPassword" placeholder="输入新密码">
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td>
                                     <input class="form-control" name="confirmpassword" type="password" id="inputConfirmPassword" placeholder="确认新密码">
                                </td>
                            </tr>
                            <tr>
                                <td>&nbsp;</td>
                                <td>
                                    <input type="submit" value="保存变更" class='btn btn-primary' />
                                </td>

                            </tr>
                        </table>
                    </form>

                </div>
            </div>
        </div>
    </div>

 <!--footer-->
<?php Yaf_Loader::import(PATH_APP . '/modules/Admin/views/foot.phtml'); ?>