<!DOCTYPE html>
<html lang="en" >
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0">
  
  <meta name="description" content="">
  <meta name="author" content="">
  
  <meta name="robots" content="NONE,NOARCHIVE" />
  <title>忘记密码 - 联创CMS</title>
  <link rel='stylesheet' type='text/css' href='/static/admin/css/customer.css' />
  <link href="/static/admin/css/bootstrap.css" type="text/css" media="screen" rel="stylesheet" />
  
  <link rel="stylesheet" type="text/css" id="site-theme" href="/static/admin/css/bootstrap-xadmin.css" />

  <link href="/static/admin/css/font-awesome.css" type="text/css" media="screen" rel="stylesheet" />
<link href="/static/admin/css/xadmin.main.css" type="text/css" media="screen" rel="stylesheet" />
<link href="/static/admin/css/xadmin.plugins.css" type="text/css" media="screen" rel="stylesheet" />
<link href="/static/admin/css/xadmin.responsive.css" type="text/css" media="screen" rel="stylesheet" />
 <link rel='stylesheet' type='text/css' href='/static/admin/css/customer.css' />
  
<style type="text/css">
  #panel-login {
    max-width: 350px;
  }
  #panel-login .controls{
    padding: 0px 15px 15px !important;
  }
  #panel-login .alert-block{
    padding: 0px;
  }
  #panel-login .alert-block ul{
    margin: 10px 15px;
    padding-left: 0px;
  }
  #panel-login .alert-block ul li{
    list-style-type: none;
  }
</style>
<style type="text/css">
  .form-signin {
      max-width: 320px;
    -webkit-border-radius: 10px;
       -moz-border-radius: 10px;
            border-radius: 10px;
    -webkit-box-shadow: 0 0px 40px rgba(0,0,0,.2);
       -moz-box-shadow: 0 0px 40px rgba(0,0,0,.2);
            box-shadow: 0 0px 40px rgba(0,0,0,.2);
  }
</style>
  <script type="text/javascript" src="/static/admin/js/jquery.js"></script>
  
  <script type="text/javascript">
    window.__admin_media_prefix__ = "/static/xadmin/";
    window.__admin_path_prefix__ = "/";
  </script>
  <script type="text/javascript" src="js/.io/jsi18n/"></script>
  
  
</head>
<body class="login">
  
<div class="container">
  <form action="/admin/user/dealForgetPassword/" method="post" id="login-form">
    <div class="panel panel-default panel-single" id="panel-login">
    <input type='hidden' name='csrfmiddlewaretoken' value='AzcgCNTvWtn3G6aFTA3svrnkyW4F9twm' />
    
      <div class="panel-heading">
        
<h2 class="form-signin-heading"><i style='position:relative;top:8px;' class="icon-comment"></i> 联创CMS</h2>
      </div>
      <div class="panel-body">
      
      
      
      <div id="div_id_username" class="row">
        <div class="controls clearfix">
        <div class="input-group input-group-lg">
          <span class="input-group-addon"><i class="icon-user icon-fixed-width"></i></span>
          <input class="form-control input-lg" id="id_username" maxlength="254" name="username" type="text" placeholder="用户名">
        </div>
        
        </div>
      </div>
      <div id="div_id_question" class="row">
        <div class="controls clearfix">
        <div class="input-group input-group-lg">
          <span class="input-group-addon"><i class="icon-lock icon-fixed-width"></i></span>
          <select class="form-control" name="question">
            <?php
                foreach($questionlist as $v){
                    echo "<option value=".$v['qid'].">".$v['content']."</option>";
                }
            ?>
            
          </select>
        </div>
        
        </div>
      </div>

      <div id="div_id_answer" class="row">
        <div class="controls clearfix">
        <div class="input-group input-group-lg">
          <span class="input-group-addon"><i class="icon-lock icon-fixed-width"></i></span>
            <input class="form-control input-lg" id="id_username" maxlength="254" name="answer" type="text" placeholder="答案">
        </div>
        
        </div>
      </div>

      <input type="hidden" name="this_is_the_login_form" value="1" />
      <input type="hidden" name="next" value="/" />
      <button class="btn btn-lg btn-primary btn-block" type="submit">找回密码</button>
      <p style='margin-top:8px;text-align:center;'><a href='/admin/user/login/'>返回登录</a></p>
      </div>
    
    </div>
  </form>
</div> <!-- /container -->
<script type="text/javascript">
document.getElementById('id_username').focus()
</script>
  <script type="text/javascript" src="/static/admin/js/jquery.ui.core.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.ui.widget.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.ui.mouse.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.ui.sortable.js"></script>
<script type="text/javascript" src="/static/admin/js/bootstrap.js"></script>
<script type="text/javascript" src="/static/admin/js/xadmin.main.js"></script>
<script type="text/javascript" src="/static/admin/js/xadmin.responsive.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.ui.effect.js"></script>
<script type="text/javascript" src="/static/admin/js/xadmin.plugin.themes.js"></script> 
</body>
</html>
