
<!DOCTYPE html>
<html lang="zh-cn" >
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0">
  
  <meta name="description" content="">
  <meta name="author" content="">
  
  <meta name="robots" content="NONE,NOARCHIVE" />
  <title></title>
  
  <link href="/static/admin/css/bootstrap.css" type="text/css" media="screen" rel="stylesheet" />
  
  <link rel="stylesheet" type="text/css" id="site-theme" href="/static/admin/css/bootstrap-xadmin.css" />
  
  <link href="/static/admin/css/font-awesome.css" type="text/css" media="screen" rel="stylesheet" />
<link href="/static/admin/css/xadmin.main.css" type="text/css" media="screen" rel="stylesheet" />
<link href="/static/admin/css/xadmin.plugins.css" type="text/css" media="screen" rel="stylesheet" />
<link href="/static/admin/css/xadmin.responsive.css" type="text/css" media="screen" rel="stylesheet" />
  
  
<style type="text/css">
  .form-signout h2, .form-signout p{margin-bottom: 15px;}
</style>

  <script type="text/javascript" src="/static/admin/js/jquery.js"></script>
  
  <script type="text/javascript">
    window.__admin_media_prefix__ = "/static/xadmin/";
    window.__admin_path_prefix__ = "/";
  </script>
  
  
</head>
<body class="">
  
<div class="container">

  <div class="panel panel-default form-signout panel-single" style="max-width: 300px;">
    <div class="panel-body">
      <h2 class="text-success">成功退出</h2>
      <p>感谢您使用联创CMS</p>
      <p class="btn-group">
        <a onclick="javascript:window.opener=null;window.open(location,'_self');window.close();" class="btn btn-primary">关闭窗口</a>
        <a href="/admin/user/login/" class="btn btn-default">重新登录</a>
      </p>
    </div>
  </div>

</div> <!-- /container -->


  <script type="text/javascript" src="/static/admin/js/jquery.ui.core.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.ui.widget.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.ui.mouse.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.ui.sortable.js"></script>
<script type="text/javascript" src="/static/admin/js/bootstrap.js"></script>
<script type="text/javascript" src="/static/admin/js/xadmin.main.js"></script>
<script type="text/javascript" src="/static/admin/js/xadmin.responsive.js"></script>
  <script type="text/javascript" src="/static/admin/js/jquery.ui.effect.js"></script>
<script type="text/javascript" src="/static/admin/js/xadmin.plugin.themes.js"></script>
  
  
</body>
</html>
