<!-- Header -->
<?php Yaf_Loader::import(PATH_APP . '/modules/Admin/views/head.phtml'); ?>


    <div class="navbar content-navbar navbar-default navbar-xs" data-toggle="breakpoint"
         data-class-xs="navbar content-navbar navbar-inverse navbar-xs"
         data-class-sm="navbar content-navbar navbar-default navbar-xs">
        <div class="navbar-header">


            <button class="navbar-toggle pull-left" data-toggle="class" data-target="#body-content" data-class-name="show_menu">
                <i class="icon-list"></i>
            </button>

            <a title="添加小组件" href="/xadmin/userwidget/add/?user=1&amp;page_id=home&amp;_redirect=/" class="navbar-toggle pull-right">
                <i class="icon-plus icon-white"></i></a>



            <a class="navbar-brand" data-toggle="collapse" data-target="#top-nav .navbar-collapse">

                <i class="icon-home" style='position:relative;top:4px;'></i> 当前位置：个人面板

            </a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">

            </ul>
        </div>
    </div>
    <div class="dashboard row">

        <div class="col-sm-4 column">

            <div class="panel panel-default widget addform form-horizontal short_label fieldset" id="88">
                <div class="panel-heading"><h3 class="panel-title">
                        设置密保 <small>密保用于找回密码</small>
                    </h3></div>
                <div class="panel-body " >

                    <form action='/admin/user/dealAddProtect' method='post'>
                        <table class="table table-hover table-striped">
                            <tr>
                                <td>问题</td>
                                <td>
                                    <select class="form-control" name="question">
                                    <option value=0>--请选择--</option>
                                   <?php
                                        foreach((array)$question_list as $key => $value){
                                            ?>

                                                <?php
                                                    if((int)$user_profile['question'] == $value['qid']){

                                                        ?>
                                                        <option selected="selected" value="<?php echo $value['qid'];?>"><?php echo $value['content'];?></option>
                                                        <?php
                                                    }else{

                                                        ?>
                                                        <option value="<?php echo $value['qid'];?>"><?php echo $value['content'];?></option>
                                                        <?php

                                                    }
                                                ?>

                                            <?php
                                        }
                                   ?>
                                    </select>
                                </td>
                            </tr>
                            <tr>
                                <td>答案</td>
                                <td>
                                    <input value="<?php echo $user_profile['answer'];?>" type="text" class="form-control" name="answer" />
                                </td>
                            </tr>
                            <tr>
                                <td>&nbsp;</td>
                                <td>
                                    <input type="submit" value="立即提交" class='btn btn-primary' />
                                </td>

                            </tr>
                        </table>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
<input type='hidden' id='_portal_key' value='dashboard:home:pos' />


<!--footer-->
<?php Yaf_Loader::import(PATH_APP . '/modules/Admin/views/foot.phtml'); ?>
