<?php Yaf_Loader::import(PATH_APP . '/modules/Admin/views/head.phtml'); ?>
<div class="navbar content-navbar navbar-default navbar-xs" data-toggle="breakpoint"
     data-class-xs="navbar content-navbar navbar-inverse navbar-xs"
     data-class-sm="navbar content-navbar navbar-default navbar-xs">
    <div class="navbar-header">
        <a class="navbar-brand" data-toggle="collapse" data-target="#top-nav .navbar-collapse">
            <i class="icon-home" style='position:relative;top:4px;'></i> 当前位置：专题数据管理
        </a>
    </div>
    <div class="navbar-collapse collapse">

        <div class="navbar-btn navbar-right hide-xs">
            <a title="返回列表" href="/admin/page/create" class="btn btn-primary">
                <i class="icon-plus icon-white"></i> <span>返回列表</span></a>
        </div>
    </div>
</div>
<div class="dashboard row">
    <div class="col-sm-12 column">
        <!--数据列表-->
        <div class="panel panel-default widget addform form-horizontal short_label fieldset" id="88">
            <div class="panel-heading"><i class='icon icon-chevron-up chevron'></i><h3 class="panel-title">常用数据列表</h3></div>
            <div class="panel-body results" >
               <form action='/admin/topic/showdata?tid=<?=$data['tid']?>' enctype="multipart/form-data" method="post">
                <table class="table table-hover table-striped">
                    <tr>
                        <th width="2%" scope="col" class="action-checkbox-column"><input type="checkbox" id="action-toggle" /></th>
                       
                        <th width="20%">标题</th>
                        <th width="20%">path</th>
                        <th width="20%">数量</th>
                        <th width="20%">状态</th>
                        <th width="18%">操作</th>
                    </tr>
                    <?php
                    if ($data['base']) {
                        foreach ($data['base'] as $key => $value) {
                            ?>                                   
                            <tr>
                                <td  class="action-checkbox"><input class="action-select" name="_selected_action" type="checkbox" value="6" /></td>
                                <td><?=$data['title'][$key]?></td>
                                <td><?=$key?></td>
                                <td><input type="text" name="show_data[base][<?=$key?>][num]" value="<?=$value['num']?>"></td>
                                <td>
                                    <select name="show_data[base][<?=$key?>][status]">
                                        <option value="1" <?=$value['status'] == 1 ? 'selected="true"' : '' ?>>启用</option>
                                        <option value="0" <?=$value['status'] == 0 ? 'selected="true"' : '' ?>>禁止</option>
                                    </select>
                                </td>
                                <td>
                                    <?=$value['status'] ? '<a href="">禁止</a>' : '<a href="">启用</a>';?>
                                </td>
                            </tr>
                            <?php
                        }
                    }
                    ?>
                    </table>
                    <table class="table table-hover table-striped" id="table2">
                        <tr>
                            <th width="2%" scope="col" class="action-checkbox-column">id</th>
                           
                            <th width="20%">标题</th>
                            <th width="20%">path</th>
                            <th width="20%">子类</th>
                            <th width="20%">数量</th>
                            <th width="18%">操作</th>
                        </tr>
                        <?php
                            $i = 0;
                            if(isset($data['data'])){
                                
                                foreach($data['data'] as $key=>$value){
                        ?>

                        <tr id="data<?=$i?>">
                            <td ><?=$i?></td>
                            <td><input name="show_data[data][<?=$i?>][title]" type="text" value="<?=$value['title']?>"></td>
                            <td><input name="show_data[data][<?=$i?>][path]" type="text" value="<?=$value['path']?>"></td>
                            <td>
                                <select name="show_data[data][<?=$i?>][sid]" id="selectdata<?=$i?>">
                                <?php foreach($data['list'] as $k=>$v){ ?>
                                    <option pathname="<?=$v['title']?>" path="<?=$v['path']?>" value="<?=$v['id']?>" <?=$v['id'] == $value['sid'] ? 'selected="true"':''?>><?=$v['title']?></option>
                                <?php } ?>
                                </select>
                            </td>
                            <td><input name="show_data[data][<?=$i?>][num]" type="text" value="<?=$value['num']?>"></td>
                            <td>
                                <a href="javascript:void(0);" onclick="delRow(this)">删除</a>
                                <a href="javascript:void(0);" onclick="appendRow(this)">添加</a>
                            </td>
                        </tr>

                        <?php $i++; }}else{ ?>
                        <tr id="data0">
                            <td>0</td>
                            <td><input type="text" name="show_data[data][0][title]"></td>
                            <td><input type="text" name="show_data[data][0][path]"></td>
                            <td>
                                <select name="show_data[data][0][sid]">
                                <?php foreach($data['list'] as $k=>$v){ ?>
                                    <option pathname="<?=$v['title']?>" path="<?=$v['path']?>" value="<?=$v['id']?>" <?=$v['id'] == $value['sid'] ? 'selected="true"':''?>><?=$v['title']?></option>
                                <?php } ?>
                                </select>
                            </td>
                            <td><input type="text" name="show_data[data][0][num]"></td>
                            <td>
                                <a onclick="delRow(this)" href="javascript:void(0);">删除</a>
                                <a onclick="appendRow(this)" href="javascript:void(0);">添加</a>
                            </td>
                        </tr>
                        <?php } ?>
                    <tr>
                        <td style="width:100px;">&nbsp;</td>
                        <td>
                            <input type="submit" name="dosubmit" value="保存" class="btn btn-primary">
                        </td>
                    </tr>
                </table>
                </form>
            </div>
        </div>
    </div>
   
    <input type='hidden' id='_portal_key' value='dashboard:home:pos' />
    <script>
        //添加行  
        function appendRow(){
            var num = $("#table2 tr").length - 2;
            //var str = "<input name='test' value='1'>";
            //$("#table2 tr:last").after(str);
            var tr = $("#data0").clone(true);//克隆一行
            tr.attr({"id":"data"+num,"form":"form"+num});
            tr.find("td:first").html(num);
            tr.find("td:eq(1)").html('<input type="text" name="show_data[data]['+num+'][title]">');
            tr.find("td:eq(2)").html('<input type="text" name="show_data[data]['+num+'][path]">');
            tr.find("td:eq(3) select").attr({"name":"show_data[data]["+num+"][sid]","id":"selectdata"+num});
            tr.find("td:eq(4)").html('<input type="text" name="show_data[data]['+num+'][num]">');
            tr.insertBefore("#table2 tr:last");//把这行加到表格的倒数第二行，表格添加完毕
        } 

        //删除相对应的行  
        function delRow(rows){  
            $(rows).parent("td").parent("tr").remove();  
        }

        $(function(){
          $("select").change(function(){
            var path = $(this).find("option:selected").attr("path");  //获取Select选择的Text 
            var pathname = $(this).find("option:selected").attr("pathname");
            var num = $("#table2 tr").length - 3;
            var tr = $("#data"+num);
            tr.find("td:eq(1)").html('<input type="text" name="show_data[data]['+num+'][title]" value="'+pathname+'">');
            tr.find("td:eq(2)").html('<input type="text" name="show_data[data]['+num+'][path]" value="'+path+'">');
          });
        })

    </script>
    <?php Yaf_Loader::import(PATH_APP . '/modules/Admin/views/foot.phtml'); ?>