/* soapClient.c
   Generated by gSOAP 2.8.14 from demo.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.8.14 2013-07-02 10:03:49 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getAccountInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getAccountInfoRequest *ns1__getAccountInfoRequest, struct _ns1__getAccountInfoResponse *ns1__getAccountInfoResponse)
{	struct __ns1__getAccountInfo soap_tmp___ns1__getAccountInfo;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://api.baidu.com/sem/sms/v2/AccountService";
	if (soap_action == NULL)
		soap_action = "https://api.baidu.com/sem/sms/v2/AccountService/getAccountInfo";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getAccountInfo.ns1__getAccountInfoRequest = ns1__getAccountInfoRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getAccountInfo(soap, &soap_tmp___ns1__getAccountInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getAccountInfo(soap, &soap_tmp___ns1__getAccountInfo, "-ns1:getAccountInfo", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getAccountInfo(soap, &soap_tmp___ns1__getAccountInfo, "-ns1:getAccountInfo", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getAccountInfoResponse)
		return soap_closesock(soap);
	soap_default__ns1__getAccountInfoResponse(soap, ns1__getAccountInfoResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__getAccountInfoResponse(soap, ns1__getAccountInfoResponse, "ns1:getAccountInfoResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__updateAccountInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__updateAccountInfoRequest *ns1__updateAccountInfoRequest, struct _ns1__updateAccountInfoResponse *ns1__updateAccountInfoResponse)
{	struct __ns1__updateAccountInfo soap_tmp___ns1__updateAccountInfo;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://api.baidu.com/sem/sms/v2/AccountService";
	if (soap_action == NULL)
		soap_action = "https://api.baidu.com/sem/sms/v2/AccountService/updateAccountInfo";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__updateAccountInfo.ns1__updateAccountInfoRequest = ns1__updateAccountInfoRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__updateAccountInfo(soap, &soap_tmp___ns1__updateAccountInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__updateAccountInfo(soap, &soap_tmp___ns1__updateAccountInfo, "-ns1:updateAccountInfo", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__updateAccountInfo(soap, &soap_tmp___ns1__updateAccountInfo, "-ns1:updateAccountInfo", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__updateAccountInfoResponse)
		return soap_closesock(soap);
	soap_default__ns1__updateAccountInfoResponse(soap, ns1__updateAccountInfoResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__updateAccountInfoResponse(soap, ns1__updateAccountInfoResponse, "ns1:updateAccountInfoResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getChangedCampaignId(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getChangedCampaignIdRequest *ns1__getChangedCampaignIdRequest, struct _ns1__getChangedCampaignIdResponse *ns1__getChangedCampaignIdResponse)
{	struct __ns1__getChangedCampaignId soap_tmp___ns1__getChangedCampaignId;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://api.baidu.com/sem/sms/v2/AccountService";
	if (soap_action == NULL)
		soap_action = "https://api.baidu.com/sem/sms/v2/AccountService/getChangedCampaignId";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getChangedCampaignId.ns1__getChangedCampaignIdRequest = ns1__getChangedCampaignIdRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getChangedCampaignId(soap, &soap_tmp___ns1__getChangedCampaignId);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getChangedCampaignId(soap, &soap_tmp___ns1__getChangedCampaignId, "-ns1:getChangedCampaignId", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getChangedCampaignId(soap, &soap_tmp___ns1__getChangedCampaignId, "-ns1:getChangedCampaignId", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getChangedCampaignIdResponse)
		return soap_closesock(soap);
	soap_default__ns1__getChangedCampaignIdResponse(soap, ns1__getChangedCampaignIdResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__getChangedCampaignIdResponse(soap, ns1__getChangedCampaignIdResponse, "ns1:getChangedCampaignIdResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getChangedAdgroupId(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getChangedAdgroupIdRequest *ns1__getChangedAdgroupIdRequest, struct _ns1__getChangedAdgroupIdResponse *ns1__getChangedAdgroupIdResponse)
{	struct __ns1__getChangedAdgroupId soap_tmp___ns1__getChangedAdgroupId;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://api.baidu.com/sem/sms/v2/AccountService";
	if (soap_action == NULL)
		soap_action = "https://api.baidu.com/sem/sms/v2/AccountService/getChangedAdgroupId";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getChangedAdgroupId.ns1__getChangedAdgroupIdRequest = ns1__getChangedAdgroupIdRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getChangedAdgroupId(soap, &soap_tmp___ns1__getChangedAdgroupId);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getChangedAdgroupId(soap, &soap_tmp___ns1__getChangedAdgroupId, "-ns1:getChangedAdgroupId", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getChangedAdgroupId(soap, &soap_tmp___ns1__getChangedAdgroupId, "-ns1:getChangedAdgroupId", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getChangedAdgroupIdResponse)
		return soap_closesock(soap);
	soap_default__ns1__getChangedAdgroupIdResponse(soap, ns1__getChangedAdgroupIdResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__getChangedAdgroupIdResponse(soap, ns1__getChangedAdgroupIdResponse, "ns1:getChangedAdgroupIdResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getChangedItemId(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getChangedItemIdRequest *ns1__getChangedItemIdRequest, struct _ns1__getChangedItemIdResponse *ns1__getChangedItemIdResponse)
{	struct __ns1__getChangedItemId soap_tmp___ns1__getChangedItemId;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://api.baidu.com/sem/sms/v2/AccountService";
	if (soap_action == NULL)
		soap_action = "https://api.baidu.com/sem/sms/v2/AccountService/getChangedItemId";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getChangedItemId.ns1__getChangedItemIdRequest = ns1__getChangedItemIdRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getChangedItemId(soap, &soap_tmp___ns1__getChangedItemId);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getChangedItemId(soap, &soap_tmp___ns1__getChangedItemId, "-ns1:getChangedItemId", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getChangedItemId(soap, &soap_tmp___ns1__getChangedItemId, "-ns1:getChangedItemId", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getChangedItemIdResponse)
		return soap_closesock(soap);
	soap_default__ns1__getChangedItemIdResponse(soap, ns1__getChangedItemIdResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__getChangedItemIdResponse(soap, ns1__getChangedItemIdResponse, "ns1:getChangedItemIdResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getChangedId(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getChangedIdRequest *ns1__getChangedIdRequest, struct _ns1__getChangedIdResponse *ns1__getChangedIdResponse)
{	struct __ns1__getChangedId soap_tmp___ns1__getChangedId;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://api.baidu.com/sem/sms/v2/AccountService";
	if (soap_action == NULL)
		soap_action = "https://api.baidu.com/sem/sms/v2/AccountService/getChangedId";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getChangedId.ns1__getChangedIdRequest = ns1__getChangedIdRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getChangedId(soap, &soap_tmp___ns1__getChangedId);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getChangedId(soap, &soap_tmp___ns1__getChangedId, "-ns1:getChangedId", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getChangedId(soap, &soap_tmp___ns1__getChangedId, "-ns1:getChangedId", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getChangedIdResponse)
		return soap_closesock(soap);
	soap_default__ns1__getChangedIdResponse(soap, ns1__getChangedIdResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__getChangedIdResponse(soap, ns1__getChangedIdResponse, "ns1:getChangedIdResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getAllObjects(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getAllObjectsRequest *ns1__getAllObjectsRequest, struct _ns1__getAllObjectsResponse *ns1__getAllObjectsResponse)
{	struct __ns1__getAllObjects soap_tmp___ns1__getAllObjects;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://api.baidu.com/sem/sms/v2/AccountService";
	if (soap_action == NULL)
		soap_action = "https://api.baidu.com/sem/sms/v2/AccountService/getAllObjects";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getAllObjects.ns1__getAllObjectsRequest = ns1__getAllObjectsRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getAllObjects(soap, &soap_tmp___ns1__getAllObjects);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getAllObjects(soap, &soap_tmp___ns1__getAllObjects, "-ns1:getAllObjects", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getAllObjects(soap, &soap_tmp___ns1__getAllObjects, "-ns1:getAllObjects", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getAllObjectsResponse)
		return soap_closesock(soap);
	soap_default__ns1__getAllObjectsResponse(soap, ns1__getAllObjectsResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__getAllObjectsResponse(soap, ns1__getAllObjectsResponse, "ns1:getAllObjectsResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getChangedScale(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getChangedScaleRequest *ns1__getChangedScaleRequest, struct _ns1__getChangedScaleResponse *ns1__getChangedScaleResponse)
{	struct __ns1__getChangedScale soap_tmp___ns1__getChangedScale;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://api.baidu.com/sem/sms/v2/AccountService";
	if (soap_action == NULL)
		soap_action = "https://api.baidu.com/sem/sms/v2/AccountService/getChangedScale";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getChangedScale.ns1__getChangedScaleRequest = ns1__getChangedScaleRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getChangedScale(soap, &soap_tmp___ns1__getChangedScale);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getChangedScale(soap, &soap_tmp___ns1__getChangedScale, "-ns1:getChangedScale", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getChangedScale(soap, &soap_tmp___ns1__getChangedScale, "-ns1:getChangedScale", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getChangedScaleResponse)
		return soap_closesock(soap);
	soap_default__ns1__getChangedScaleResponse(soap, ns1__getChangedScaleResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__getChangedScaleResponse(soap, ns1__getChangedScaleResponse, "ns1:getChangedScaleResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getSelectedObjects(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getSelectedObjectsRequest *ns1__getSelectedObjectsRequest, struct _ns1__getSelectedObjectsResponse *ns1__getSelectedObjectsResponse)
{	struct __ns1__getSelectedObjects soap_tmp___ns1__getSelectedObjects;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://api.baidu.com/sem/sms/v2/AccountService";
	if (soap_action == NULL)
		soap_action = "https://api.baidu.com/sem/sms/v2/AccountService/getSelectedObjects";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getSelectedObjects.ns1__getSelectedObjectsRequest = ns1__getSelectedObjectsRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getSelectedObjects(soap, &soap_tmp___ns1__getSelectedObjects);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getSelectedObjects(soap, &soap_tmp___ns1__getSelectedObjects, "-ns1:getSelectedObjects", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getSelectedObjects(soap, &soap_tmp___ns1__getSelectedObjects, "-ns1:getSelectedObjects", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getSelectedObjectsResponse)
		return soap_closesock(soap);
	soap_default__ns1__getSelectedObjectsResponse(soap, ns1__getSelectedObjectsResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__getSelectedObjectsResponse(soap, ns1__getSelectedObjectsResponse, "ns1:getSelectedObjectsResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getFileState(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getFileStateRequest *ns1__getFileStateRequest, struct _ns1__getFileStateResponse *ns1__getFileStateResponse)
{	struct __ns1__getFileState soap_tmp___ns1__getFileState;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://api.baidu.com/sem/sms/v2/AccountService";
	if (soap_action == NULL)
		soap_action = "https://api.baidu.com/sem/sms/v2/AccountService/getFileState";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getFileState.ns1__getFileStateRequest = ns1__getFileStateRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getFileState(soap, &soap_tmp___ns1__getFileState);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getFileState(soap, &soap_tmp___ns1__getFileState, "-ns1:getFileState", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getFileState(soap, &soap_tmp___ns1__getFileState, "-ns1:getFileState", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getFileStateResponse)
		return soap_closesock(soap);
	soap_default__ns1__getFileStateResponse(soap, ns1__getFileStateResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__getFileStateResponse(soap, ns1__getFileStateResponse, "ns1:getFileStateResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getAllObjectsPath(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getAllObjectsPathRequest *ns1__getAllObjectsPathRequest, struct _ns1__getAllObjectsPathResponse *ns1__getAllObjectsPathResponse)
{	struct __ns1__getAllObjectsPath soap_tmp___ns1__getAllObjectsPath;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://api.baidu.com/sem/sms/v2/AccountService";
	if (soap_action == NULL)
		soap_action = "https://api.baidu.com/sem/sms/v2/AccountService/getAllObjectsPath";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getAllObjectsPath.ns1__getAllObjectsPathRequest = ns1__getAllObjectsPathRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getAllObjectsPath(soap, &soap_tmp___ns1__getAllObjectsPath);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getAllObjectsPath(soap, &soap_tmp___ns1__getAllObjectsPath, "-ns1:getAllObjectsPath", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getAllObjectsPath(soap, &soap_tmp___ns1__getAllObjectsPath, "-ns1:getAllObjectsPath", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getAllObjectsPathResponse)
		return soap_closesock(soap);
	soap_default__ns1__getAllObjectsPathResponse(soap, ns1__getAllObjectsPathResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__getAllObjectsPathResponse(soap, ns1__getAllObjectsPathResponse, "ns1:getAllObjectsPathResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getSelectedObjectsPath(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getSelectedObjectsPathRequest *ns1__getSelectedObjectsPathRequest, struct _ns1__getSelectedObjectsPathResponse *ns1__getSelectedObjectsPathResponse)
{	struct __ns1__getSelectedObjectsPath soap_tmp___ns1__getSelectedObjectsPath;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://api.baidu.com/sem/sms/v2/AccountService";
	if (soap_action == NULL)
		soap_action = "https://api.baidu.com/sem/sms/v2/AccountService/getSelectedObjectsPath";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getSelectedObjectsPath.ns1__getSelectedObjectsPathRequest = ns1__getSelectedObjectsPathRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getSelectedObjectsPath(soap, &soap_tmp___ns1__getSelectedObjectsPath);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getSelectedObjectsPath(soap, &soap_tmp___ns1__getSelectedObjectsPath, "-ns1:getSelectedObjectsPath", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getSelectedObjectsPath(soap, &soap_tmp___ns1__getSelectedObjectsPath, "-ns1:getSelectedObjectsPath", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getSelectedObjectsPathResponse)
		return soap_closesock(soap);
	soap_default__ns1__getSelectedObjectsPathResponse(soap, ns1__getSelectedObjectsPathResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__getSelectedObjectsPathResponse(soap, ns1__getSelectedObjectsPathResponse, "ns1:getSelectedObjectsPathResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getAllChangedObjects(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getAllChangedObjectsRequest *ns1__getAllChangedObjectsRequest, struct _ns1__getAllChangedObjectsResponse *ns1__getAllChangedObjectsResponse)
{	struct __ns1__getAllChangedObjects soap_tmp___ns1__getAllChangedObjects;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://api.baidu.com/sem/sms/v2/AccountService";
	if (soap_action == NULL)
		soap_action = "https://api.baidu.com/sem/sms/v2/AccountService/getAllChangedObjects";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getAllChangedObjects.ns1__getAllChangedObjectsRequest = ns1__getAllChangedObjectsRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getAllChangedObjects(soap, &soap_tmp___ns1__getAllChangedObjects);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getAllChangedObjects(soap, &soap_tmp___ns1__getAllChangedObjects, "-ns1:getAllChangedObjects", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getAllChangedObjects(soap, &soap_tmp___ns1__getAllChangedObjects, "-ns1:getAllChangedObjects", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getAllChangedObjectsResponse)
		return soap_closesock(soap);
	soap_default__ns1__getAllChangedObjectsResponse(soap, ns1__getAllChangedObjectsResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__getAllChangedObjectsResponse(soap, ns1__getAllChangedObjectsResponse, "ns1:getAllChangedObjectsResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getAllChangedObjectsPath(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getAllChangedObjectsPathRequest *ns1__getAllChangedObjectsPathRequest, struct _ns1__getAllChangedObjectsPathResponse *ns1__getAllChangedObjectsPathResponse)
{	struct __ns1__getAllChangedObjectsPath soap_tmp___ns1__getAllChangedObjectsPath;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://api.baidu.com/sem/sms/v2/AccountService";
	if (soap_action == NULL)
		soap_action = "https://api.baidu.com/sem/sms/v2/AccountService/getAllChangedObjectsPath";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getAllChangedObjectsPath.ns1__getAllChangedObjectsPathRequest = ns1__getAllChangedObjectsPathRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getAllChangedObjectsPath(soap, &soap_tmp___ns1__getAllChangedObjectsPath);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getAllChangedObjectsPath(soap, &soap_tmp___ns1__getAllChangedObjectsPath, "-ns1:getAllChangedObjectsPath", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getAllChangedObjectsPath(soap, &soap_tmp___ns1__getAllChangedObjectsPath, "-ns1:getAllChangedObjectsPath", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getAllChangedObjectsPathResponse)
		return soap_closesock(soap);
	soap_default__ns1__getAllChangedObjectsPathResponse(soap, ns1__getAllChangedObjectsPathResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__getAllChangedObjectsPathResponse(soap, ns1__getAllChangedObjectsPathResponse, "ns1:getAllChangedObjectsPathResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__gettopNKeywordsData(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__gettopNKeywordsDataRequest *ns1__gettopNKeywordsDataRequest, struct _ns1__gettopNKeywordsDataResponse *ns1__gettopNKeywordsDataResponse)
{	struct __ns1__gettopNKeywordsData soap_tmp___ns1__gettopNKeywordsData;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://api.baidu.com/sem/sms/v2/AccountService";
	if (soap_action == NULL)
		soap_action = "https://api.baidu.com/sem/sms/v2/AccountService/gettopNKeywordsData";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__gettopNKeywordsData.ns1__gettopNKeywordsDataRequest = ns1__gettopNKeywordsDataRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__gettopNKeywordsData(soap, &soap_tmp___ns1__gettopNKeywordsData);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__gettopNKeywordsData(soap, &soap_tmp___ns1__gettopNKeywordsData, "-ns1:gettopNKeywordsData", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__gettopNKeywordsData(soap, &soap_tmp___ns1__gettopNKeywordsData, "-ns1:gettopNKeywordsData", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__gettopNKeywordsDataResponse)
		return soap_closesock(soap);
	soap_default__ns1__gettopNKeywordsDataResponse(soap, ns1__gettopNKeywordsDataResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__gettopNKeywordsDataResponse(soap, ns1__gettopNKeywordsDataResponse, "ns1:gettopNKeywordsDataResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__updateAccountBudget(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__updateAccountBudgetRequest *ns1__updateAccountBudgetRequest, struct _ns1__updateAccountBudgetResponse *ns1__updateAccountBudgetResponse)
{	struct __ns1__updateAccountBudget soap_tmp___ns1__updateAccountBudget;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://api.baidu.com/sem/sms/v2/AccountService";
	if (soap_action == NULL)
		soap_action = "https://api.baidu.com/sem/sms/v2/AccountService/updateAccountBudget";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__updateAccountBudget.ns1__updateAccountBudgetRequest = ns1__updateAccountBudgetRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__updateAccountBudget(soap, &soap_tmp___ns1__updateAccountBudget);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__updateAccountBudget(soap, &soap_tmp___ns1__updateAccountBudget, "-ns1:updateAccountBudget", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__updateAccountBudget(soap, &soap_tmp___ns1__updateAccountBudget, "-ns1:updateAccountBudget", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__updateAccountBudgetResponse)
		return soap_closesock(soap);
	soap_default__ns1__updateAccountBudgetResponse(soap, ns1__updateAccountBudgetResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__updateAccountBudgetResponse(soap, ns1__updateAccountBudgetResponse, "ns1:updateAccountBudgetResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getAccountBudget(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getAccountBudgetRequest *ns1__getAccountBudgetRequest, struct _ns1__getAccountBudgetResponse *ns1__getAccountBudgetResponse)
{	struct __ns1__getAccountBudget soap_tmp___ns1__getAccountBudget;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://api.baidu.com/sem/sms/v2/AccountService";
	if (soap_action == NULL)
		soap_action = "https://api.baidu.com/sem/sms/v2/AccountService/getAccountBudget";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getAccountBudget.ns1__getAccountBudgetRequest = ns1__getAccountBudgetRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getAccountBudget(soap, &soap_tmp___ns1__getAccountBudget);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getAccountBudget(soap, &soap_tmp___ns1__getAccountBudget, "-ns1:getAccountBudget", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getAccountBudget(soap, &soap_tmp___ns1__getAccountBudget, "-ns1:getAccountBudget", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getAccountBudgetResponse)
		return soap_closesock(soap);
	soap_default__ns1__getAccountBudgetResponse(soap, ns1__getAccountBudgetResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__getAccountBudgetResponse(soap, ns1__getAccountBudgetResponse, "ns1:getAccountBudgetResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getChangedNewCreativeId(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__GetChangedNewCreativeIdRequest *ns1__GetChangedNewCreativeIdRequest, struct _ns1__GetChangedNewCreativeIdResponse *ns1__GetChangedNewCreativeIdResponse)
{	struct __ns1__getChangedNewCreativeId soap_tmp___ns1__getChangedNewCreativeId;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://api.baidu.com/sem/sms/v2/AccountService";
	if (soap_action == NULL)
		soap_action = "https://api.baidu.com/sem/sms/v2/AccountService/getChangedNewCreativeId";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getChangedNewCreativeId.ns1__GetChangedNewCreativeIdRequest = ns1__GetChangedNewCreativeIdRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getChangedNewCreativeId(soap, &soap_tmp___ns1__getChangedNewCreativeId);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getChangedNewCreativeId(soap, &soap_tmp___ns1__getChangedNewCreativeId, "-ns1:getChangedNewCreativeId", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getChangedNewCreativeId(soap, &soap_tmp___ns1__getChangedNewCreativeId, "-ns1:getChangedNewCreativeId", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetChangedNewCreativeIdResponse)
		return soap_closesock(soap);
	soap_default__ns1__GetChangedNewCreativeIdResponse(soap, ns1__GetChangedNewCreativeIdResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__GetChangedNewCreativeIdResponse(soap, ns1__GetChangedNewCreativeIdResponse, "ns1:GetChangedNewCreativeIdResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.c */
