<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=gb2312" />
    <title><?= isset($title) ? $title.'-'.$config['sitename'] : $config['sitename'] ?></title>
    <base target="_blank">
    <meta name="keywords" content="<?= isset($keywords) ? misc::remove_nbsp($keywords) : '' ?>">
    <meta name="Description" content="<?= isset($description) ? misc::remove_nbsp($description) : '' ?>">
    <meta name="applicable-device" content="mobile"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0;" >
    <meta name="format-detection" content="telephone=no"/>
    <link rel="alternate" type="application/vnd.wap.xhtml+xml" media="handheld" href="target"/>
    <meta http-equiv="Cache-Control" content="no-transform" />

    <link href="<?= IMGURL ?>static/css/style1211.css" rel="stylesheet" type="text/css">
    <link href="<?= IMGURL ?>static/css/index1211.css" rel="stylesheet" type="text/css">
    <script src="<?= IMGURL ?>static/js/index0929.js" type="text/javascript"></script>
    <script src="<?= IMGURL ?>static/js/jquery-1.4.2.js" type="text/javascript"></script>
    <script src="<?= IMGURL ?>static/js/dhqh.js" type="text/javascript"></script>
    <script language="javascript" type="text/javascript"> 
var url1="http://mtip.ufstone.com/showswt.php?charset=gb2312&names=hangzhoupb";
document.writeln("<scr"+"ipt src=\"" + url1 + "\"  language=\"javascript\"   type=\"text/javascript\" charset=\"gb2312\" ><\/scr"+"ipt>");
</script>
</head>
<body>
<header>



    <div class="hd01">
        <a href="/<?=SITEDIR?>/" class="a1">首页</a>
        <div id="zk"><img src="<?= IMGURL ?>static/images/sjmh_003.jpg" width="22" height="17" />
            <div class="content none">
                <ul>
                    <li><a href="/hyzx/ssjf/">瘦身减肥</a></li>
                    <li><a href="/hyzx/tszl/">特色诊疗</a></li>
                    <li><a href="/hyzx/bzbj/">不知不觉</a></li>
                    <li><a href="/hyzx/cnly/">长年累月</a></li>
                    <li><a href="/hyzx/myqf/">明月清风</a></li>
                    <li><a href="/hyzx/yszd/">养生之道</a></li>
                    <li><a href="/hyzx/qsjt/">强身健体</a></li>
                    <li><a href="/hyzx/jgyx/">巾帼英雄</a></li>
                    <li><a href="/hyzx/pybm/">疲于奔命</a></li>
                    <li><a href="/hyzx/jkyl/">健康医疗</a></li>
                    <li><a href="/hyzx/jkbj/">健康保健</a></li>
                    <li><a href="/hyzx/jbzd/">疾病诊断</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="hd02"><a style="text-decoration:none;"><?=$title?>-<?=$config['sitename']?></a></div>

</header>

<article>
    <div class="path">您当前的位置：<a href="/<?= SITEDIR ?>/"><?=SITENAME?></a> ->&nbsp;
        <a href="/<?= SITEDIR ?>/<?= $category[$data['catid']]['catpath'] ?>/" HtmlUrl_href="/<?= SITEDIR ?>/<?= $category[$data['catid']]['catpath'] ?>/"><?=$category[$data['catid']]['catname']?></a> > 
        <?= $data['title'] ?>
    </div>
    <div class="banner" name="sj_banner"><a><img src="<?= IMGURL ?>static/images/111.jpg" width="100%" /></a></div>
    <!--推荐文章-->
    <p class="btp"><span>推荐阅读</span></p>
    <!--推荐文章end-->
    <div class="clear"></div>
    <div class="bdgg_b" name="yltoplb">
        <ul>
            <?php foreach ($data['tjyd'] as $k => $v) {
                ?>
                <li>
                    <div class="gg_bLeft"><a href="<?= BASEURL . SITEDIR . '/' . $category[$v['catid']]['catpath'] . '/' . $v['id'] ?>.html"><?= $v['title'] ?></a></div>
                    <div class="gg_bRight"><a href="javascript:openZoosUrl('chatwin')"><img src="<?= IMGURL ?>static/images/0f0005lthsdj6liqdkxpks.gif"></a><a name="sj_tel"><img src="<?= IMGURL ?>static/images/0f000fp5wgb4v1my-hends.gif"></a></div>
                </li>
            <?php } ?>
        </ul>
    </div>
    <div class="list1">
        <div class="cont">
            <h1><?=$title?></h1>
            <div class="cont_1">
                <span>来源： 佚名</span>
                <span>时间：<?= date('Y-m-d', $data['inputtime']) ?></span>
            </div>

            <?= isset($data['content']) ? misc::replacebr(stripslashes($data['content'])) : misc::replacebr(stripslashes($data['description'])); ?>
            <p class="pagebar"></p>

            <div class="cont_2">
                <a href="javascript:openZoosUrl('chatwin')" class="a11" name="sj_swt">在线咨询</a>
                <a href="javascript:openZoosUrl('chatwin')" class="a22" name="sj_swt">预约挂号</a>
            </div>
            <dl>


            </dl>
            <!--推荐文章-->

            <!--推荐文章end-->
        </div>
    </div>

    <p class="clr"></p>
    <!--热点文章-->
    <div class="banner" name="ylsjgg"><a><img src="<?= IMGURL ?>static/images/ggbt.jpg" width="97%" /></a></div>

    <p class="btp"><span>精华阅读</span></p>
    <div class="clear"></div>
    <div class="bdgg_b" name="ylbtlb">      
        <ul>
            <?php foreach ($data['jhyd'] as $v) { ?>
                <li>
                    <div class="gg_bLeft"><a href="<?= BASEURL . SITEDIR . '/' . $category[$v['catid']]['catpath'] . '/' . $v['id'] ?>.html"><?= $v['title'] ?></a></div>
                    <div class="gg_bRight"><a href="javascript:openZoosUrl('chatwin')"><img src="<?= IMGURL ?>static/images/0f0005lthsdj6liqdkxpks.gif"></a><a name="sj_tel"><img src="<?= IMGURL ?>static/images/0f000fp5wgb4v1my-hends.gif"></a></div>
                </li>
            <?php } ?>
        </ul>
    </div>

    <!--热点文章end-->
    <p class="clr"></p>
    <!--相关阅读-->

    <!--相关阅读end-->
    <p class="clr"></p>
    <!--最新文章-->

    <!--最新文章end-->
</article>

<!--手机底部-->
<footer>
    <p class="p4">
        <a name="sj_tel"><img src="<?= IMGURL ?>static/images/qq20140707153814_01.jpg"></a>
        <a href="javascript:openZoosUrl('chatwin')" name="sj_swt"><img src="<?= IMGURL ?>static/images/qq20140707153814_02.jpg"></a>
        <a href="javascript:openZoosUrl('chatwin')" name="sj_swt"><img src="<?= IMGURL ?>static/images/qq20140707153814_03.jpg"></a>
        <a href="javascript:openZoosUrl('chatwin')" name="sj_swt"><img src="<?= IMGURL ?>static/images/qq20140707153814_04.jpg"></a>
    </p>
</footer>
<!--手机底部end-->
<script language="javascript" src="http://js.ufstone.com/js/tanc.js"></script>
</body>
</html>