<?php Yaf_Loader::import(PATH_APP . '/modules/Admin/views/head.phtml'); ?>
<div class="navbar content-navbar navbar-default navbar-xs" data-toggle="breakpoint"
     data-class-xs="navbar content-navbar navbar-inverse navbar-xs"
     data-class-sm="navbar content-navbar navbar-default navbar-xs">
    <div class="navbar-header">
        <a class="navbar-brand" data-toggle="collapse" data-target="#top-nav .navbar-collapse">
            <i class="icon-home" style='position:relative;top:4px;'></i> 当前位置：文档管理
        </a>
    </div>
    <div class="navbar-collapse collapse">
        <div class="navbar-btn navbar-right hide-xs">
            <a title="新建文档" href="/admin/document/create" class="btn btn-primary">
                <i class="icon-plus icon-white"></i> <span>新建文档</span></a>
        </div>
    </div>
</div>


<div class="col-sm-12 column">

        <!--文档筛选-->
        <div class="panel panel-default widget addform form-horizontal short_label fieldset" id="88">
            <div class="panel-heading"><i class='icon icon-chevron-up chevron'></i><h3 class="panel-title">文档筛选</h3></div>
            <div class="panel-body " >
                <div style="padding:10px">
                    <form id ="search_news" action="" method="get">
                        <table class="table table-hover table-striped">
                            <tr>
                                <td id="catmod" style='width:200px;'>
                                    栏目：
                                    <select id="doc_cate" class="form-control" name="catid">
                                        <option value=''>请选择栏目</option>
                                        <?php
                                        if ($data['category']) {
                                            foreach ($data['category'] as $key => $category) {
                                                ?>
                                                <option  value='<?= $category['catid'] ?>'<?php if (isset($cond['catid']) && $cond['catid'] == $category['catid']) { ?> selected="selected"<?php } ?> >
                                                    <?= $category['catname'] ?>
                                                </option>
                                                <?php
                                            }
                                        }
                                        ?>
                                    </select>
                                </td>
                                <td style='width:200px;'>
                                    id：<input type='text' value="<?php echo isset($cond['id']) ? $cond['id'] : "" ?>" name="id" class = "text-field admintextinputwidget form-control" maxlength = "50" name = "name" type = "text">
                                </td>
                                <td style='width:200px;'>
                                    标题：<input type='text' value="<?php echo isset($cond['title']) ? $cond['title'] : "" ?>" name="title" class = "text-field admintextinputwidget form-control" maxlength = "50" name = "name" type = "text">
                                </td>
                                <td>
                                    <input name='dosubmit' style="position:relative;top:22px;" type="submit" value="筛选文档" class="btn btn-primary btn-sm" />
                                </td>
                            </tr>
                        </table>
                    </form>
                </div>
            </div>
        </div>

        <!--文档列表-->

        <div class="panel panel-default widget addform form-horizontal short_label fieldset" id="88">
            <div class="panel-heading"><i class='icon icon-chevron-up chevron'></i><h3 class="panel-title"> 文档列表</h3></div>
            <div class="panel-body results" >
                <form id="changelist-form" action="" method="post">
                    <table class="table table-hover table-striped">
                        <tr>
                            <th width="2%" scope="col" class="action-checkbox-column"><input type="checkbox" id="action-toggle" /></th>
                            <th width="10%">文档ID</th>
                            <th width="40%">标题</th>
                            <?php if(!$titlesearch){ ?>
                            <th width="5%">推荐 / 精华</th>
                            <th width="5%">状态</th>
                            <th width="15%">录入时间</th>
                            <?php } ?>
                            <th width="15%">操作</th>
                        </tr>

                        <?php
                        if ($data['data']) {
                            foreach ($data['data'] as $key => $new) {
                                ?>                                   
                                <tr>
                                    <td  class="action-checkbox"><input class="action-select" name="id[]" type="checkbox" value="<?= $new['id'] ?>"/></td>
                                    <td><?php echo $new['id']; ?></td>
                                    

                                    <td><a href="<?=misc::get_return_news_url($data['category'][$new['catid']]['catpath'],$new['inputtime'],$new['id']);?>" target="_blank"><?= mb_substr($new['title'], 0, 100, 'UTF-8') ?></a></td>

                                    <?php if(!$titlesearch){ ?>
                                    <td><?= $new['attribute'] == 1 ? '推荐' : ($new['attribute'] == 2 ? '精华' : ''); ?></td>
                                    <td><?=$new['status'] ? '√' : 'X'; ?></td>
                                    <td><?=TIME_TYPE == 1 ? date('Y-m-d H:i:s', $new['inputtime']) : $new['inputtime'];?></td>
                                    <?php } ?>
                                    <td>
                                        <a href='/admin/document/update?id=<?php echo $new['id'] ?>'>编辑</a>
                                        <a href='/admin/document/trash?id=<?php echo $new['id'] ?>&catid=<?= $new['catid'] ?>' onclick="javascript:return confirm('确定要删除吗？')">删除</a>
                                    </td>
                                </tr>
                                <?php
                            }
                        }
                        ?>
                    </table>
                </form>
            </div>
        </div>

        <!--            ---->
        <div class="form-actions well well-sm">
            <div class="btn-group clearfix dropup">
                <a class="dropdown-toggle btn btn-success" data-toggle="dropdown" href="#">
                    <i class="icon-wrench icon-white"></i> 
                    <span class="action-counter">选中了 <?= $data['perNum'] ?> 个中的 0 个</span>
                    <span class="all" style="display: none;">选中了 0 个</span>
                    <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                    <li>
                        <a onclick="$.do_action('/admin/document/batchRecommend?attribute=0');">
                            <i class="icon-book"></i> 普通
                        </a>
                        <a onclick="$.do_action('/admin/document/batchRecommend?attribute=1');">
                            <i class="icon-share-alt"></i> 推荐
                        </a>
                        <a onclick="$.do_action('/admin/document/batchRecommend?attribute=2');">
                            <i class="icon-star"></i> 精华
                        </a>
                        <a onclick="$.do_action('/admin/document/batchtrash');">
                            <i class="icon-remove"></i> 放入回收站
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <!--            ---->

        <?php echo isset($data['page']) ? $data['page'] : ''; ?>

    </div>
    <input type='hidden' id='_portal_key' value='dashboard:home:pos' />

    <script type="text/javascript"> var _actions_icnt = "<?= $data['perNum'] ?>";</script>

    <?php Yaf_Loader::import(PATH_APP . '/modules/Admin/views/foot.phtml'); ?>