<?php Yaf_Loader::import(PATH_APP . '/modules/Admin/views/head.phtml'); ?>
<!--编辑器-->
<link rel="stylesheet" href="/static/admin/editor/themes/default/default.css" />
<script charset="utf-8" src="/static/admin/editor/kindeditor-min.js"></script>
<script charset="utf-8" src="/static/admin/editor/lang/zh_CN.js"></script>
<!--编辑器初始化-->
<script>
    var editor;
    KindEditor.ready(function (K) {
        editor = K.create('textarea[name="content"]', {
            allowFileManager: true,
            filterMode: false,
            minChangeSize: 10
        });
    });</script>


<div class="navbar content-navbar navbar-default navbar-xs" data-toggle="breakpoint"
     data-class-xs="navbar content-navbar navbar-inverse navbar-xs"
     data-class-sm="navbar content-navbar navbar-default navbar-xs">
    <div class="navbar-header">
        <a class="navbar-brand" data-toggle="collapse" data-target="#top-nav .navbar-collapse">
            <i class="icon-home" style='position:relative;top:4px;'></i> 当前位置：编辑页面
        </a>
    </div>
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">   
        </ul>
        <div class="navbar-btn navbar-right hide-xs">
            <a title="编辑页面" href="<?= $data['referer'] ?>" class="btn btn-primary">
                <i class="icon-plus icon-white"></i> <span>返回列表</span></a>
        </div>
    </div>
</div>    



<form id="managememberFrom" class = "exform rended" enctype = "multipart/form-data" action = "/admin/document/update/" method = "post" >
    <input type = "hidden" value = "<?php echo $data['news']['id'] ?>" name = "id">
    <input type = "hidden" value = "<?php echo $data['referer'] ?>" name = "referer">
    <div class = "form-container row clearfix">
        <div id = "column-0" class = "column form-column main col col-sm-9 form-horizontal ui-sortable">

            <div class = "panel panel-default fieldset" id = "box-1">
                <div class = "panel-heading"><i class = "icon icon-chevron-up chevron"></i><h3 class = "panel-title">编辑页面</h3></div>
                <div class = "panel-body ">

                    <div class = "form-group">
                        <label class = "control-label ">栏目</label>
                        <div class = "controls ">
                            <select name="catid" class = "text-field admintextinputwidget form-control" >
                                <?php foreach ($categorys as $key => $category) { ?>
                                    <option value="<?= $category['catid'] ?>"  <?php if ($category['catid'] == $data['news']['catid']) { ?>selected="selected"<?php } ?> >
                                        <?= $category['catname'] ?>
                                    </option>
                                <?php } ?>      
                            </select>
                        </div>
                    </div>

                    <div id = "username" class = "form-group">
                        <label class = "control-label ">标题</label>
                        <div class = "controls ">
                            <input name = "title"   required  minlength="5" maxlength="50" value="<?= $data['news']['title'] ?>" class = "text-field admintextinputwidget form-control" id = "id_user_name" type = "text">
                        </div>
                    </div>

                    <div id = "keywords" class = "form-group">
                        <label class = "control-label ">关键词</label>
                        <div class = "controls ">
                            <input name = "keywords" value="<?= $data['news']['keywords'] ?>" class = "text-field admintextinputwidget form-control"  type = "text">
                        </div>
                    </div>

                    <div  class = "form-group">
                        <label class = "control-label ">描述</label>
                        <div class = "controls ">
                            <textarea name="desc" style="width:98%;height:150px;"><?= $data['news']['description'] ?></textarea>                                        
                        </div>
                    </div>

                    <div class = "form-group">
                        <label class = "control-label ">页面地址</label>
                        <div class = "controls ">
                            <input name = "url"   id = "islink"   minlength="5" maxlength="100" value="" class = "text-field admintextinputwidget form-control" type = "text">
                        </div>
                    </div>

                    <div class = "form-group">
                        <label class = "control-label ">内容</label>
                        <div class = "controls ">
                            <textarea name="content" style="width:98%;height:400px;"><?= $data['news']['content'] ?></textarea>                                        
                        </div>
                    </div>



                </div>
            </div>
            <div id = "column-1" class = "column form-column sidebar col col-sm-3 ui-sortable"></div>
        </div>

        <div class = "form-actions well well-sm clearfix">
            <button type = "submit" class = "default btn btn-primary hide-xs" name = "_save" data-loading-text = "保存中.."><i class = "icon-save"></i> 保存</button>
        </div>
    </div>
</form>

<input type = 'hidden' id = '_portal_key' value = 'dashboard:home:pos' />


<!--验证-->
<script type="text/javascript" src="/static/js/jquery.validate.min.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.validate.messages.cn.js"></script>


<?php Yaf_Loader::import(PATH_APP . '/modules/Admin/views/foot.phtml'); ?>