/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class network */

#ifndef _Included_network
#define _Included_network
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     network
 * Method:    Network_Init
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_network_Network_1Init
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     network
 * Method:    Network_Connect
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_network_Network_1Connect
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     network
 * Method:    Network_Recv
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_network_Network_1Recv
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     network
 * Method:    Network_Send
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_network_Network_1Send
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     network
 * Method:    Network_String
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_network_Network_1String
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
