<?php Yaf_Loader::import(PATH_APP . '/modules/Admin/views/head.phtml'); ?>
<div class="navbar content-navbar navbar-default navbar-xs" data-toggle="breakpoint"
     data-class-xs="navbar content-navbar navbar-inverse navbar-xs"
     data-class-sm="navbar content-navbar navbar-default navbar-xs">
    <div class="navbar-header">
        <a class="navbar-brand" data-toggle="collapse" data-target="#top-nav .navbar-collapse">
            <i class="icon-home" style='position:relative;top:4px;'></i> 当前位置：子类管理
        </a>
    </div>
    <div class="navbar-collapse collapse">
        <div class="navbar-btn navbar-right hide-xs">
            <a title="新建子类" href="/admin/topicsubclass/add?tid=<?=$topic_id?>" class="btn btn-primary">
                <i class="icon-plus icon-white"></i> <span>新建子类</span>
            </a>
        </div>
    </div>
</div>
<div class="dashboard row">
    <div class="col-sm-12 column">
        <!--频道列表-->
        <div class="panel panel-default widget addform form-horizontal short_label fieldset" id="88">
            <div class="panel-heading"><i class='icon icon-chevron-up chevron'></i><h3 class="panel-title">子类列表 </h3></div>
            <div class="panel-body " >
                <table class="table table-hover table-striped">
                    <tr>
                        <th width="5%">子类ID</th>
                        <th width="10%">子类标题</th>
                        <th width="5%">所属用户</th>
                        <th width="5%">状态</th>
                        <th width="25%">操作</th>
                    </tr>
                    <?php
                    foreach ($data['data'] as $value) {
                        ?>
                        <tr>
                            
                            <td><?=$value['id']; ?></td>
                            <td><?=$value['title'];?></td>
                            <td><?=$value['username'];?></td>
                            <td><?=$value['status'] ? '显示' : '隐藏'; ?></td>
                            <td>
                                <a href='/admin/topicsubclass/edit?tid=<?=$topic_id?>&sid=<?=$value['id']; ?>'>编辑</a>
                                <a href='/admin/topicsubclass/delete?tid=<?=$topic_id?>&sid=<?=$value['id'] ?>' onclick="javascript:return confirm('确定要删除该子类吗？')">删除</a>
                                <?=$value['status'] ? "<a href='/admin/topicsubclass/changeSubStatus?sid=".$value['id']."&status=0'>隐藏</a>" : "<a href='/admin/topicsubclass/changeSubStatus?sid=".$value['id']."&status=1'>显示</a>"; ?>
                                <a href="/admin/topicdata/add?tid=<?=$topic_id?>&sid=<?=$value['id']?>">添加文章</a>
                                <a href="/admin/topicsubclass/showdata?tid=<?=$topic_id?>&sid=<?=$value['id']?>">列表页数据管理</a>
                                <a href="/admin/topicsubclass/contentdata?tid=<?=$topic_id?>&sid=<?=$value['id']?>">内容页数据管理</a>
                                <a href="/admin/topicdata/batchAdd?tid=<?=$topic_id?>&sid=<?=$value['id']?>">批量添加文章</a>
                            </td>
                        </tr>
                        <?php
                    }
                    ?>
                    <tr>
                        <td colspan=9 style='text-align:right;'><?php echo isset($data['page']) ? $data['page']:''; ?> </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>
<input type='hidden' id='_portal_key' value='dashboard:home:pos' />
<?php Yaf_Loader::import(PATH_APP . '/modules/Admin/views/foot.phtml'); ?>