<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title><?= isset($title) ? $title : (isset($config['title']) ? $config['title'] : '') ?></title>
        <base target="_blank"/>
        <meta name="Keywords" content="<?= isset($keywords) ? $keywords : (isset($config['keywords']) ? $config['keywords'] : '') ?>"  />
        <meta name="Description" content="<?= isset($description) ? $description : (isset($config['description']) ? $config['description'] : '') ?>" />
        <link href="<?= IMGURL ?>static/css/index.css" rel="stylesheet" type="text/css" />
        <link href="<?= IMGURL ?>static/css/list.css" rel="stylesheet" type="text/css" />
        <link href="<?= IMGURL ?>static/css/content.css" rel="stylesheet" type="text/css" />
        <script type="text/javascript" src="<?= IMGURL ?>static/manage/systemjs.aspx"></script>
        <script src="<?= IMGURL ?>static/js/jQuery-1.11.0.js" type="text/javascript"></script>
        <script type="text/javascript" src="<?= IMGURL ?>static/js/rwbanner.js"></script>
    </head>

    <body>
        <div class="contain">
            <div class="head"><img src="<?= IMGURL ?>static/images/logo.gif" style="margin-top:20px;" /><img src="<?= IMGURL ?>static/images/9.jpg" style="float:right;" /></div>
            <div class="nav" id="nav">
                <ul>
                    <li class="hover"><a href="/kpzx/">网站首页<br /><span>Home</span></a></li>
                    <li><a href="/kpzx/sxqj/">神闲气静<br /><span>Colonel God</span></a></li>
                    <li><a href="/kpzx/dzxy/">对症下药<br /><span>Remedy</span></a></li>
                    <li><a href="/kpzx/lkjj/">临渴掘井<br /><span>Matz</span></a></li>
                    <li><a href="/kpzx/zjzb/">知己知彼<br /><span>EuropeMix</span></a></li>
                    <li><a href="/kpzx/wycm/">未雨绸缪<br /><span>Prepar</span></a></li>
                    <li><a href="/kpzx/jsyh/">健身养护<br /><span>Curing</span></a></li>
                    <li><a href="/kpzx/ysyz/">饮食原则<br /><span>Food</span></a></li>
                    <li><a href="/kpzx/ldyz/">老当益壮<br /><span>Vasolin</span></a></li>
                    <li><a href="/kpzx/bjqf/">百计千方<br /><span>Game Plan</span></a></li>
                    <li><a href="/kpzx/slzb/">霜露之病<br /><span>Frost</span></a></li>
                    <li><a href="/kpzx/qbyn/">却病延年<br /><span>Frolong</span></a></li>
                    <li class="last1"><a href="/kpzx/jkzn/">健康指南<br /><span>Guide</span></a></li>
                </ul>
            </div>