		<!--手机底部-->
		<footer>
			<p class="p4">
			<a name="sj_tel">
				<img src="<?=IMGURL?>static/images/qq20140707153814_01.jpg">
			</a>
			<a href="javascript:openZoosUrl('chatwin')" name="sj_swt">
				<img src="<?=IMGURL?>static/images/qq20140707153814_02.jpg">
			</a>
			<a href="javascript:openZoosUrl('chatwin')" name="sj_swt">
				<img src="<?=IMGURL?>static/images/qq20140707153814_03.jpg"></a>
			<a href="javascript:openZoosUrl('chatwin')" name="sj_swt">
				<img src="<?=IMGURL?>static/images/qq20140707153814_04.jpg"></a>
			</p>
		</footer>
		<!--手机底部end-->
		<div style="display: none">
        <script type="text/javascript">
            var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
            document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3F48f1419d9ce761612ada810a8f14ac26' type='text/javascript'%3E%3C/script%3E"));
        </script>
    </div>
	</body>
</html>