<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=GBK">
    <title><?= isset($title) ? $title.'_'.SITENAME : SITENAME ?></title>
    <base href="." target="_blank">                    
    <meta name="keywords" content="<?= isset($config['keywords']) ? $config['keywords'] : '' ?>"> 
    <meta name="Description" content="{FieldName=Info Length=156}">
    <meta name="applicable-device" content="mobile"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0;">
    <meta name="format-detection" content="telephone=no">
    <link href="<?=IMGURL?>static/css/style1211.css" rel="stylesheet" type="text/css">
    <link href="<?=IMGURL?>static/css/index1211.css" rel="stylesheet" type="text/css">
    <script src="<?=IMGURL?>static/js/jquery-1.4.2.js" type="text/javascript"></script>
    <script type="text/javascript" src="<?=IMGURL?>static/js/userJsFrame.js"></script>
    <script src="<?=IMGURL?>static/js/index0929.js" type="text/javascript"></script>
    <script src="<?=IMGURL?>static/js/dhqh.js" type="text/javascript"></script>
</head>
<body>
    <div class="hd01">
        <a href="<?=BASEURL.SITEDIR.'/'?>" class="a1">首页</a>
        <div id="zk">
            <img src="<?=IMGURL?>static/images/sjmh_003.jpg" width="22" height="17">
            <div class="content none">
                <ul>
                    <li><a href="/kpzx/ldmy/">灵丹圣药</a></li>
                    <li><a href="/kpzx/pajk/">平安健康</a></li>
                    <li><a href="/kpzx/jkys/">健康养生</a></li>
                    <li><a href="/kpzx/yszd/">养生之道</a></li>
                    <li><a href="/kpzx/fbzd/">防病指导</a></li>
                    <li><a href="/kpzx/jkjm/">健康揭秘</a></li>
                    <li><a href="/kpzx/jkxx/">健康信息</a></li>
                    <li><a href="/kpzx/jkbk/">健康百科</a></li>
                    <li><a href="/kpzx/jkqy/">健康求医</a></li>
                    <li><a href="/kpzx/jzfb/">及早防备</a></li>
                    <li><a href="/kpzx/fwdj/">防微杜渐</a></li>
                    <li><a href="/kpzx/yskt/">养生课堂</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="hd02"><a style="text-decoration:none;">中国楼兰网</a></div>
