<html>
    <head>
        <title>统计</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="/static/admin/css/bootstrap.css" type="text/css" media="screen" rel="stylesheet" />
        <link rel="stylesheet" type="text/css" media="screen" href="/static/admin/css/bootstrap-datetimepicker.min.css">
        <script type="text/javascript" src="/static/admin/js/jquery.js"></script>
    </head>
    <body>
        <div class="container">
            <form role="form">
                <input type="hidden" name="key" value="<?= date('Y-m-d') ?>">
                <div class="form-group">
                    <label>开始时间</label>
                    <input name="starttime"  id='starttime'  value="<?= $data['starttime'] ?>" readonly class = "text-field admintextinputwidget form-control" maxlength = "50" type = "text" />
                </div>

                <div class="form-group">
                    <label>结束时间</label>
                    <input name="endtime"  id='endtime'  value="<?= $data['endtime'] ?>" readonly class = "text-field admintextinputwidget form-control" maxlength = "50" type = "text" />
                </div>
                <button type="submit" class="btn btn-success">搜索</button>
            </form>
            <table class="table table-bordered">
                <tr class="success">
                    <th>总量</th>
                    <th>今日数量</th>
                    <th><?= $data['starttime'] ?> 至 <?= $data['endtime'] ?></th>
                </tr>
                <tr>
                    <td><?= $data['count'] ?></td>
                    <td><?= $data['todayCount'] ?></td>
                    <td><?= $data['searchCount'] ?></td>
                </tr>

            </table>
            <table class="table table-bordered">
                <tr class="success">
                    <th width="10%">id</th>
                    <th>标题</th>
                    <th width="15%">录入时间</th>
                </tr>

                <?php
                if ($data['data']) {
                    foreach ($data['data'] as $key => $value) {
                        ?>
                        <tr <?php if ($key % 2 != 0) { ?> class="active" <?php } ?>>
                            <td><?= $value['id'] ?></td>
                            <td>
                                <a href="<?= BASEURL . SITEDIR . '/' . $category[$value['catid']]['catpath'] . '/' . $value['id'] ?>.html" target="_blank"><?= $value['title'] ?></a>
                            </td>
                            <td><?= date('Y-m-d H:i:s', $value['inputtime']) ?></td>
                        </tr>
                        <?php
                    }
                }
                ?>


            </table>
            <?php echo isset($data['page']) ? $data['page'] : ''; ?>
        </div>

        <script type="text/javascript">
            $(function () {
                $("#starttime").datetimepicker({
                    autoclose: 1,
                    format: 'yyyy-mm-dd hh:ii:ss',
                    language: 'zh-CN',
                    todayBtn: 1,
                    todayHighlight: 1,
                });
                $("#endtime").datetimepicker({
                    autoclose: 1,
                    format: 'yyyy-mm-dd hh:ii:ss',
                    language: 'zh-CN',
                    todayBtn: 1,
                    todayHighlight: 1,
                });
            });
        </script>
        <script type="text/javascript" src="/static/admin/js/bootstrap.js"></script>
        <script type="text/javascript" src="/static/admin/js/bootstrap-datetimepicker.min.js"></script>
        <script type="text/javascript" src="/static/admin/js/bootstrap-datetimepicker.zh-CN.js"  charset="UTF-8"></script>
    </body>
</html>
