
#include <string.h>
#include "lg_string.h"
#include "lg_string_json.h"
#include "ad_system_json_packet.h"

const char *ad_system_json_packet_head_parse(json_object *json_root)
{

    json_object *PACKET_TYPE = NULL;
    if (!(PACKET_TYPE = json_object_object_get(json_root, "PACKET_TYPE")))
	return NULL;

    const char *packet_type = NULL;
    if (!(packet_type = json_object_get_string(PACKET_TYPE)))
	return NULL;

    return packet_type;
}

const char *ad_system_json_packet_value_parse(json_object *json_root, const char *key)
{

    json_object *KEY = NULL;
    if (!(KEY = json_object_object_get(json_root, key)))
	return NULL;

    char *value = NULL;
    if (!(value = (char *)json_object_get_string(KEY)))
	return NULL;

    return value;
}

json_object *ad_system_json_packet_data_parse(json_object *json_root, ad_system_packet_json_data_t *json)
{

    memset(json, 0, sizeof(ad_system_packet_json_data_t));

    GET_JSON_VALUE_STR(PASS_OLD, "PASS_OLD");
    GET_JSON_VALUE_STR(PASS_NEW, "PASS_NEW");

    GET_JSON_VALUE_NUM(FIND_TYPE, "FIND_TYPE");
    GET_JSON_VALUE_STR2(FIND_NAME, "FIND_NAME");
    GET_JSON_VALUE_NUM(PAGE_COUNT, "PAGE_COUNT");
    GET_JSON_VALUE_NUM(PAGE_INDEX, "PAGE_INDEX");
    if (json->PAGE_COUNT && json->PAGE_INDEX)
	json->page_index_s = json->PAGE_COUNT * json->PAGE_INDEX - json->PAGE_COUNT + 1;
    if (json->PAGE_COUNT && json->PAGE_INDEX)
	json->page_index_e = json->page_index_s + json->PAGE_COUNT - 1;

    GET_JSON_VALUE_NUM(DATE_TYPE, "DATE_TYPE");
    GET_JSON_VALUE_NUM(DISPLAY_STATUS, "DISPLAY_STATUS");

    GET_JSON_VALUE_NUM(SORT_COLUMN, "SORT_COLUMN");
    GET_JSON_VALUE_NUM(SORT_TYPE, "SORT_TYPE");

    GET_JSON_VALUE_NUM(FIND_NAME_TYPE, "FIND_NAME_TYPE");
    GET_JSON_VALUE_NUM(FIND_STATUS, "FIND_STATUS");
    GET_JSON_VALUE_NUM(UPDATE_TYPE, "UPDATE_TYPE");
    GET_JSON_VALUE_NUM(STATUS, "STATUS");

    GET_JSON_VALUE_NUM(TIME_TYPE, "TIME_TYPE");
    GET_JSON_VALUE_STR(BEGIN_TIME, "BEGIN_TIME");
    GET_JSON_VALUE_STR(END_TIME, "END_TIME");

    GET_JSON_VALUE_STR(CAMPAIGN_ID, "CAMPAIGN_ID");
    GET_JSON_VALUE_STR2(CAMPAIGN_NAME, "CAMPAIGN_NAME");
    GET_JSON_VALUE_STR(CAMPAIGN_BUDGET, "CAMPAIGN_BUDGET");
    GET_JSON_VALUE_NUM(CAMPAIGN_STATUS, "CAMPAIGN_STATUS");

    GET_JSON_VALUE_NUM(REGION_TYPE, "REGION_TYPE");
    GET_JSON_VALUE_STR(REGION_SERIALIZE, "REGION_SERIALIZE");
    GET_JSON_VALUE_NUM(SCHEDULE_TYPE, "SCHEDULE_TYPE");
    GET_JSON_VALUE_STR(SCHEDULE_SERIALIZE, "SCHEDULE_SERIALIZE");

    GET_JSON_VALUE_STR(GROUP_ID, "GROUP_ID");
    GET_JSON_VALUE_NUM(GROUP_NAME_TYPE, "GROUP_NAME_TYPE");
    GET_JSON_VALUE_STR2(GROUP_NAME, "GROUP_NAME");
    GET_JSON_VALUE_NUM(GROUP_PRICE_TYPE, "GROUP_PRICE_TYPE");
    GET_JSON_VALUE_STR(GROUP_CPC_PRICE, "GROUP_CPC_PRICE");
    GET_JSON_VALUE_STR(GROUP_CPM_PRICE, "GROUP_CPM_PRICE");
    GET_JSON_VALUE_NUM(GROUP_TARGETING_TYPE, "GROUP_TARGETING_TYPE");
    GET_JSON_VALUE_STR(GROUP_DISEASE, "GROUP_DISEASE");
    GET_JSON_VALUE_STR(GROUP_KEYWORD_ID, "GROUP_KEYWORD_ID");
    GET_JSON_VALUE_STR(GROUP_KEYWORD, "GROUP_KEYWORD");

    GET_JSON_VALUE_STR(CREATIVE_ID, "CREATIVE_ID");
    GET_JSON_VALUE_STR2(CREATIVE_NAME, "CREATIVE_NAME");
    GET_JSON_VALUE_NUM(CREATIVE_STATUS, "CREATIVE_STATUS");
    GET_JSON_VALUE_STR2(CREATIVE_DESCRIPTION, "CREATIVE_DESCRIPTION");
    GET_JSON_VALUE_STR(MOBILE_DESTINATION_URL, "MOBILE_DESTINATION_URL");
    GET_JSON_VALUE_STR(MOBILE_DISPLAY_URL, "MOBILE_DISPLAY_URL");
    GET_JSON_VALUE_STR(CREATIVE_DESTINATION_URL, "CREATIVE_DESTINATION_URL");
    GET_JSON_VALUE_STR(CREATIVE_DISPLAY_URL, "CREATIVE_DISPLAY_URL");
    GET_JSON_VALUE_STR(CREATIVE_IMG_ID, "CREATIVE_IMG_ID");


    GET_JSON_VALUE_STR(CREATIVE_APPEND_ID, "CREATIVE_APPEND_ID");
    GET_JSON_VALUE_NUM(APPEND_STATUS, "APPEND_STATUS");
    GET_JSON_VALUE_STR(APPEND_CONTENT, "APPEND_CONTENT");
    GET_JSON_VALUE_NUM(CREATIVE_APPEND_TYPE, "CREATIVE_APPEND_TYPE");

    GET_JSON_VALUE_STR(ID, "ID");
    GET_JSON_VALUE_NUM(ID_TYPE, "ID_TYPE");
    GET_JSON_VALUE_NUM(BATCH_TYPE, "BATCH_TYPE");

    GET_JSON_VALUE_STR(REPORT_ID, "REPORT_ID");
    GET_JSON_VALUE_NUM(REPORT_SPECIES, "REPORT_SPECIES");
    GET_JSON_VALUE_NUM(REPORT_TYPE, "REPORT_TYPE");
    GET_JSON_VALUE_STR(REPORT_NAME, "REPORT_NAME");
    GET_JSON_VALUE_STR(TIME_START, "TIME_START");
    GET_JSON_VALUE_STR(TIME_END, "TIME_END");
    GET_JSON_VALUE_NUM(REPORT_BELONG, "REPORT_BELONG");

    GET_JSON_VALUE_NUM(MONEY_TYPE, "MONEY_TYPE");
    GET_JSON_VALUE_STR(COMPANY_NAME, "COMPANY_NAME");
    GET_JSON_VALUE_STR(COMPANY_SITE, "COMPANY_SITE");
    GET_JSON_VALUE_STR(INDUSTRY , "INDUSTRY");
    GET_JSON_VALUE_STR(PROVINCE_ID, "PROVINCE_ID");
    GET_JSON_VALUE_STR(CITY_ID, "CITY_ID");
    GET_JSON_VALUE_STR(ADDRESS, "ADDRESS");
    GET_JSON_VALUE_STR(POSTCODE, "POSTCODE");
    GET_JSON_VALUE_STR(CONTACT, "CONTACT");
    GET_JSON_VALUE_STR(TELEPHONE, "TELEPHONE");
    GET_JSON_VALUE_STR(FAX, "FAX");
    GET_JSON_VALUE_STR(MOBILE, "MOBILE");
    GET_JSON_VALUE_STR(EMAIL, "EMAIL");
    GET_JSON_VALUE_STR(WEBIM, "WEBIM");
    GET_JSON_VALUE_STR(KEY, "KEY");

    GET_JSON_VALUE_STR(ACCOUNT_ID, "ACCOUNT_ID");
    GET_JSON_VALUE_NUM(CREATIVE_TYPE, "CREATIVE_TYPE");

    GET_JSON_VALUE_NUM(DEPT_TYPE, "DEPT_TYPE");
    GET_JSON_VALUE_STR(DEPT_SERIALIZE, "DEPT_SERIALIZE");

    GET_JSON_VALUE_STR(SHOW_TIME_START, "SHOW_TIME_START");
    GET_JSON_VALUE_STR(SHOW_TIME_END, "SHOW_TIME_END");
    GET_JSON_VALUE_STR(PRICE, "PRICE");
    GET_JSON_VALUE_STR(BRAND_ID, "BRAND_ID");

    GET_JSON_VALUE_NUM(INSERT_TYPE, "INSERT_TYPE");
    GET_JSON_VALUE_NUM(MOD_STATUS, "MOD_STATUS");


    GET_JSON_VALUE_STR(TITLE, "TITLE");
    GET_JSON_VALUE_STR(DESCRIPTION, "DESCRIPTION");
    GET_JSON_VALUE_STR(DESTINATION_URL, "DESTINATION_URL");
    GET_JSON_VALUE_STR(DISPLAY_URL, "DISPLAY_URL");
    GET_JSON_VALUE_STR(WEB_SITE, "WEB_SITE");
    GET_JSON_VALUE_STR(WEB_IM, "WEB_IM");
    GET_JSON_VALUE_STR(GUAHAO_URL, "GUAHAO_URL");

    GET_JSON_VALUE_STR(IMG0_ID,	    "IMG0_ID");
    GET_JSON_VALUE_STR(IMG0_URL,    "IMG0_URL");
    GET_JSON_VALUE_STR(IMG1_ID,     "IMG1_ID");
    GET_JSON_VALUE_STR(IMG1_URL,    "IMG1_URL");
    GET_JSON_VALUE_STR(IMG2_ID,     "IMG2_ID");
    GET_JSON_VALUE_STR(IMG2_URL,    "IMG2_URL");
    GET_JSON_VALUE_STR(IMG3_ID,     "IMG3_ID");
    GET_JSON_VALUE_STR(IMG3_URL,    "IMG3_URL");
    GET_JSON_VALUE_STR(IMG4_ID,     "IMG4_ID");
    GET_JSON_VALUE_STR(IMG4_URL,    "IMG4_URL");
    GET_JSON_VALUE_STR(IMG5_ID,     "IMG5_ID");
    GET_JSON_VALUE_STR(IMG5_URL,    "IMG5_URL");

    GET_JSON_VALUE_STR(BRAND_CREATIVE_ID,    "BRAND_CREATIVE_ID");
    GET_JSON_VALUE_NUM(SHOW_TIME_TYPE, "SHOW_TIME_TYPE");

    //json_object_put(json_root);
    return json_root;
}



