<div id="footer">
    <hr/>
    <footer class="text-center">
      <p>&copy; 联创兄弟 2014</p>
    </footer>
</div>
  <script type='text/javascript'>
            $(function() {
                if ($('.alert').text() !== '') {
                    setTimeout(function() {
                        $('.alert').fadeOut();
                    }, 3000);
                }
            });
        </script>