</div>
<!-- content endt -->
</div>
<!-- body endt -->
<!--footer-->
<div id="footer">
    <hr/>
    <footer class="text-center">
        <p>&copy; 联创兄弟 2014</p>
    </footer>
</div>
<script type='text/javascript'>
    $(function () {
        if ($('.alert').text() !== '') {
            setTimeout(function () {
                $('.alert').fadeOut();
            }, 3000);
        }
    });
</script>
<script type="text/javascript" src="/static/admin/js/jquery.ui.core.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.ui.widget.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.ui.mouse.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.ui.sortable.js"></script>
<script type="text/javascript" src="/static/admin/js/bootstrap.js"></script>
<script type="text/javascript" src="/static/admin/js/xadmin.main.js"></script>
<script type="text/javascript" src="/static/admin/js/xadmin.responsive.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.ui.effect.js"></script>
<script type="text/javascript" src="/static/admin/js/xadmin.plugin.themes.js"></script>
<script type="text/javascript" src="/static/admin/js/xadmin.page.dashboard.js"></script>
<script type="text/javascript" src="/static/admin/js/xadmin.plugin.portal.js"></script>
<script type="text/javascript" src="/static/admin/js/bootstrap-datepicker.js"></script>
<script type="text/javascript" src="/static/admin/js/xadmin.widget.datetime.js"></script>
<script type="text/javascript" src="/static/admin/js/xadmin.page.form.js"></script>
<script type="text/javascript" src="/static/admin/js/xadmin.plugin.quick-form.js"></script>

<!--时间插件-->
<script type="text/javascript" src="/static/admin/js/bootstrap-datetimepicker.min.js"></script>
<script type="text/javascript" src="/static/admin/js/bootstrap-datetimepicker.zh-CN.js"  charset="UTF-8"></script>

<!--checkbox-->
<script type="text/javascript" src="/static/admin/js/xadmin.plugin.actions.js"></script>
</body>
</html>