/* soapClient.c
   Generated by gSOAP 2.8.14 from demo.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.8.14 2013-07-19 09:54:08 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__authLogin(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns2__authLogin *ns2__authLogin, struct ns2__authLoginResponse *ns2__authLoginResponse)
{	struct __ns1__authLogin soap_tmp___ns1__authLogin;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://semtools.leechat.com/server/ws/account";
	if (soap_action == NULL)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__authLogin.ns2__authLogin = ns2__authLogin;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__authLogin(soap, &soap_tmp___ns1__authLogin);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__authLogin(soap, &soap_tmp___ns1__authLogin, "-ns1:authLogin", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__authLogin(soap, &soap_tmp___ns1__authLogin, "-ns1:authLogin", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__authLoginResponse)
		return soap_closesock(soap);
	soap_default_ns2__authLoginResponse(soap, ns2__authLoginResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns2__authLoginResponse(soap, ns2__authLoginResponse, "ns2:authLoginResponse", "ns2:authLoginResponse");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__queryAllAccount(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns2__queryAllAccount *ns2__queryAllAccount, struct ns2__queryAllAccountResponse *ns2__queryAllAccountResponse)
{	struct __ns1__queryAllAccount soap_tmp___ns1__queryAllAccount;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://semtools.leechat.com/server/ws/account";
	if (soap_action == NULL)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__queryAllAccount.ns2__queryAllAccount = ns2__queryAllAccount;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__queryAllAccount(soap, &soap_tmp___ns1__queryAllAccount);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__queryAllAccount(soap, &soap_tmp___ns1__queryAllAccount, "-ns1:queryAllAccount", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__queryAllAccount(soap, &soap_tmp___ns1__queryAllAccount, "-ns1:queryAllAccount", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__queryAllAccountResponse)
		return soap_closesock(soap);
	soap_default_ns2__queryAllAccountResponse(soap, ns2__queryAllAccountResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns2__queryAllAccountResponse(soap, ns2__queryAllAccountResponse, "ns2:queryAllAccountResponse", "ns2:queryAllAccountResponse");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__deleteAccount(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns2__deleteAccount *ns2__deleteAccount, struct ns2__deleteAccountResponse *ns2__deleteAccountResponse)
{	struct __ns1__deleteAccount soap_tmp___ns1__deleteAccount;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://semtools.leechat.com/server/ws/account";
	if (soap_action == NULL)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__deleteAccount.ns2__deleteAccount = ns2__deleteAccount;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__deleteAccount(soap, &soap_tmp___ns1__deleteAccount);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__deleteAccount(soap, &soap_tmp___ns1__deleteAccount, "-ns1:deleteAccount", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__deleteAccount(soap, &soap_tmp___ns1__deleteAccount, "-ns1:deleteAccount", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__deleteAccountResponse)
		return soap_closesock(soap);
	soap_default_ns2__deleteAccountResponse(soap, ns2__deleteAccountResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns2__deleteAccountResponse(soap, ns2__deleteAccountResponse, "ns2:deleteAccountResponse", "ns2:deleteAccountResponse");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__addAccount(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns2__addAccount *ns2__addAccount, struct ns2__addAccountResponse *ns2__addAccountResponse)
{	struct __ns1__addAccount soap_tmp___ns1__addAccount;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://semtools.leechat.com/server/ws/account";
	if (soap_action == NULL)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__addAccount.ns2__addAccount = ns2__addAccount;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__addAccount(soap, &soap_tmp___ns1__addAccount);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__addAccount(soap, &soap_tmp___ns1__addAccount, "-ns1:addAccount", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__addAccount(soap, &soap_tmp___ns1__addAccount, "-ns1:addAccount", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__addAccountResponse)
		return soap_closesock(soap);
	soap_default_ns2__addAccountResponse(soap, ns2__addAccountResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns2__addAccountResponse(soap, ns2__addAccountResponse, "ns2:addAccountResponse", "ns2:addAccountResponse");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__queryAccount(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns2__queryAccount *ns2__queryAccount, struct ns2__queryAccountResponse *ns2__queryAccountResponse)
{	struct __ns1__queryAccount soap_tmp___ns1__queryAccount;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://semtools.leechat.com/server/ws/account";
	if (soap_action == NULL)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__queryAccount.ns2__queryAccount = ns2__queryAccount;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__queryAccount(soap, &soap_tmp___ns1__queryAccount);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__queryAccount(soap, &soap_tmp___ns1__queryAccount, "-ns1:queryAccount", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__queryAccount(soap, &soap_tmp___ns1__queryAccount, "-ns1:queryAccount", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__queryAccountResponse)
		return soap_closesock(soap);
	soap_default_ns2__queryAccountResponse(soap, ns2__queryAccountResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns2__queryAccountResponse(soap, ns2__queryAccountResponse, "ns2:queryAccountResponse", "ns2:queryAccountResponse");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__updateAccount(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns2__updateAccount *ns2__updateAccount, struct ns2__updateAccountResponse *ns2__updateAccountResponse)
{	struct __ns1__updateAccount soap_tmp___ns1__updateAccount;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://semtools.leechat.com/server/ws/account";
	if (soap_action == NULL)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__updateAccount.ns2__updateAccount = ns2__updateAccount;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__updateAccount(soap, &soap_tmp___ns1__updateAccount);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__updateAccount(soap, &soap_tmp___ns1__updateAccount, "-ns1:updateAccount", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__updateAccount(soap, &soap_tmp___ns1__updateAccount, "-ns1:updateAccount", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__updateAccountResponse)
		return soap_closesock(soap);
	soap_default_ns2__updateAccountResponse(soap, ns2__updateAccountResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns2__updateAccountResponse(soap, ns2__updateAccountResponse, "ns2:updateAccountResponse", "ns2:updateAccountResponse");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__updateLoginPassword(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns2__updateLoginPassword *ns2__updateLoginPassword, struct ns2__updateLoginPasswordResponse *ns2__updateLoginPasswordResponse)
{	struct __ns1__updateLoginPassword soap_tmp___ns1__updateLoginPassword;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://semtools.leechat.com/server/ws/account";
	if (soap_action == NULL)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__updateLoginPassword.ns2__updateLoginPassword = ns2__updateLoginPassword;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__updateLoginPassword(soap, &soap_tmp___ns1__updateLoginPassword);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__updateLoginPassword(soap, &soap_tmp___ns1__updateLoginPassword, "-ns1:updateLoginPassword", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__updateLoginPassword(soap, &soap_tmp___ns1__updateLoginPassword, "-ns1:updateLoginPassword", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__updateLoginPasswordResponse)
		return soap_closesock(soap);
	soap_default_ns2__updateLoginPasswordResponse(soap, ns2__updateLoginPasswordResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns2__updateLoginPasswordResponse(soap, ns2__updateLoginPasswordResponse, "ns2:updateLoginPasswordResponse", "ns2:updateLoginPasswordResponse");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.c */
