/* soapStub.h
   Generated by gSOAP 2.8.14 from demo.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapStub_H
#define soapStub_H
#define SOAP_NAMESPACE_OF_ns1	"https://api.baidu.com/sem/sms/v2"
#define SOAP_NAMESPACE_OF_ns2	"http://api.baidu.com/sem/common/v2"
#include "stdsoap2.h"
#if GSOAP_VERSION != 20814
# error "GSOAP VERSION MISMATCH IN GENERATED CODE: PLEASE REINSTALL PACKAGE"
#endif

#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (7)
/* xsd:boolean */
enum xsd__boolean { xsd__boolean__false_ = 0, xsd__boolean__true_ = 1 };
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE_ns1__AccountInfoType
#define SOAP_TYPE_ns1__AccountInfoType (8)
/* ns1:AccountInfoType */
struct ns1__AccountInfoType
{
	LONG64 *userid;	/* optional element of type xsd:long */
	double *balance;	/* optional element of type xsd:double */
	double *cost;	/* optional element of type xsd:double */
	double *payment;	/* optional element of type xsd:double */
	double *budget;	/* optional element of type xsd:double */
	int *type;	/* optional element of type xsd:int */
	int __sizeregionTarget;	/* sequence of elements <regionTarget> */
	int *regionTarget;	/* optional element of type xsd:int */
	int __sizeexcludeIp;	/* sequence of elements <excludeIp> */
	char **excludeIp;	/* optional element of type xsd:string */
	int __sizeopenDomains;	/* sequence of elements <openDomains> */
	char **openDomains;	/* optional element of type xsd:string */
	struct ns2__OptType *ns2__opt;	/* optional element of type ns2:OptType */
};
#endif

#ifndef SOAP_TYPE_ns1__ChangedCampaignIdType
#define SOAP_TYPE_ns1__ChangedCampaignIdType (17)
/* ns1:ChangedCampaignIdType */
struct ns1__ChangedCampaignIdType
{
	int operator_;	/* required element of type xsd:int */
	LONG64 campaignId;	/* required element of type xsd:long */
};
#endif

#ifndef SOAP_TYPE_ns1__ChangedAdgroupIdType
#define SOAP_TYPE_ns1__ChangedAdgroupIdType (18)
/* ns1:ChangedAdgroupIdType */
struct ns1__ChangedAdgroupIdType
{
	int operator_;	/* required element of type xsd:int */
	LONG64 campaignId;	/* required element of type xsd:long */
	LONG64 adgroupId;	/* required element of type xsd:long */
};
#endif

#ifndef SOAP_TYPE_ns1__ChangedItemType
#define SOAP_TYPE_ns1__ChangedItemType (19)
/* ns1:ChangedItemType */
struct ns1__ChangedItemType
{
	int operator_;	/* required element of type xsd:int */
	LONG64 id;	/* required element of type xsd:long */
	LONG64 adgroupId;	/* required element of type xsd:long */
	LONG64 campaignId;	/* required element of type xsd:long */
};
#endif

#ifndef SOAP_TYPE_ns1__VariableColumn
#define SOAP_TYPE_ns1__VariableColumn (20)
/* ns1:VariableColumn */
struct ns1__VariableColumn
{
	char *key;	/* required element of type xsd:string */
	char *value;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__TopNkeywordsData
#define SOAP_TYPE_ns1__TopNkeywordsData (21)
/* ns1:TopNkeywordsData */
struct ns1__TopNkeywordsData
{
	LONG64 keywordId;	/* required element of type xsd:long */
	float keywordCost;	/* required element of type xsd:float */
	float keywordACP;	/* required element of type xsd:float */
	float keywordClick;	/* required element of type xsd:float */
	char *keyword;	/* optional element of type xsd:string */
	int *isdel;	/* optional element of type xsd:int */
	int *status;	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__ChangedNewCreativeType
#define SOAP_TYPE_ns1__ChangedNewCreativeType (23)
/* ns1:ChangedNewCreativeType */
struct ns1__ChangedNewCreativeType
{
	int *operator_;	/* optional element of type xsd:int */
	LONG64 *id;	/* optional element of type xsd:long */
	LONG64 *adgroupId;	/* optional element of type xsd:long */
	LONG64 *campaignId;	/* optional element of type xsd:long */
};
#endif

#ifndef SOAP_TYPE_ns1__ChangedNewCreativeScaleType
#define SOAP_TYPE_ns1__ChangedNewCreativeScaleType (24)
/* ns1:ChangedNewCreativeScaleType */
struct ns1__ChangedNewCreativeScaleType
{
	int __sizechangedNewCreativeScale;	/* sequence of elements <changedNewCreativeScale> */
	LONG64 *changedNewCreativeScale;	/* optional element of type xsd:long */
};
#endif

#ifndef SOAP_TYPE__ns1__getAccountInfoRequest
#define SOAP_TYPE__ns1__getAccountInfoRequest (25)
/* ns1:getAccountInfoRequest */
struct _ns1__getAccountInfoRequest
{
	int type;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE__ns1__getAccountInfoResponse
#define SOAP_TYPE__ns1__getAccountInfoResponse (26)
/* ns1:getAccountInfoResponse */
struct _ns1__getAccountInfoResponse
{
	struct ns1__AccountInfoType *accountInfoType;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:AccountInfoType */
};
#endif

#ifndef SOAP_TYPE__ns1__updateAccountInfoRequest
#define SOAP_TYPE__ns1__updateAccountInfoRequest (28)
/* ns1:updateAccountInfoRequest */
struct _ns1__updateAccountInfoRequest
{
	struct ns1__AccountInfoType *accountInfoType;	/* required element of type ns1:AccountInfoType */
};
#endif

#ifndef SOAP_TYPE__ns1__updateAccountInfoResponse
#define SOAP_TYPE__ns1__updateAccountInfoResponse (29)
/* ns1:updateAccountInfoResponse */
struct _ns1__updateAccountInfoResponse
{
	struct ns1__AccountInfoType *accountInfoType;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:AccountInfoType */
};
#endif

#ifndef SOAP_TYPE__ns1__getChangedCampaignIdRequest
#define SOAP_TYPE__ns1__getChangedCampaignIdRequest (30)
/* ns1:getChangedCampaignIdRequest */
struct _ns1__getChangedCampaignIdRequest
{
	time_t startTime;	/* required element of type xsd:dateTime */
	enum xsd__boolean *campaignLevel;	/* optional element of type xsd:boolean */
	enum xsd__boolean *adgroupLevel;	/* optional element of type xsd:boolean */
	enum xsd__boolean *itemLevel;	/* optional element of type xsd:boolean */
	int *newCreativeLevel;	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE__ns1__getChangedCampaignIdResponse
#define SOAP_TYPE__ns1__getChangedCampaignIdResponse (33)
/* ns1:getChangedCampaignIdResponse */
struct _ns1__getChangedCampaignIdResponse
{
	time_t *endTime;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:dateTime */
	int __sizechangedCampaignIds;	/* sequence of elements <changedCampaignIds> */
	struct ns1__ChangedCampaignIdType *changedCampaignIds;	/* optional element of type ns1:ChangedCampaignIdType */
};
#endif

#ifndef SOAP_TYPE__ns1__getChangedAdgroupIdRequest
#define SOAP_TYPE__ns1__getChangedAdgroupIdRequest (36)
/* ns1:getChangedAdgroupIdRequest */
struct _ns1__getChangedAdgroupIdRequest
{
	time_t startTime;	/* required element of type xsd:dateTime */
	int __sizecampaignIds;	/* sequence of elements <campaignIds> */
	LONG64 *campaignIds;	/* optional element of type xsd:long */
	enum xsd__boolean *adgroupLevel;	/* optional element of type xsd:boolean */
	enum xsd__boolean *itemLevel;	/* optional element of type xsd:boolean */
	int *newCreativeLevel;	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE__ns1__getChangedAdgroupIdResponse
#define SOAP_TYPE__ns1__getChangedAdgroupIdResponse (37)
/* ns1:getChangedAdgroupIdResponse */
struct _ns1__getChangedAdgroupIdResponse
{
	time_t *endTime;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:dateTime */
	int __sizechangedAdgroupIds;	/* sequence of elements <changedAdgroupIds> */
	struct ns1__ChangedAdgroupIdType *changedAdgroupIds;	/* optional element of type ns1:ChangedAdgroupIdType */
};
#endif

#ifndef SOAP_TYPE__ns1__getChangedItemIdRequest
#define SOAP_TYPE__ns1__getChangedItemIdRequest (39)
/* ns1:getChangedItemIdRequest */
struct _ns1__getChangedItemIdRequest
{
	time_t startTime;	/* required element of type xsd:dateTime */
	int type;	/* required element of type xsd:int */
	int __sizeids;	/* sequence of elements <ids> */
	LONG64 *ids;	/* optional element of type xsd:long */
};
#endif

#ifndef SOAP_TYPE__ns1__getChangedItemIdResponse
#define SOAP_TYPE__ns1__getChangedItemIdResponse (40)
/* ns1:getChangedItemIdResponse */
struct _ns1__getChangedItemIdResponse
{
	time_t *endTime;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:dateTime */
	int __sizechangedKeywordIds;	/* sequence of elements <changedKeywordIds> */
	struct ns1__ChangedItemType *changedKeywordIds;	/* optional element of type ns1:ChangedItemType */
	int __sizechangedCreativeIds;	/* sequence of elements <changedCreativeIds> */
	struct ns1__ChangedItemType *changedCreativeIds;	/* optional element of type ns1:ChangedItemType */
};
#endif

#ifndef SOAP_TYPE__ns1__getChangedIdRequest
#define SOAP_TYPE__ns1__getChangedIdRequest (42)
/* ns1:getChangedIdRequest */
struct _ns1__getChangedIdRequest
{
	time_t startTime;	/* required element of type xsd:dateTime */
};
#endif

#ifndef SOAP_TYPE__ns1__getChangedIdResponse
#define SOAP_TYPE__ns1__getChangedIdResponse (43)
/* ns1:getChangedIdResponse */
struct _ns1__getChangedIdResponse
{
	time_t *endTime;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:dateTime */
	int __sizechangedCampaignIds;	/* sequence of elements <changedCampaignIds> */
	struct ns1__ChangedCampaignIdType *changedCampaignIds;	/* optional element of type ns1:ChangedCampaignIdType */
	int __sizechangedAdgroupIds;	/* sequence of elements <changedAdgroupIds> */
	struct ns1__ChangedAdgroupIdType *changedAdgroupIds;	/* optional element of type ns1:ChangedAdgroupIdType */
	int __sizechangedKeywordIds;	/* sequence of elements <changedKeywordIds> */
	struct ns1__ChangedItemType *changedKeywordIds;	/* optional element of type ns1:ChangedItemType */
	int __sizechangedCreativeIds;	/* sequence of elements <changedCreativeIds> */
	struct ns1__ChangedItemType *changedCreativeIds;	/* optional element of type ns1:ChangedItemType */
};
#endif

#ifndef SOAP_TYPE__ns1__getAllObjectsRequest
#define SOAP_TYPE__ns1__getAllObjectsRequest (44)
/* ns1:getAllObjectsRequest */
struct _ns1__getAllObjectsRequest
{
	int __sizecampaignIds;	/* sequence of elements <campaignIds> */
	LONG64 *campaignIds;	/* optional element of type xsd:long */
	enum xsd__boolean *includeQuality;	/* optional element of type xsd:boolean */
	enum xsd__boolean *includeTemp;	/* optional element of type xsd:boolean */
	int *format;	/* optional element of type xsd:int */
	int __sizevariableColumns;	/* sequence of elements <variableColumns> */
	struct ns1__VariableColumn *variableColumns;	/* optional element of type ns1:VariableColumn */
	int *newCreativeFiles;	/* optional element of type xsd:int */
	int *includeTempNewCreatives;	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE__ns1__getAllObjectsResponse
#define SOAP_TYPE__ns1__getAllObjectsResponse (46)
/* ns1:getAllObjectsResponse */
struct _ns1__getAllObjectsResponse
{
	char *fileId;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__getChangedScaleRequest
#define SOAP_TYPE__ns1__getChangedScaleRequest (47)
/* ns1:getChangedScaleRequest */
struct _ns1__getChangedScaleRequest
{
	time_t startTime;	/* required element of type xsd:dateTime */
	int __sizecampaignIds;	/* sequence of elements <campaignIds> */
	LONG64 *campaignIds;	/* optional element of type xsd:long */
	enum xsd__boolean *changedCampaignScale;	/* optional element of type xsd:boolean */
	enum xsd__boolean *changedAdgroupScale;	/* optional element of type xsd:boolean */
	enum xsd__boolean *changedKeywordScale;	/* optional element of type xsd:boolean */
	enum xsd__boolean *changedCreativeScale;	/* optional element of type xsd:boolean */
	int *changedNewCreativeScales;	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE__ns1__getChangedScaleResponse
#define SOAP_TYPE__ns1__getChangedScaleResponse (48)
/* ns1:getChangedScaleResponse */
struct _ns1__getChangedScaleResponse
{
	int __sizechangedCampaignScale;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* sequence of elements <changedCampaignScale> */
	LONG64 *changedCampaignScale;	/* optional element of type xsd:long */
	int __sizechangedAdgroupScale;	/* sequence of elements <changedAdgroupScale> */
	LONG64 *changedAdgroupScale;	/* optional element of type xsd:long */
	int __sizechangedKeywordScale;	/* sequence of elements <changedKeywordScale> */
	LONG64 *changedKeywordScale;	/* optional element of type xsd:long */
	int __sizechangedCreativeScale;	/* sequence of elements <changedCreativeScale> */
	LONG64 *changedCreativeScale;	/* optional element of type xsd:long */
	int __sizechangedNewCreativeScales;	/* sequence of elements <changedNewCreativeScales> */
	struct ns1__ChangedNewCreativeScaleType *changedNewCreativeScales;	/* optional element of type ns1:ChangedNewCreativeScaleType */
};
#endif

#ifndef SOAP_TYPE__ns1__getSelectedObjectsRequest
#define SOAP_TYPE__ns1__getSelectedObjectsRequest (50)
/* ns1:getSelectedObjectsRequest */
struct _ns1__getSelectedObjectsRequest
{
	int __sizecampaignIds;	/* sequence of elements <campaignIds> */
	LONG64 *campaignIds;	/* optional element of type xsd:long */
	int __sizecampaignSelectedColumn;	/* sequence of elements <campaignSelectedColumn> */
	char **campaignSelectedColumn;	/* optional element of type xsd:string */
	int __sizeadgroupSelectedColumn;	/* sequence of elements <adgroupSelectedColumn> */
	char **adgroupSelectedColumn;	/* optional element of type xsd:string */
	int __sizekeywordSelectedColumn;	/* sequence of elements <keywordSelectedColumn> */
	char **keywordSelectedColumn;	/* optional element of type xsd:string */
	int __sizecreativeSelectedColumn;	/* sequence of elements <creativeSelectedColumn> */
	char **creativeSelectedColumn;	/* optional element of type xsd:string */
	int __sizeselectedRow;	/* sequence of elements <selectedRow> */
	struct ns1__VariableColumn *selectedRow;	/* optional element of type ns1:VariableColumn */
	int *format;	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE__ns1__getSelectedObjectsResponse
#define SOAP_TYPE__ns1__getSelectedObjectsResponse (51)
/* ns1:getSelectedObjectsResponse */
struct _ns1__getSelectedObjectsResponse
{
	char *fileId;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__getFileStateRequest
#define SOAP_TYPE__ns1__getFileStateRequest (52)
/* ns1:getFileStateRequest */
struct _ns1__getFileStateRequest
{
	char *fileId;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__getFileStateResponse
#define SOAP_TYPE__ns1__getFileStateResponse (53)
/* ns1:getFileStateResponse */
struct _ns1__getFileStateResponse
{
	int *isGenerated;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE__ns1__getAllObjectsPathRequest
#define SOAP_TYPE__ns1__getAllObjectsPathRequest (54)
/* ns1:getAllObjectsPathRequest */
struct _ns1__getAllObjectsPathRequest
{
	char *fileId;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__getAllObjectsPathResponse
#define SOAP_TYPE__ns1__getAllObjectsPathResponse (55)
/* ns1:getAllObjectsPathResponse */
struct _ns1__getAllObjectsPathResponse
{
	char *accountFilePath;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
	char *accountFileMd5;	/* optional element of type xsd:string */
	char *campaignFilePath;	/* optional element of type xsd:string */
	char *campaignFileMd5;	/* optional element of type xsd:string */
	char *adgroupFilePath;	/* optional element of type xsd:string */
	char *adgroupFileMd5;	/* optional element of type xsd:string */
	char *keywordFilePath;	/* optional element of type xsd:string */
	char *keywordFileMd5;	/* optional element of type xsd:string */
	char *creativeFilePath;	/* optional element of type xsd:string */
	char *creativeFileMd5;	/* optional element of type xsd:string */
	int __sizenewCreativeFilePaths;	/* sequence of elements <newCreativeFilePaths> */
	char **newCreativeFilePaths;	/* optional element of type xsd:string */
	int __sizenewCreativeFileMd5s;	/* sequence of elements <newCreativeFileMd5s> */
	char **newCreativeFileMd5s;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__getSelectedObjectsPathRequest
#define SOAP_TYPE__ns1__getSelectedObjectsPathRequest (56)
/* ns1:getSelectedObjectsPathRequest */
struct _ns1__getSelectedObjectsPathRequest
{
	char *fileId;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__getSelectedObjectsPathResponse
#define SOAP_TYPE__ns1__getSelectedObjectsPathResponse (57)
/* ns1:getSelectedObjectsPathResponse */
struct _ns1__getSelectedObjectsPathResponse
{
	char *campaignSelectedFilePath;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
	char *campaignSelectedFileMd5;	/* optional element of type xsd:string */
	char *adgroupSelectedFilePath;	/* optional element of type xsd:string */
	char *adgroupSelectedFileMd5;	/* optional element of type xsd:string */
	char *keywordSelectedFilePath;	/* optional element of type xsd:string */
	char *keywordSelectedFileMd5;	/* optional element of type xsd:string */
	char *creativeSelectedFilePath;	/* optional element of type xsd:string */
	char *creativeSelectedFileMd5;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__getAllChangedObjectsRequest
#define SOAP_TYPE__ns1__getAllChangedObjectsRequest (58)
/* ns1:getAllChangedObjectsRequest */
struct _ns1__getAllChangedObjectsRequest
{
	time_t startTime;	/* required element of type xsd:dateTime */
	int __sizecampaignIds;	/* sequence of elements <campaignIds> */
	LONG64 *campaignIds;	/* optional element of type xsd:long */
	enum xsd__boolean *changedCampaignFile;	/* optional element of type xsd:boolean */
	enum xsd__boolean *changedAdgroupFile;	/* optional element of type xsd:boolean */
	enum xsd__boolean *changedKeywordFile;	/* optional element of type xsd:boolean */
	enum xsd__boolean *changedCreativeFile;	/* optional element of type xsd:boolean */
	enum xsd__boolean *includeTemp;	/* optional element of type xsd:boolean */
	int *format;	/* optional element of type xsd:int */
	int __sizevariableColumns;	/* sequence of elements <variableColumns> */
	struct ns1__VariableColumn *variableColumns;	/* optional element of type ns1:VariableColumn */
	int *changedNewCreativeFiles;	/* optional element of type xsd:int */
	int *includeTempChangedNewCreatives;	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE__ns1__getAllChangedObjectsResponse
#define SOAP_TYPE__ns1__getAllChangedObjectsResponse (59)
/* ns1:getAllChangedObjectsResponse */
struct _ns1__getAllChangedObjectsResponse
{
	char *fileId;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__getAllChangedObjectsPathRequest
#define SOAP_TYPE__ns1__getAllChangedObjectsPathRequest (60)
/* ns1:getAllChangedObjectsPathRequest */
struct _ns1__getAllChangedObjectsPathRequest
{
	char *fileId;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__getAllChangedObjectsPathResponse
#define SOAP_TYPE__ns1__getAllChangedObjectsPathResponse (61)
/* ns1:getAllChangedObjectsPathResponse */
struct _ns1__getAllChangedObjectsPathResponse
{
	char *changedCampaignFilePath;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
	char *changedCampaignFileMd5;	/* optional element of type xsd:string */
	char *changedAdgroupFilePath;	/* optional element of type xsd:string */
	char *changedAdgroupFileMd5;	/* optional element of type xsd:string */
	char *changedKeywordFilePath;	/* optional element of type xsd:string */
	char *changedKeywordFileMd5;	/* optional element of type xsd:string */
	char *changedCreativeFilePath;	/* optional element of type xsd:string */
	char *changedCreativeFileMd5;	/* optional element of type xsd:string */
	int __sizechangedNewCreativeFilePaths;	/* sequence of elements <changedNewCreativeFilePaths> */
	char **changedNewCreativeFilePaths;	/* optional element of type xsd:string */
	int __sizechangedNewCreativeFileMd5s;	/* sequence of elements <changedNewCreativeFileMd5s> */
	char **changedNewCreativeFileMd5s;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__gettopNKeywordsDataRequest
#define SOAP_TYPE__ns1__gettopNKeywordsDataRequest (62)
/* ns1:gettopNKeywordsDataRequest */
struct _ns1__gettopNKeywordsDataRequest
{
	int *startRank;	/* optional element of type xsd:int */
	int *endRank;	/* optional element of type xsd:int */
	int *standardvalue;	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE__ns1__gettopNKeywordsDataResponse
#define SOAP_TYPE__ns1__gettopNKeywordsDataResponse (63)
/* ns1:gettopNKeywordsDataResponse */
struct _ns1__gettopNKeywordsDataResponse
{
	int __sizetopNkeywordsData;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* sequence of elements <topNkeywordsData> */
	struct ns1__TopNkeywordsData *topNkeywordsData;	/* optional element of type ns1:TopNkeywordsData */
};
#endif

#ifndef SOAP_TYPE__ns1__updateAccountBudgetRequest
#define SOAP_TYPE__ns1__updateAccountBudgetRequest (65)
/* ns1:updateAccountBudgetRequest */
struct _ns1__updateAccountBudgetRequest
{
	int *type;	/* optional element of type xsd:int */
	double accountBudget;	/* required element of type xsd:double */
};
#endif

#ifndef SOAP_TYPE__ns1__updateAccountBudgetResponse
#define SOAP_TYPE__ns1__updateAccountBudgetResponse (66)
/* ns1:updateAccountBudgetResponse */
struct _ns1__updateAccountBudgetResponse
{
	int effectiveType;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
	double accountBudget;	/* required element of type xsd:double */
};
#endif

#ifndef SOAP_TYPE__ns1__getAccountBudgetRequest
#define SOAP_TYPE__ns1__getAccountBudgetRequest (67)
/* ns1:getAccountBudgetRequest */
struct _ns1__getAccountBudgetRequest
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__ns1__getAccountBudgetResponse
#define SOAP_TYPE__ns1__getAccountBudgetResponse (68)
/* ns1:getAccountBudgetResponse */
struct _ns1__getAccountBudgetResponse
{
	int effectiveType;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
	double accountBudget;	/* required element of type xsd:double */
	int __sizeweeklyBudget;	/* sequence of elements <weeklyBudget> */
	double *weeklyBudget;	/* optional element of type xsd:double */
};
#endif

#ifndef SOAP_TYPE__ns1__GetChangedNewCreativeIdRequest
#define SOAP_TYPE__ns1__GetChangedNewCreativeIdRequest (69)
/* ns1:GetChangedNewCreativeIdRequest */
struct _ns1__GetChangedNewCreativeIdRequest
{
	time_t startTime;	/* required element of type xsd:dateTime */
	int *type;	/* optional element of type xsd:int */
	int __sizeids;	/* sequence of elements <ids> */
	LONG64 *ids;	/* optional element of type xsd:long */
	int newCreativeType;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE__ns1__GetChangedNewCreativeIdResponse
#define SOAP_TYPE__ns1__GetChangedNewCreativeIdResponse (70)
/* ns1:GetChangedNewCreativeIdResponse */
struct _ns1__GetChangedNewCreativeIdResponse
{
	time_t *endTime;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:dateTime */
	int __sizechangedNewCreativeIds;	/* sequence of elements <changedNewCreativeIds> */
	struct ns1__ChangedNewCreativeType *changedNewCreativeIds;	/* optional element of type ns1:ChangedNewCreativeType */
};
#endif

#ifndef SOAP_TYPE_ns2__OptType
#define SOAP_TYPE_ns2__OptType (15)
/* ns2:OptType */
struct ns2__OptType
{
	int __sizeoptString;	/* sequence of elements <optString> */
	struct ns2__StringMapItemType *optString;	/* optional element of type ns2:StringMapItemType */
	int __sizeoptInt;	/* sequence of elements <optInt> */
	struct ns2__IntMapItemType *optInt;	/* optional element of type ns2:IntMapItemType */
	int __sizeoptLong;	/* sequence of elements <optLong> */
	struct ns2__LongMapItemType *optLong;	/* optional element of type ns2:LongMapItemType */
	int __sizeoptFloat;	/* sequence of elements <optFloat> */
	struct ns2__FloatMapItemType *optFloat;	/* optional element of type ns2:FloatMapItemType */
	int __sizeoptDouble;	/* sequence of elements <optDouble> */
	struct ns2__DoubleMapItemType *optDouble;	/* optional element of type ns2:DoubleMapItemType */
};
#endif

#ifndef SOAP_TYPE_ns2__StringMapItemType
#define SOAP_TYPE_ns2__StringMapItemType (72)
/* ns2:StringMapItemType */
struct ns2__StringMapItemType
{
	char *key;	/* required element of type xsd:string */
	char *value;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns2__IntMapItemType
#define SOAP_TYPE_ns2__IntMapItemType (74)
/* ns2:IntMapItemType */
struct ns2__IntMapItemType
{
	char *key;	/* required element of type xsd:string */
	int value;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns2__LongMapItemType
#define SOAP_TYPE_ns2__LongMapItemType (76)
/* ns2:LongMapItemType */
struct ns2__LongMapItemType
{
	char *key;	/* required element of type xsd:string */
	LONG64 value;	/* required element of type xsd:long */
};
#endif

#ifndef SOAP_TYPE_ns2__FloatMapItemType
#define SOAP_TYPE_ns2__FloatMapItemType (78)
/* ns2:FloatMapItemType */
struct ns2__FloatMapItemType
{
	char *key;	/* required element of type xsd:string */
	float value;	/* required element of type xsd:float */
};
#endif

#ifndef SOAP_TYPE_ns2__DoubleMapItemType
#define SOAP_TYPE_ns2__DoubleMapItemType (80)
/* ns2:DoubleMapItemType */
struct ns2__DoubleMapItemType
{
	char *key;	/* required element of type xsd:string */
	double value;	/* required element of type xsd:double */
};
#endif

#ifndef SOAP_TYPE_ns2__AuthHeader
#define SOAP_TYPE_ns2__AuthHeader (82)
/* ns2:AuthHeader */
struct ns2__AuthHeader
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *token;	/* required element of type xsd:string */
	char *target;	/* optional element of type xsd:string */
	char *accessToken;	/* optional element of type xsd:string */
	int *account_USCOREtype;	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns2__ResHeader
#define SOAP_TYPE_ns2__ResHeader (83)
/* ns2:ResHeader */
struct ns2__ResHeader
{
	char *desc;	/* required element of type xsd:string */
	int __sizefailures;	/* sequence of elements <failures> */
	struct ns2__Failure *failures;	/* optional element of type ns2:Failure */
	int *oprs;	/* optional element of type xsd:int */
	int *oprtime;	/* optional element of type xsd:int */
	int *quota;	/* optional element of type xsd:int */
	int *rquota;	/* optional element of type xsd:int */
	int status;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns2__Failure
#define SOAP_TYPE_ns2__Failure (84)
/* ns2:Failure */
struct ns2__Failure
{
	int code;	/* required element of type xsd:int */
	char *message;	/* optional element of type xsd:string */
	char *position;	/* required element of type xsd:string */
	char *content;	/* optional element of type xsd:string */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (86)
/* SOAP Header: */
struct SOAP_ENV__Header
{
	struct ns2__AuthHeader *ns2__AuthHeader;	/* mustUnderstand */
	struct ns2__ResHeader *ns2__ResHeader;	/* optional element of type ns2:ResHeader */
};
#endif

#endif

#ifndef SOAP_TYPE___ns1__getAccountInfo
#define SOAP_TYPE___ns1__getAccountInfo (92)
/* Operation wrapper: */
struct __ns1__getAccountInfo
{
	struct _ns1__getAccountInfoRequest *ns1__getAccountInfoRequest;	/* optional element of type ns1:getAccountInfoRequest */
};
#endif

#ifndef SOAP_TYPE___ns1__updateAccountInfo
#define SOAP_TYPE___ns1__updateAccountInfo (96)
/* Operation wrapper: */
struct __ns1__updateAccountInfo
{
	struct _ns1__updateAccountInfoRequest *ns1__updateAccountInfoRequest;	/* optional element of type ns1:updateAccountInfoRequest */
};
#endif

#ifndef SOAP_TYPE___ns1__getChangedCampaignId
#define SOAP_TYPE___ns1__getChangedCampaignId (100)
/* Operation wrapper: */
struct __ns1__getChangedCampaignId
{
	struct _ns1__getChangedCampaignIdRequest *ns1__getChangedCampaignIdRequest;	/* optional element of type ns1:getChangedCampaignIdRequest */
};
#endif

#ifndef SOAP_TYPE___ns1__getChangedAdgroupId
#define SOAP_TYPE___ns1__getChangedAdgroupId (104)
/* Operation wrapper: */
struct __ns1__getChangedAdgroupId
{
	struct _ns1__getChangedAdgroupIdRequest *ns1__getChangedAdgroupIdRequest;	/* optional element of type ns1:getChangedAdgroupIdRequest */
};
#endif

#ifndef SOAP_TYPE___ns1__getChangedItemId
#define SOAP_TYPE___ns1__getChangedItemId (108)
/* Operation wrapper: */
struct __ns1__getChangedItemId
{
	struct _ns1__getChangedItemIdRequest *ns1__getChangedItemIdRequest;	/* optional element of type ns1:getChangedItemIdRequest */
};
#endif

#ifndef SOAP_TYPE___ns1__getChangedId
#define SOAP_TYPE___ns1__getChangedId (112)
/* Operation wrapper: */
struct __ns1__getChangedId
{
	struct _ns1__getChangedIdRequest *ns1__getChangedIdRequest;	/* optional element of type ns1:getChangedIdRequest */
};
#endif

#ifndef SOAP_TYPE___ns1__getAllObjects
#define SOAP_TYPE___ns1__getAllObjects (116)
/* Operation wrapper: */
struct __ns1__getAllObjects
{
	struct _ns1__getAllObjectsRequest *ns1__getAllObjectsRequest;	/* optional element of type ns1:getAllObjectsRequest */
};
#endif

#ifndef SOAP_TYPE___ns1__getChangedScale
#define SOAP_TYPE___ns1__getChangedScale (120)
/* Operation wrapper: */
struct __ns1__getChangedScale
{
	struct _ns1__getChangedScaleRequest *ns1__getChangedScaleRequest;	/* optional element of type ns1:getChangedScaleRequest */
};
#endif

#ifndef SOAP_TYPE___ns1__getSelectedObjects
#define SOAP_TYPE___ns1__getSelectedObjects (124)
/* Operation wrapper: */
struct __ns1__getSelectedObjects
{
	struct _ns1__getSelectedObjectsRequest *ns1__getSelectedObjectsRequest;	/* optional element of type ns1:getSelectedObjectsRequest */
};
#endif

#ifndef SOAP_TYPE___ns1__getFileState
#define SOAP_TYPE___ns1__getFileState (128)
/* Operation wrapper: */
struct __ns1__getFileState
{
	struct _ns1__getFileStateRequest *ns1__getFileStateRequest;	/* optional element of type ns1:getFileStateRequest */
};
#endif

#ifndef SOAP_TYPE___ns1__getAllObjectsPath
#define SOAP_TYPE___ns1__getAllObjectsPath (132)
/* Operation wrapper: */
struct __ns1__getAllObjectsPath
{
	struct _ns1__getAllObjectsPathRequest *ns1__getAllObjectsPathRequest;	/* optional element of type ns1:getAllObjectsPathRequest */
};
#endif

#ifndef SOAP_TYPE___ns1__getSelectedObjectsPath
#define SOAP_TYPE___ns1__getSelectedObjectsPath (136)
/* Operation wrapper: */
struct __ns1__getSelectedObjectsPath
{
	struct _ns1__getSelectedObjectsPathRequest *ns1__getSelectedObjectsPathRequest;	/* optional element of type ns1:getSelectedObjectsPathRequest */
};
#endif

#ifndef SOAP_TYPE___ns1__getAllChangedObjects
#define SOAP_TYPE___ns1__getAllChangedObjects (140)
/* Operation wrapper: */
struct __ns1__getAllChangedObjects
{
	struct _ns1__getAllChangedObjectsRequest *ns1__getAllChangedObjectsRequest;	/* optional element of type ns1:getAllChangedObjectsRequest */
};
#endif

#ifndef SOAP_TYPE___ns1__getAllChangedObjectsPath
#define SOAP_TYPE___ns1__getAllChangedObjectsPath (144)
/* Operation wrapper: */
struct __ns1__getAllChangedObjectsPath
{
	struct _ns1__getAllChangedObjectsPathRequest *ns1__getAllChangedObjectsPathRequest;	/* optional element of type ns1:getAllChangedObjectsPathRequest */
};
#endif

#ifndef SOAP_TYPE___ns1__gettopNKeywordsData
#define SOAP_TYPE___ns1__gettopNKeywordsData (148)
/* Operation wrapper: */
struct __ns1__gettopNKeywordsData
{
	struct _ns1__gettopNKeywordsDataRequest *ns1__gettopNKeywordsDataRequest;	/* optional element of type ns1:gettopNKeywordsDataRequest */
};
#endif

#ifndef SOAP_TYPE___ns1__updateAccountBudget
#define SOAP_TYPE___ns1__updateAccountBudget (152)
/* Operation wrapper: */
struct __ns1__updateAccountBudget
{
	struct _ns1__updateAccountBudgetRequest *ns1__updateAccountBudgetRequest;	/* optional element of type ns1:updateAccountBudgetRequest */
};
#endif

#ifndef SOAP_TYPE___ns1__getAccountBudget
#define SOAP_TYPE___ns1__getAccountBudget (156)
/* Operation wrapper: */
struct __ns1__getAccountBudget
{
	struct _ns1__getAccountBudgetRequest *ns1__getAccountBudgetRequest;	/* optional element of type ns1:getAccountBudgetRequest */
};
#endif

#ifndef SOAP_TYPE___ns1__getChangedNewCreativeId
#define SOAP_TYPE___ns1__getChangedNewCreativeId (160)
/* Operation wrapper: */
struct __ns1__getChangedNewCreativeId
{
	struct _ns1__GetChangedNewCreativeIdRequest *ns1__GetChangedNewCreativeIdRequest;	/* optional element of type ns1:GetChangedNewCreativeIdRequest */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (161)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (163)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
	char *__any;
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (166)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (167)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stubs                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getAccountInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getAccountInfoRequest *ns1__getAccountInfoRequest, struct _ns1__getAccountInfoResponse *ns1__getAccountInfoResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__updateAccountInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__updateAccountInfoRequest *ns1__updateAccountInfoRequest, struct _ns1__updateAccountInfoResponse *ns1__updateAccountInfoResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getChangedCampaignId(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getChangedCampaignIdRequest *ns1__getChangedCampaignIdRequest, struct _ns1__getChangedCampaignIdResponse *ns1__getChangedCampaignIdResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getChangedAdgroupId(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getChangedAdgroupIdRequest *ns1__getChangedAdgroupIdRequest, struct _ns1__getChangedAdgroupIdResponse *ns1__getChangedAdgroupIdResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getChangedItemId(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getChangedItemIdRequest *ns1__getChangedItemIdRequest, struct _ns1__getChangedItemIdResponse *ns1__getChangedItemIdResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getChangedId(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getChangedIdRequest *ns1__getChangedIdRequest, struct _ns1__getChangedIdResponse *ns1__getChangedIdResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getAllObjects(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getAllObjectsRequest *ns1__getAllObjectsRequest, struct _ns1__getAllObjectsResponse *ns1__getAllObjectsResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getChangedScale(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getChangedScaleRequest *ns1__getChangedScaleRequest, struct _ns1__getChangedScaleResponse *ns1__getChangedScaleResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getSelectedObjects(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getSelectedObjectsRequest *ns1__getSelectedObjectsRequest, struct _ns1__getSelectedObjectsResponse *ns1__getSelectedObjectsResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getFileState(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getFileStateRequest *ns1__getFileStateRequest, struct _ns1__getFileStateResponse *ns1__getFileStateResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getAllObjectsPath(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getAllObjectsPathRequest *ns1__getAllObjectsPathRequest, struct _ns1__getAllObjectsPathResponse *ns1__getAllObjectsPathResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getSelectedObjectsPath(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getSelectedObjectsPathRequest *ns1__getSelectedObjectsPathRequest, struct _ns1__getSelectedObjectsPathResponse *ns1__getSelectedObjectsPathResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getAllChangedObjects(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getAllChangedObjectsRequest *ns1__getAllChangedObjectsRequest, struct _ns1__getAllChangedObjectsResponse *ns1__getAllChangedObjectsResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getAllChangedObjectsPath(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getAllChangedObjectsPathRequest *ns1__getAllChangedObjectsPathRequest, struct _ns1__getAllChangedObjectsPathResponse *ns1__getAllChangedObjectsPathResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__gettopNKeywordsData(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__gettopNKeywordsDataRequest *ns1__gettopNKeywordsDataRequest, struct _ns1__gettopNKeywordsDataResponse *ns1__gettopNKeywordsDataResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__updateAccountBudget(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__updateAccountBudgetRequest *ns1__updateAccountBudgetRequest, struct _ns1__updateAccountBudgetResponse *ns1__updateAccountBudgetResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getAccountBudget(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getAccountBudgetRequest *ns1__getAccountBudgetRequest, struct _ns1__getAccountBudgetResponse *ns1__getAccountBudgetResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getChangedNewCreativeId(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__GetChangedNewCreativeIdRequest *ns1__GetChangedNewCreativeIdRequest, struct _ns1__GetChangedNewCreativeIdResponse *ns1__GetChangedNewCreativeIdResponse);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapStub.h */
