<!-- Header -->
        <?php Yaf_Loader::import(PATH_APP . '/modules/Admin/views/head.phtml'); ?>

                <div class="navbar content-navbar navbar-default navbar-xs" data-toggle="breakpoint"
                     data-class-xs="navbar content-navbar navbar-inverse navbar-xs"
                     data-class-sm="navbar content-navbar navbar-default navbar-xs">
                    <div class="navbar-header">
                        <button class="navbar-toggle pull-left" data-toggle="class" data-target="#body-content" data-class-name="show_menu">
                            <i class="icon-list"></i>
                        </button>

                        <a title="添加小组件" href="/xadmin/userwidget/add/?user=1&amp;page_id=home&amp;_redirect=/" class="navbar-toggle pull-right">
                            <i class="icon-plus icon-white"></i></a>
                        <a class="navbar-brand" data-toggle="collapse" data-target="#top-nav .navbar-collapse">

                            <i class="icon-home" style='position:relative;top:4px;'></i> 当前位置：会员列表

                        </a>
                    </div>
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">   
                        </ul>
                        <!--                        <div class="navbar-btn navbar-right hide-xs">
                                                    <a title="添加用户" href="/admin/managemember/add/" class="btn btn-primary">
                                                        <i class="icon-plus icon-white"></i> <span>添加会员</span></a>
                                                </div>-->
                    </div>
                </div>    

                <?php
                $alerts = Alert::get();
                if ($alerts) {
                    foreach ($alerts as $type => $alert) {
                        ?>
                        <div class="alert alert-<?php echo $type; ?> alert-dismissable">
                            <button type="button" class="close" data-dismiss="alert">×</button>
                            <?php echo $alert; ?>
                        </div>
                        <?php
                    }
                }
                ?>


                <div class="dashboard row">
                    <div class="col-sm-12 column">
                        <!--栏目列表-->
                        <div class="panel panel-default widget addform form-horizontal short_label fieldset" id="88">
                            <div class="panel-heading"><i class='icon icon-chevron-up chevron'></i><h3 class="panel-title">
                                    会员列表
                                </h3></div>
                            <div class="panel-body " >

                                <table class="table table-hover table-striped">
                                    <tr>
                                        <th>ID</th>
                                        <th>用户名</th>
                                        <th>昵称</th>
                                        <th>email</th>
                                        <th>电话</th>
                                        <th>状态</th>
                                        <th>最后登录时间</th>
                                        <th>操作</th>
                                    </tr>
                                    <?php
                                    if ($data['data']) {
                                        foreach ($data['data'] as $key => $member) {
                                            ?>                                   
                                            <tr>
                                                <td><?php echo $member['id']; ?></td>
                                                <td><?php echo $member['username'] ?></td>
                                                <td><?php echo $member['nickname'] ?></td>
                                                <td><?php echo $member['email'] ?></td>
                                                <td><?php echo $member['phone'] ?></td>
                                                <td style='width:8%;'><?php echo $member['status'] ? '√' : 'X'; ?></td>
                                                <td><?php echo date('Y-m-d H:i:s', $member['last_login_time']); ?></td>
                                                <td>
                                                    <a href='/admin/managemember/edit?id=<?php echo $member['id'] ?>'>编辑</a>
                                                    <a href='/admin/managemember/delete?id=<?php echo $member['id'] ?>' onclick="javascript:return confirm('确定要删除该用户吗？')">删除</a>
                                                </td>
                                            </tr>
                                            <?php
                                        }
                                    }
                                    ?>
                                    <tr>
                                        <td colspan=9 style='text-align:right;'><?php echo isset($data['page'])?$data['page']:''; ?> </td>
                                    </tr>
                                </table>
                            </div>

                        </div>
                    </div>
                </div>
                <input type='hidden' id='_portal_key' value='dashboard:home:pos' />


        <!--footer-->
        <?php Yaf_Loader::import(PATH_APP . '/modules/Admin/views/foot.phtml'); ?>